# 差异订单:根据业务单id获取差异订单详情 配送退货|配送收货时传差异单id 平台退回|销售退货时传业务单id
query differenceOrderDetail($orderId: ID!, $orderType: DifferenceOrderType) {
  differenceOrderDetail(orderId: $orderId, orderType: $orderType) {
    belongOrg {
      orgId
      orgName
    }
    createUser {
      phoneNum
      userId
      userName
    }
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    businessCode
    businessId
    commodityList {
      batchInfo {
        warehouse {
          warehouseId
          warehouseName
        }
        batchCode
        batchId
        createTime
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        commodityTypeId
        commodityTypeName
        unit {
          unitId
          unitName
        }
        quantity
        quantityItem {
          unit {
            unitId
            unitName
          }
          quantity
        }
      }
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      commodityType {
        commodityTypeId
        commodityTypeName
      }
      businessItemId
      orderId
      orderItemId
      planCode
      planSaleTime
      reason
      saleOrderItemId
      markList
      markNameList
      batch {
        batchCode
        batchId
        createTime
        sourceBatchCode
        sourceBatchId
        unit {
          unitId
          unitName
        }
        quantity
        quantityItem {
          unit {
            unitId
            unitName
          }
          quantity
        }
      }
      originDeliveryExtendInfo {
        deliveryGoodsSource
        deliveryGoodsSourceDesc
        warehouse {
          address
          belongId
          belongType
          houseNumber
          id
          locationList
          name
          orgId
          remark
          status
          typeId
        }
      }
      quantity
      quantityItem {
        unit {
          unitId
          unitName
        }
        quantity
      }
      unit {
        unitId
        unitName
      }
      differenceOrderType
    }
    createTime
    deliveryTime
    differenceOrderType
    differenceOrderTypeDesc
    orderCode
    orderId
    receiveTime
    returnTime
    differenceOrderStatus
    differenceOrderStatusDesc
    depletionTime
    remark
  }
}