# 代卖调拨费用单:列表
query pageAgencyTradeTransferBill($page: Page, $pageAgencyTradeTransferBillInput: PageAgencyTradeTransferBillInput) {
  pageAgencyTradeTransferBill(
    page: $page
    pageAgencyTradeTransferBillInput: $pageAgencyTradeTransferBillInput
  ) {
    pageCurrent
    pageSize
    records {
      agencyTradeTransferAuditBy {
        phoneNum
        userId
        userName
      }
      agencyTradeTransferAuditTime
      agencyTradeTransferBillCommodity {
        billCode
        billPaymentFeeItemList {
          amount
          batch {
            batchCode
            batchId
            unit {
              unitId
              unitName
            }
            createTime
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
            sourceBatchCode
            sourceBatchId
          }
          commoditySku {
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
            availableSkuQuantity {
              businessUnit {
                unitId
                unitName
              }
              unit {
                unitId
                unitName
              }
              conversion
            }
            baseUnit {
              unitId
              unitName
            }
          }
          costUnitPrice
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          unitPrice
          dynamicQuantity {
            unit {
              unitId
              unitName
            }
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
        }
        remark
        totalAmount
      }
      agencyTradeTransferOtherBill {
        agencyTradeTransferOtherItemBill {
          amount
          billFreightItemId
          billFreightType
          billFrightTypeName
          brand
          freightAttribute
          payMode
          payModeName
          phone
          remark
          supplier {
            supplierId
            supplierName
          }
          paymentType
        }
        billCode
        totalAmount
      }
      billAuditBy {
        phoneNum
        userId
        userName
      }
      billId
      billStatus
      billStatusName
      commodityType
      commodityTypeName
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      flowCode
      flowId
      flowStatus
      flowStatusName
      flowType
      flowTypeName
      remark
      sourceAppId
      sourceBelongOrg {
        orgId
        orgName
      }
      sourceId
      sourceOrg {
        orgId
        orgName
      }
      sourceWarehouse {
        warehouseId
        warehouseName
      }
      targetAppId
      targetBelongOrg {
        orgId
        orgName
      }
      targetOrg {
        orgId
        orgName
      }
      targetWarehouse {
        warehouseId
        warehouseName
      }
      refuseNote
      consignmentOrderCode
      sourceBill {
        belongOrg {
          orgId
          orgName
        }
        createBy {
          phoneNum
          userId
          userName
        }
        customerBelongInfo {
          customerId
          customerName
          customerType
        }
        billFreightResp {
          billCode
          billItemId
          callInsList {
            supplier {
              supplierId
              supplierName
            }
            amount
            billFreightItemId
            billFreightType
            billFrightTypeName
            brand
            freightAttribute
            launchLink
            launchOrg
            payMode
            payModeName
            paymentType
            phone
            remark
          }
          totalAmount
        }
        billId
        billOperationLogPayload {
          user {
            phoneNum
            userId
            userName
          }
          createTime
          endStatus
          endStatusDesc
          note
          startStatus
          startStatusDesc
        }
        billPaymentResp {
          supplier {
            supplierId
            supplierName
          }
          billCode
          billNote
          billPaymentFeeItemRespsList {
            batchInfo {
              customer {
                customerId
                customerName
                customerType
                lastLevelId
                lastLevelName
              }
              unit {
                unitId
                unitName
              }
              warehouse {
                warehouseId
                warehouseName
              }
              batchCode
              batchId
              commodityTypeId
              commodityTypeName
              createTime
              quantity
              quantityItem {
                unit {
                  unitId
                  unitName
                }
                quantity
              }
            }
            commoditySku {
              availableSkuQuantity {
                businessUnit {
                  unitId
                  unitName
                }
                unit {
                  unitId
                  unitName
                }
                conversion
              }
              baseUnit {
                unitId
                unitName
              }
              categoryId
              categoryName
              commodityId
              commodityName
              commoditySkuId
              commoditySkuName
              commoditySpecOptionId
              commoditySpecOptionName
            }
            unit {
              unitId
              unitName
            }
            amount
            costUnitPrice
            grossUnitQuantity
            itemId
            quantity
            sourceBatchId
            stockType
            unitPrice
          }
          totalAmount
        }
        billSource
        billSourceDesc
        billStatus
        billStatusDesc
        businessId
        businessInfo {
          domesticCollectiveProcurementReturnsAndLoss {
            belongOrg {
              orgId
              orgName
            }
            createBy {
              phoneNum
              userId
              userName
            }
            customer {
              customerId
              customerName
              customerType
              lastLevelId
              lastLevelName
            }
            supplier {
              supplierId
              supplierName
            }
            warehouse {
              warehouseId
              warehouseName
            }
            businessType
            businessTypeName
            commodities {
              totalType {
                unitId
                unitName
              }
              unitType {
                unitId
                unitName
              }
              commoditySkuId
            }
            commodityTypeId
            commodityTypeName
            createTime
            domesticCollectiveCode
            note
          }
          internalConsignmentSaleAndPurchase {
            belongOrg {
              orgId
              orgName
            }
            createBy {
              phoneNum
              userId
              userName
            }
            customer {
              customerId
              customerName
              customerType
              lastLevelId
              lastLevelName
            }
            purchaser {
              phoneNum
              userId
              userName
            }
            supplier {
              supplierId
              supplierName
            }
            warehouse {
              warehouseId
              warehouseName
            }
            businessType
            businessTypeName
            commodityTypeId
            commodityTypeName
            internalConsignmentCode
            note
            purchaseDate
            saleDate
            subType
          }
          internalPurchaseAndSaleReturn {
            belongOrg {
              orgId
              orgName
            }
            createBy {
              phoneNum
              userId
              userName
            }
            customer {
              customerId
              customerName
              customerType
              lastLevelId
              lastLevelName
            }
            supplier {
              supplierId
              supplierName
            }
            warehouse {
              warehouseId
              warehouseName
            }
            code
            commodityType
            commodityTypeName
            createTime
            exrOrderSubTypeName
            extOrderSubType
            extOrderType
            extOrderTypeName
            note
            returnWay
            returnWayDesc
            waitConfirmFlag
          }
          otherIn {
            supplier {
              supplierId
              supplierName
            }
            wmsMarkList {
              appId
              businessType
              labelContent
              markId
              tenantId
            }
            commodityType
            commodityTypeName
            inOrderCode
            inOrderTypeDesc
            remark
          }
          otherOutInfo {
            supplier {
              supplierId
              supplierName
            }
            wmsMarkList {
              appId
              businessType
              labelContent
              markId
              tenantId
            }
            commodityType
            commodityTypeName
            orderCode
            orderTypeDesc
            remark
          }
          selfPurchase {
            businessCode
            commodityType
            commodityTypeName
            purchaseTime
          }
        }
        createTime
        refuseNote
        warehouse {
          address
          belongId
          belongType
          houseNumber
          id
          locationList
          name
          orgId
          remark
          status
          typeId
        }
      }
    }
    totalRecords
  }
}

# 代卖调拨费用单:详情
query getAgencyTradeTransferBill($getAgencyTradeTransferBillInput: GetAgencyTradeTransferBillInput) {
  getAgencyTradeTransferBill(
    getAgencyTradeTransferBillInput: $getAgencyTradeTransferBillInput
  ) {
    agencyTradeTransferAuditBy {
      phoneNum
      userId
      userName
    }
    agencyTradeTransferAuditTime
    agencyTradeTransferBillCommodity {
      billCode
      billPaymentFeeItemList {
        amount
        batch {
          batchCode
          batchId
          unit {
            unitId
            unitName
          }
          createTime
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
          sourceBatchCode
          sourceBatchId
        }
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
        }
        costUnitPrice
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        unitPrice
        dynamicQuantity {
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
      }
      remark
      totalAmount
    }
    agencyTradeTransferOtherBill {
      agencyTradeTransferOtherItemBill {
        amount
        billFreightItemId
        billFreightType
        billFrightTypeName
        brand
        freightAttribute
        payMode
        payModeName
        phone
        remark
        supplier {
          supplierId
          supplierName
        }
        paymentType
      }
      billCode
      totalAmount
    }
    billAuditBy {
      phoneNum
      userId
      userName
    }
    billId
    billStatus
    billStatusName
    commodityType
    commodityTypeName
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    flowCode
    flowId
    flowStatus
    flowStatusName
    flowType
    flowTypeName
    remark
    sourceAppId
    sourceBelongOrg {
      orgId
      orgName
    }
    sourceId
    sourceOrg {
      orgId
      orgName
    }
    sourceWarehouse {
      warehouseId
      warehouseName
    }
    targetAppId
    targetBelongOrg {
      orgId
      orgName
    }
    targetOrg {
      orgId
      orgName
    }
    targetWarehouse {
      warehouseId
      warehouseName
    }
    refuseNote
    consignmentOrderCode
    sourceBill {
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customerBelongInfo {
        customerId
        customerName
        customerType
      }
      billFreightResp {
        billCode
        billItemId
        callInsList {
          amount
          billFreightItemId
          billFreightType
          freightAttribute
          launchLink
          launchOrg
          payMode
          paymentType
          phone
          supplier {
            supplierId
            supplierName
          }
          billFrightTypeName
          brand
          payModeName
          remark
        }
        totalAmount
      }
      billId
      billOperationLogPayload {
        user {
          phoneNum
          userId
          userName
        }
        createTime
        endStatus
        endStatusDesc
        note
        startStatus
        startStatusDesc
      }
      billPaymentResp {
        supplier {
          supplierId
          supplierName
        }
        billCode
        billNote
        billPaymentFeeItemRespsList {
          batchInfo {
            customer {
              customerId
              customerName
              customerType
              lastLevelId
              lastLevelName
            }
            warehouse {
              warehouseId
              warehouseName
            }
            batchCode
            batchId
            commodityTypeId
            commodityTypeName
            createTime
            unit {
              unitId
              unitName
            }
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
          commoditySku {
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
            availableSkuQuantity {
              businessUnit {
                unitId
                unitName
              }
              unit {
                unitId
                unitName
              }
              conversion
            }
            baseUnit {
              unitId
              unitName
            }
          }
          amount
          costUnitPrice
          grossUnitQuantity
          itemId
          sourceBatchId
          stockType
          unitPrice
          unit {
            unitId
            unitName
          }
          quantity
        }
        totalAmount
      }
      billSource
      billSourceDesc
      billStatus
      billStatusDesc
      businessId
      businessInfo {
        domesticCollectiveProcurementReturnsAndLoss {
          belongOrg {
            orgId
            orgName
          }
          createBy {
            phoneNum
            userId
            userName
          }
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          supplier {
            supplierId
            supplierName
          }
          warehouse {
            warehouseId
            warehouseName
          }
          businessType
          businessTypeName
          commodities {
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
            commoditySkuId
          }
          commodityTypeId
          commodityTypeName
          createTime
          domesticCollectiveCode
          note
        }
        internalConsignmentSaleAndPurchase {
          belongOrg {
            orgId
            orgName
          }
          createBy {
            phoneNum
            userId
            userName
          }
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          purchaser {
            phoneNum
            userId
            userName
          }
          supplier {
            supplierId
            supplierName
          }
          warehouse {
            warehouseId
            warehouseName
          }
          businessType
          businessTypeName
          commodityTypeId
          commodityTypeName
          internalConsignmentCode
          note
          purchaseDate
          saleDate
          subType
        }
        internalPurchaseAndSaleReturn {
          belongOrg {
            orgId
            orgName
          }
          createBy {
            phoneNum
            userId
            userName
          }
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          supplier {
            supplierId
            supplierName
          }
          warehouse {
            warehouseId
            warehouseName
          }
          code
          commodityType
          commodityTypeName
          createTime
          exrOrderSubTypeName
          extOrderSubType
          extOrderType
          extOrderTypeName
          note
          waitConfirmFlag
          returnWay
          returnWayDesc
        }
        otherIn {
          supplier {
            supplierId
            supplierName
          }
          wmsMarkList {
            appId
            businessType
            labelContent
            markId
            tenantId
          }
          commodityType
          commodityTypeName
          inOrderCode
          inOrderTypeDesc
          remark
        }
        otherOutInfo {
          supplier {
            supplierId
            supplierName
          }
          wmsMarkList {
            appId
            businessType
            labelContent
            markId
            tenantId
          }
          commodityType
          commodityTypeName
          orderCode
          orderTypeDesc
          remark
        }
        selfPurchase {
          businessCode
          commodityType
          commodityTypeName
          purchaseTime
        }
      }
      createTime
      refuseNote
      warehouse {
        address
        belongId
        belongType
        houseNumber
        id
        locationList
        name
        orgId
        remark
        status
        typeId
      }
    }
  }
}

mutation auditAgencyTradeTransferBill($auditAgencyTradeTransferBillInput: AuditAgencyTradeTransferBillInput) {
  auditAgencyTradeTransferBill(
    auditAgencyTradeTransferBillInput: $auditAgencyTradeTransferBillInput
  )
}

mutation rejectAgencyTradeTransferBill($rejectAgencyTradeTransferBillInput: RejectAgencyTradeTransferBillInput) {
  rejectAgencyTradeTransferBill(
    rejectAgencyTradeTransferBillInput: $rejectAgencyTradeTransferBillInput
  )
}

mutation updateAgencyTradeTransferOtherBill($updateAgencyTradeTransferOtherBillInput: UpdateAgencyTradeTransferOtherBillInput) {
  updateAgencyTradeTransferOtherBill(
    updateAgencyTradeTransferOtherBillInput: $updateAgencyTradeTransferOtherBillInput
  )
}

query transferBillCountStatistic($transferBillCountStatisticInput: TransferBillCountStatisticInput) {
  transferBillCountStatistic(
    transferBillCountStatisticInput: $transferBillCountStatisticInput
  ) {
    agencyTradeBillCount {
      toAudit
      toSubmit
    }
    transferBillCount {
      toAudit
      toSubmit
    }
  }
}