# 查询调拨费用订单
query listTransferBill(
  $listTransferBillInput: ListTransferBillInput
  $page: Page
) {
  listTransferBill(listTransferBillInput: $listTransferBillInput, page: $page) {
    records {
      billId
      flowId
      flowCode
      orderId
      orderCode
      sourceId
      sourceAppId
      flowType
      flowTypeName
      transferType
      commodityType
      commodityTypeName
      sourceWarehouseId
      sourceWarehouseName
      sourceBelongType
      sourceBelongId
      sourceBelongName
      targetWarehouseId
      targetWarehouseName
      targetBelongType
      targetBelongId
      targetBelongName
      remark
      flowStatus
      flowStatusName
      billStatus
      billStatusCode
      billStatusName
      flowApplyCreateTime
      flowCreateBy
      flowCreateName
      stockUpdateTime
      stockCreateBy
      stockCreateName
      stockAuditUser
      stockAuditUserName
      billAuditBy
      billAuditName
      transferCommodityBill {
        billCode
        remark
        totalAmount
        transferCommodityItemBills {
          itemId
          commodityId
          commodityName
          commoditySkuId
          commoditySpecOptionId
          skuTextDescription
          unitQuantity
          unitType
          unitTypeName
          totalQuantity
          totalType
          totalTypeName
          unitPrice
          priceType
          priceTypeName
          batchId
          batchCode
          createTime
          createBy
          updateTime
          updateBy
          stockUnitQuantity
          stockTotalQuantity
          customerId
          customerName
          conversion
          amount
          skuDetail {
            commoditySkuId
            commoditySkuName
            commodityId
            commodityName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
          }
        }
      }
      transferOtherBill {
        billItemId
        billCode
        totalAmount
        transferOrderFeeItems {
          attr
          billType
          billTypeText
          payMode
          payModeText
          supplierId
          supplierName
          amount
          brand
          phone
          remark
          createTime
          createBy
          updateTime
          updateBy
          billFreightItemId
        }
      }
      refuseNote
      sourceTotalAmount
      targetTotalAmount
      recordUpdateTime
      belongOrg {
        orgId
        orgName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 查询调拨费用订单详情
query getTransferBill($flowId: ID) {
  getTransferBill(flowId: $flowId) {
    billId
    flowId
    flowCode
    orderId
    orderCode
    sourceId
    sourceAppId
    flowType
    flowTypeName
    transferType
    commodityType
    commodityTypeName
    sourceWarehouseId
    sourceWarehouseName
    sourceBelongType
    sourceBelongId
    sourceBelongName
    targetWarehouseId
    targetWarehouseName
    targetBelongType
    targetBelongId
    targetBelongName
    remark
    flowStatus
    flowStatusName
    billStatus
    billStatusCode
    billStatusName
    flowApplyCreateTime
    flowCreateBy
    flowCreateName
    stockUpdateTime
    stockCreateBy
    stockCreateName
    stockAuditUser
    stockAuditUserName
    billAuditBy
    billAuditName
    transferCommodityBill {
      billCode
      remark
      totalAmount
      transferCommodityItemBills {
        itemId
        commodityId
        commodityName
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        unitQuantity
        unitType
        unitTypeName
        totalQuantity
        totalType
        totalTypeName
        unitPrice
        priceType
        priceTypeName
        batchId
        batchCode
        createTime
        createBy
        updateTime
        updateBy
        stockUnitQuantity
        stockTotalQuantity
        customerId
        customerName
        conversion
        amount
        skuDetail {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
      }
    }
    transferOtherBill {
      billItemId
      billCode
      totalAmount
      transferOrderFeeItems {
        attr
        billType
        billTypeText
        payMode
        payModeText
        supplierId
        supplierName
        amount
        brand
        phone
        remark
        createTime
        createBy
        updateTime
        updateBy
        billFreightItemId
      }
    }
    refuseNote
    sourceTotalAmount
    targetTotalAmount
    recordUpdateTime
    belongOrg {
      orgId
      orgName
    }
  }
}

# 查询调拨费用单状态值
query getTransferOrderFeeStatus(
  $getTransferBillStatusInput: GetTransferBillStatusInput
) {
  getTransferOrderFeeStatus(
    getTransferBillStatusInput: $getTransferBillStatusInput
  ) {
    toSubmit
    toAudit
  }
}

# 调拨出库货款单修改
mutation updateTransferCommodityBill(
  $updateFlowTransferCommodityBillInput: UpdateFlowTransferCommodityBillInput
) {
  updateTransferCommodityBill(
    updateFlowTransferCommodityBillInput: $updateFlowTransferCommodityBillInput
  )
}

# 调拨出入库运杂款修改
mutation updateTransferOtherBill(
  $updateFlowTransferOtherBillInput: UpdateFlowTransferOtherBillInput
) {
  updateTransferOtherBill(
    updateFlowTransferOtherBillInput: $updateFlowTransferOtherBillInput
  )
}

# 提交出入库费用单审核
mutation updateTransferStat(
  $updateTransferOrderStatInput: UpdateTransferOrderStatInput
) {
  updateTransferStat(
    updateTransferOrderStatInput: $updateTransferOrderStatInput
  )
}
