query countInternalConsignmentStatus {
  countInternalConsignmentStatus {
    unSubmitted
  }
}

# 内部代卖: 详情页
query internalConsignmentOrder($input: PitayaInternalConsignmentIDInput) {
  internalConsignmentOrder(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    cancelableFlag
    commodities {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      itemId
      stockBatchInfo {
        batchCode
        batchId
        customerBelongInfo {
          customerId
          customerName
          customerType
        }
        unit {
          unitId
          unitName
        }
        createTime
        lockQuantity
        lockQuantityItem {
          unit {
            unitId
            unitName
          }
          quantity
        }
        quantity
        quantityItem {
          unit {
            unitId
            unitName
          }
          quantity
        }
      }
      dynamicQuantity {
        unit {
          unitId
          unitName
        }
        quantity
        quantityItem {
          unit {
            unitId
            unitName
          }
          quantity
        }
      }
    }
    commodityTypeId
    commodityTypeName
    consignmentOrg {
      orgId
      orgName
    }
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    orderCode
    orderId
    orderStatus
    orderStatusName
    remark
    totalTransportFees
    transferOtherItemBills {
      amount
      billFreightItemId
      billFreightType
      billFreightTypeName
      licensePlate
      payMode
      payModeName
      phone
      remark
      supplier {
        supplierId
        supplierName
      }
      paymentType
    }
    warehouse {
      warehouseId
      warehouseName
    }
    errorDesc
  }
}

query listConsignmentOrg($input: PitayaListConsignmentOrgInput) {
  listConsignmentOrg(input: $input) {
    country
    id
    leadingId
    operatorId
    orgName
    parentId
    parentName
    remark
    tenantId
  }
}

# 内部代卖: 列表页
query pageInternalConsignment($input: PitayaPageInternalConsignmentInput, $page: Page) {
  pageInternalConsignment(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      commodities {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
        }
        itemId
        stockBatchInfo {
          batchCode
          batchId
          customerBelongInfo {
            customerId
            customerName
            customerType
          }
          unit {
            unitId
            unitName
          }
          createTime
          lockQuantity
          lockQuantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        dynamicQuantity {
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
      }
      commodityTypeId
      commodityTypeName
      consignmentOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      orderCode
      orderId
      orderStatus
      orderStatusName
      remark
      warehouse {
        warehouseId
        warehouseName
      }
      cancelableFlag
      errorDesc
      totalTransportFees
      transferOtherItemBills {
        supplier {
          supplierId
          supplierName
        }
        amount
        billFreightItemId
        billFreightType
        billFreightTypeName
        licensePlate
        payMode
        payModeName
        paymentType
        phone
        remark
      }
    }
    totalRecords
  }
}

mutation cancelConsignmentOrder($input: PitayaInternalConsignmentIDInput) {
  cancelConsignmentOrder(input: $input)
}

mutation cancelInternalConsignment($input: PitayaInternalConsignmentIDInput) {
  cancelInternalConsignment(input: $input)
}

# 内部代卖: 新增
mutation createInternalConsignment($input: PitayaInternalConsignmentInput) {
  createInternalConsignment(input: $input)
}

mutation submitInternalConsignment($input: PitayaInternalConsignmentIDInput) {
  submitInternalConsignment(input: $input)
}

# 内部代卖: 修改
mutation updateInternalConsignment($input: PitayaInternalConsignmentInput, $orderId: ID!) {
  updateInternalConsignment(input: $input, orderId: $orderId)
}

query listConsignmentPayMode {
  listConsignmentPayMode {
    label: payModeName
    value: payMode
  }
}

# 代卖结算:结算详情查询
query getAgencySaleSettlementDetail($input: GetAgencySaleSettlementDetailInput) {
  getAgencySaleSettlementDetail(input: $input) {
    agencySellingFee
    agentName
    amount
    auditProcess {
      auditStatus
      auditTime
      reviewer
    }
    auditStatus
    commodityList {
      batchCommodityList {
        amount
        batchId
        inStockTime
        originalBatchId
        quantity
        skuId
        skuName
        unitId
        unitName
      }
      operationTime
      orderCode
      orderId
      sourceType
    }
    createTime
    createUser
    financialAmount
    lowerCommodityList {
      agentId
      agentName
      commodityList {
        batchCommodityList {
          amount
          batchId
          inStockTime
          originalBatchId
          quantity
          skuId
          skuName
          unitId
          unitName
        }
        operationTime
        orderCode
        orderId
        sourceType
      }
      subtotal
    }
    lowerCostList {
      amount
      available
      calculation
      costId
      costType
      fillName
      occurrence
    }
    orderCode
    orderId
    orderType
    otherCostList {
      amount
      available
      calculation
      costId
      costType
      fillName
      occurrence
    }
    otherSelfCostList {
      amount
      calculation
      costId
      costType
      fillName
      payMode
      supplierId
      supplierName
    }
    remark
    ruleValue
    settlementCode
    settlementId
    settlementRule
  }
}

query listConsignmentLog($input: PitayaInternalConsignmentIDInput) {
  listConsignmentLog(input: $input) {
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    logType
    logTypeText
  }
}

# 代卖合作:查询代卖单详情
query getAgencySaleDetail($input: AgencySaleIdInput!) {
  getAgencySaleDetail(input: $input) {
    agencySaleCode
    agencySaleId
    agencySaleType
    canCancel
    canReturn
    cooperationDays
    createTime
    creator
    existReturnBack
    parentId
    ruleValue
    settlement {
      receivableAmount
      salesAmount
      settlementAmount
      settlementList {
        auditStatus
        operator
        orgName
        receivableAmount
        settlementAmount
        settlementCode
        settlementId
        settlementTime
      }
      settlementStatus
    }
    settlementQuantity
    settlementRule
    settlementStatus
  }
}