query listTransferOptions {
  listTransferOptions {
    label
    value
  }
}

query listTransferOrgList($listTransferOrgListInput: ListTransferOrgListInput) {
  listTransferOrgList(listTransferOrgListInput: $listTransferOrgListInput) {
    value: id
    label: orgName
  }
}

query getTransferOutOrderStatus(
  $getTransferOutOrderStatusInput: GetTransferOutOrderStatusInput
) {
  getTransferOutOrderStatus(
    getTransferOutOrderStatusInput: $getTransferOutOrderStatusInput
  ) {
    toSubmit
    toProcess
  }
}

query listTransferOutOrder(
  $listTransferOrderInput: ListTransferOrderInput
  $page: Page
) {
  listTransferOutOrder(
    listTransferOrderInput: $listTransferOrderInput
    page: $page
  ) {
    records {
      flowId
      flowCode
      flowType
      flowTypeName
      transferType
      commodityType
      commodityTypeName
      sourceWarehouseId
      sourceWarehouseName
      sourceBelongId
      sourceBelongName
      targetWarehouseId
      targetWarehouseName
      targetBelongId
      targetBelongName
      flowRemark
      flowStatus
      flowStatusName
      createTime
      createBy
      createUserName
      createUserPhone
      updateBy
      updateUserName
      updateTime
      transferCommodityItemBills {
        itemId
        commodityId
        commodityName
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        unitQuantity
        unitType
        unitTypeName
        totalQuantity
        totalType
        totalTypeName
        unitPrice
        priceType
        priceTypeName
        batchId
        batchCode
        createTime
        createBy
        updateTime
        updateBy
        stockUnitQuantity
        stockTotalQuantity
        customerId
        customerName
        conversion
        amount
        skuDetail {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
      }
      transferOtherItemBills {
        attr
        billType
        billTypeText
        payMode
        payModeText
        supplierId
        supplierName
        amount
        brand
        phone
        remark
        createTime
        createBy
        updateTime
        updateBy
        billFreightItemId
      }
      totalGoodsFee
      totalTransportFees
      billId
      billStatus
      billStatusName
      reason
      direction
      sourceAppId
      targetAppId
      belongOrg {
        orgId
        orgName
      }
      targetBelongOrg {
        orgId
        orgName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

mutation createTransferOutOrder(
  $createTransferOrderInput: CreateTransferOrderInput
) {
  createTransferOutOrder(createTransferOrderInput: $createTransferOrderInput)
}

mutation updateTransferOutOrder(
  $updateTransferCommodityInput: UpdateTransferCommodityInput
) {
  updateTransferOutOrder(
    updateTransferCommodityInput: $updateTransferCommodityInput
  )
}

query getTransferOutOrder($flowId: ID) {
  getTransferOutOrder(flowId: $flowId) {
    flowId
    flowCode
    flowType
    flowTypeName
    transferType
    commodityType
    commodityTypeName
    sourceWarehouseId
    sourceWarehouseName
    sourceBelongId
    sourceBelongName
    targetWarehouseId
    targetWarehouseName
    targetBelongId
    targetBelongName
    flowRemark
    flowStatus
    flowStatusName
    createTime
    createBy
    createUserName
    createUserPhone
    updateBy
    updateUserName
    updateTime
    transferCommodityItemBills {
      itemId
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitType
      unitTypeName
      totalQuantity
      totalType
      totalTypeName
      unitPrice
      priceType
      priceTypeName
      batchId
      batchCode
      createTime
      createBy
      updateTime
      updateBy
      stockUnitQuantity
      stockTotalQuantity
      customerId
      customerName
      conversion
      amount
      skuDetail {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
    }
    transferOtherItemBills {
      attr
      billType
      billTypeText
      payMode
      payModeText
      supplierId
      supplierName
      amount
      brand
      phone
      remark
      createTime
      createBy
      updateTime
      updateBy
      billFreightItemId
    }
    totalGoodsFee
    totalTransportFees
    billId
    billStatus
    billStatusName
    reason
    direction
    sourceAppId
    targetAppId
    belongOrg {
      orgId
      orgName
    }
    targetBelongOrg {
      orgId
      orgName
    }
  }
}

query countTransferOutStockRecord(
  $queryOutRecordListInput: QueryOutRecordListInput
) {
  countTransferOutStockRecord(queryOutRecordListInput: $queryOutRecordListInput)
}

query outStockRecordDetail($queryOutRecordListInput: QueryOutRecordListInput) {
  outStockRecordDetail(queryOutRecordListInput: $queryOutRecordListInput) {
    outStockRecords {
      recordCode
      userName
      createTime
      totalCommodityAmount
      commodityType
      commoditiesList {
        commoditySkuId
        stockBatchId
        stockBatchCode
        unitQuantity
        unitType
        totalQuantity
        totalType
        unitPrice
        unitPriceType
        subtotalAmount
        commodityName
        commoditySpecOptionName
        unitTypeName
        totalTypeName
        unitPriceTypeName
      }
    }
    outStockOrderWaitCommodities {
      commoditySkuId
      unitQuantity
      unitTypeName
      unitPriceTypeName
      totalQuantity
      totalTypeName
      unitPrice
      unitPriceTypeName
      commodityName
      commoditySpecOptionName
      conversion
    }
  }
}

query getTransferInOrderStatus(
  $getTransferInOrderStatusInput: GetTransferInOrderStatusInput
) {
  getTransferInOrderStatus(
    getTransferInOrderStatusInput: $getTransferInOrderStatusInput
  ) {
    toSubmit
    toProcess
  }
}

query listTransferInOrder(
  $listTransferOrderInput: ListTransferOrderInput
  $page: Page
) {
  listTransferInOrder(
    listTransferOrderInput: $listTransferOrderInput
    page: $page
  ) {
    records {
      flowId
      flowCode
      flowType
      flowTypeName
      transferType
      commodityType
      commodityTypeName
      sourceWarehouseId
      sourceWarehouseName
      sourceBelongId
      sourceBelongName
      targetWarehouseId
      targetWarehouseName
      targetBelongId
      targetBelongName
      flowRemark
      flowStatus
      flowStatusName
      createTime
      createBy
      createUserName
      createUserPhone
      updateBy
      updateUserName
      updateTime
      transferCommodityItemBills {
        itemId
        commodityId
        commodityName
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        unitQuantity
        unitType
        unitTypeName
        totalQuantity
        totalType
        totalTypeName
        unitPrice
        priceType
        priceTypeName
        batchId
        batchCode
        createTime
        createBy
        updateTime
        updateBy
        stockUnitQuantity
        stockTotalQuantity
        customerId
        customerName
        conversion
        amount
        skuDetail {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
      }
      transferOtherItemBills {
        attr
        billType
        billTypeText
        payMode
        payModeText
        supplierId
        supplierName
        amount
        brand
        phone
        remark
        createTime
        createBy
        updateTime
        updateBy
        billFreightItemId
      }
      totalGoodsFee
      totalTransportFees
      billId
      billStatus
      billStatusName
      reason
      direction
      sourceAppId
      targetAppId
      belongOrg {
        orgId
        orgName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

query getTransferInOrder($flowId: ID) {
  getTransferInOrder(flowId: $flowId) {
    flowId
    flowCode
    flowType
    flowTypeName
    transferType
    commodityType
    commodityTypeName
    sourceWarehouseId
    sourceWarehouseName
    sourceBelongId
    sourceBelongName
    targetWarehouseId
    targetWarehouseName
    targetBelongId
    targetBelongName
    flowRemark
    flowStatus
    flowStatusName
    createTime
    createBy
    createUserName
    createUserPhone
    updateBy
    updateUserName
    updateTime
    transferCommodityItemBills {
      itemId
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitType
      unitTypeName
      totalQuantity
      totalType
      totalTypeName
      unitPrice
      priceType
      priceTypeName
      batchId
      batchCode
      createTime
      createBy
      updateTime
      updateBy
      stockUnitQuantity
      stockTotalQuantity
      customerId
      customerName
      conversion
      amount
      skuDetail {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
    }
    transferOtherItemBills {
      attr
      billType
      billTypeText
      payMode
      payModeText
      supplierId
      supplierName
      amount
      brand
      phone
      remark
      createTime
      createBy
      updateTime
      updateBy
      billFreightItemId
    }
    totalGoodsFee
    totalTransportFees
    billId
    billStatus
    billStatusName
    reason
    direction
    sourceAppId
    targetAppId
    belongOrg {
      orgId
      orgName
    }
  }
}

query countTransferInStockRecord($queryRecordListInput: QueryRecordListInput) {
  countTransferInStockRecord(queryRecordListInput: $queryRecordListInput)
}
