# 联营配送单: 保存
mutation saveJointVentureOrder(
  $saveJointVentureOrderInput: SaveJointVentureOrderInput
) {
  saveJointVentureOrder(saveJointVentureOrderInput: $saveJointVentureOrderInput)
}

# 联营配送单: 修改
mutation updateJointVentureOrder(
  $updateJointVentureOrderInput: UpdateJointVentureOrderInput
) {
  updateJointVentureOrder(
    updateJointVentureOrderInput: $updateJointVentureOrderInput
  )
}

# 配送单: 获取联营配送单列表详情
query jointDeliveryOrderDetail(
  $deliveryOrderDetailQueryInput: DeliveryOrderDetailQueryInput
) {
  deliveryOrderDetail(
    deliveryOrderDetailQueryInput: $deliveryOrderDetailQueryInput
  ) {
    orderId
    warehouse {
      warehouseId
      warehouseName
    }
    belongInfo {
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
    }
    businessUserName
    carNum
    carType
    deliveryType
    deliveryTypeDesc
    driverContact
    driverName
    orderCode
    orderStatus
    orderStatusDesc
    org {
      orgId
      orgName
    }
    saleOrderDate
    createBy {
      userId
      userName
      phoneNum
    }
    createTime
    deliveryOrderFee {
      amount
      billId
      feeItemId
      feeType
      feeTypeDesc
      payMode
      payModeDesc
      remark
      supplier {
        supplierId
        supplierName
      }
    }
    jointVentureOrderItem {
      itemId
      sku {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        categoryId
        categoryName
      }
      batch {
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        batchCode
        batchId
        createTime
        sourceBatchCode
        sourceBatchId
        totalQuantity
        unitQuantity
      }
      outTotalQuantity
      outUnitQuantity
      totalQuantity
      unitQuantity
      batchId
      batchCode
      stockQuantity {
        unitQuantity
        totalQuantity
      }
    }
    belongOrg {
      orgId
      orgName
    }
    photos
    deliveryOrderTypeDesc
    deliveryDate
    commodityTypeId
    commodityTypeDesc
    outOrderType
    outOrderTypeDesc
    statusNote
    outOrderId
    outOrderQuantity
  }
}
