query homeBadgeCount(
  $countInternalPurchaseReturnInput: CountInternalPurchaseReturnInput
  $deliveryOrderStatusCountInput: DeliveryOrderStatusCountInput
  $countBillStatusInput: CountBillStatusInput
  $receiptQuantityInput: ReceiptQuantityInput
  $emptyCabinetBillQuantityInput: EmptyCabinetBillInput
  $countCostEntryByStatusInput: CostEntryCountInput
  $countOutOrderTypeInput: CountOutOrderTypeInput
  $input: GetStatusCountInput
  $statusGroupCountInput: StatusGroupCountInput
  $countSaleReturnInput: CountSaleReturnInput
  $damageOutStatusCountInput: DamageOutStatusCountInput
  $breakContractStatusInput: BreakContractStatusInput
  $bill1StatusInput: Bill1StatusGroupCountInput!
  $bill2StatusInput: Bill2StatusGroupCountInput!
  $countDomesticPurchaseStatusFilter: CountDomesticPurchaseStatusFilter!
  $platformReturnBadgeInput: PitayaPagePlatformReturnInput
  $incomeStatementType: BillMainTypeEnum!
  $incomeStatementTypeInput: IncomeStatementTypeInput
  $countPurchaseStatusInput: CountPurchaseStatusInput
) {
  # 内部采购: 状态统计
  pitayaCountInternalPurchaseStatus {
    toBeReceived
    received
  }
  deliveryBillStatusCount(
    deliveryOrderStatusCountInput: $deliveryOrderStatusCountInput
  ) {
    unSubmit
    unAudit
  }
  # 配送费用审核 v2.20.0
  countAllStatusDeliveryFee(countBillStatusInput: $countBillStatusInput) {
    billMainType
    billStatusNumberList {
      number
      status
    }
  }
  # 费用单操作（未接入费用模板）: 状态查询·
  bill1StatusGroupCount(input: $bill1StatusInput) {
    bizUnReviewed
    complete
    fdConfirmed
    fdUnReviewed
    unConfirmed
    unSubmitted
    billSource
  }
  # 费用单操作（接入费用模板）: 状态查询
  bill2StatusGroupCount(input: $bill2StatusInput) {
    billMainType
    billStatus
    number
  }
  receiptQuantity(input: $receiptQuantityInput) {
    finishedTotal
    totalTodoQuantity
    waitAcceptanceTotal
    waitEmptyCabinetTotal
  }
  emptyCabinetBillQuantity(input: $emptyCabinetBillQuantityInput) {
    waitCommitTotal
    waitReviewTotal
    waitTodoTotal
  }
  saleIncomeOrderStatistic {
    orderCount
    auditCount
  }
  userPlanChangedSummary {
    notHandleCount
  }
  countInOrderAudit {
    rawMaterial
    subMaterial
    finishedProduct
    defectiveProduct
    semiFinishedProduct
    turnoverBasket
    returnProduct
    damageProduct
  }
  countOutOrderType(countOutOrderTypeInput: $countOutOrderTypeInput) {
    rawMaterial
    subMaterial
    finishedProduct
    defectiveProduct
    semiFinishedProduct
    refund
    basket
  }
  auditSecondmentCount
  transferBillCountAggregate {
    toAudit
    toInSubmit
    toOutSubmit
  }
  stockAdjustmentStatus {
    toBeAudit
  }
  saleRejectStatistic
  getStatusCount(input: $input)
  taskNoticeStatistic
  statusGroupCount(statusGroupCountInput: $statusGroupCountInput) {
    billStatus
    number
    billMainType
  }
  ProductionStockAdjustmentStatus {
    toBeAuditStockIn
    toBeAuditStockOut
  }
  countDeliveryReturn {
    toSubmit
  }
  countSaleReturn(countSaleReturnInput: $countSaleReturnInput) {
    toSubmit
    toInbound
    finished
  }
  abnormalOrderStatistic
  goodsTransferStatusCount {
    unProcessed
  }
  damageOutStatusCount(damageOutStatusCountInput: $damageOutStatusCountInput) {
    toBeSubmit
    inProgress
    toBeOut
    rejected
  }
  countPitayaCostEntryByStatus(input: $countCostEntryByStatusInput) {
    toSubmitNum
    underReviewNum
    underReviewNumBIZ
  }
  breakContractStatus(breakContractStatusInput: $breakContractStatusInput) {
    saleToSubmitCount
    saleToAuditCount
    saleToRejectedCount
    auditToAuditCount
  }
  omsPurchaseStatus {
    count
    status
  }
  # 内部销售: 状态统计
  pitayaCountInternalSaleStatus {
    toBeDelivered
    toBeSubmitted
  }
  countInternalConsignmentStatus {
    unSubmitted
  }
  # 内部采购收货任务
  countPitayaReceiveTask
  countPitayaDomesticReceiveTask
  # 国产货采购
  countDomesticPurchaseStatus(
    countDomesticPurchaseStatusFilter: $countDomesticPurchaseStatusFilter
  ) {
    countDomesticPurchaseStatus {
      count
      status
    }
    countExpandOrderStatus {
      count
      status
    }
  }
  # 采购
  countIndividualPurchaseStatus(
    countPurchaseStatusInput: $countPurchaseStatusInput
  ) {
    count
    status
  }
  # 审核订单:角标统计
  stockOrderBadge {
    toBeInAudited
    toBeOutAudited
  }
  # 销售开单
  saleInvoiceBadge {
    toBeSubmit
  }
  # 销售退货单 v2.20.0
  pitayaReturnBadge {
    toBeInbound
    toBeSubmit
  }
  # 销售计划
  salePlanOrderBadge {
    canceled
    published
    toBePublished
  }
  # 平台退回: 角标/门店管理-退货信息列表页-角标
  pitayaPlatformReturnBadge(input: $platformReturnBadgeInput) {
    toBeInbound
    toBeSubmitted
  }
  # 配送费用单-接入中台: 数量角标
  countDeliveryFee(incomeStatementType: $incomeStatementType)
  # 销售配送单: 获取配送单列表统计数据
  deliveryOrderStats {
    unSubmit
  }
  # 收入单: 数量角标
  countIncomeStatement(incomeStatementTypeInput: $incomeStatementTypeInput) {
    incomeStatementType
    statusNumberList {
      number
      status
    }
  }
  # 采购售后单
  countInternalPurchaseReturn(
    countInternalPurchaseReturnInput: $countInternalPurchaseReturnInput
  ) {
    count
    status
  }
  # 质检任务
  countPitayaSopTask
}

query saleAnotherBadgeCount(
  $deliveryOrderStatusCountDeliveryOrderStatusCountInput: DeliveryOrderStatusCountInput
  $deliveryOrderStatusCountInput: DeliveryOrderStatusCountInput
  $countSaleReturnInput: CountSaleReturnInput
) {
  deliveryOrderStatusCount(
    deliveryOrderStatusCountInput: $deliveryOrderStatusCountDeliveryOrderStatusCountInput
  ) {
    unSubmit
    unOutStock
    unReceipt
  }
  deliveryBillStatusCount(
    deliveryOrderStatusCountInput: $deliveryOrderStatusCountInput
  ) {
    unSubmit
    unAudit
  }
  saleRejectStatistic
  countSaleReturn(countSaleReturnInput: $countSaleReturnInput) {
    toSubmit
    toInbound
    finished
  }
  saleIncomeOrderStatistic {
    orderCount
    auditCount
  }
  countDeliveryReturn {
    toSubmit
  }
}
