# 业务管控: 组织下有客户的渠道列表
query listOrgChannel {
  listOrgChannel {
    label
    value
  }
}

# 业务管控详情页接口
query getOverviewDetail($input: OverviewDetailInput) {
  getOverviewDetail(input: $input) {
    createType
    createTypeName
    customerName
    planStatusName
    createTypeName
    productionTypeNum
    completedNumSum
    expectNumSum
    expectSaleNumSum
    outStockNumSum
    createUserName
    createTime
    customerDistributionName
    planId
    overviewDetail {
      commodityTypeId
      commodityName
      commoditySpecOptionName
      expectSaleNum
      completedNum
      expectNum
      outStockNum
      leaderName
      line
      totalTypeName
    }
  }
}

# 业务管控列表页头部状态数量接口
query overviewStatusOption($input: OverviewStatusInput) {
  overviewStatusOption(input: $input) {
    pendingReviewNum
    processingNum
    completedNum
  }
}

# 业务管控: 业务管控统计概览接口（新）
query listBusinessControl($listBusinessControlInput: ListBusinessControlInput) {
  listBusinessControl(listBusinessControlInput: $listBusinessControlInput) {
    channelDetail {
      completedNum
      expectNum
      finishDeliveryNum
      receivedNum
      returnedNum
      saleOrderType
      waitForDeliveryNum
      saleOrderTypeName
      selfPickedNumSum
      waitSelfPickNumSum
    }
    # channelId
    # channelName
    completedNumSum
    expectNumSum
    expectSalePrice
    finishDeliveryNumSum
    platformNum
    receivedNumSum
    returnedNumSum
    waitForDeliveryNumSum
    labelId
    labelName
    belongOrg {
      orgId
      orgName
    }
    realSalePrice
    selfPickedNumSum
    waitSelfPickNumSum
  }
}

# 业务管控: 业务管控统计分页接口
query pageBusinessOverview($page: Page, $pageBusinessOverviewInput: PageBusinessOverviewInput) {
  pageBusinessOverview(
    page: $page
    pageBusinessOverviewInput: $pageBusinessOverviewInput
  ) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      customerBelongInfo {
        customerId
        customerName
        customerType
      }
      submitUser {
        phoneNum
        userId
        userName
      }
      finishDeliveryNumSum
      receivedNumSum
      returnedNumSum
      saleOrderItems {
        commoditySku {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
        priceType {
          unitId
          unitName
        }
        priceQuantity
      }
      saleOrderStatus
      saleOrderStatusName
      saleOrderType
      saleOrderTypeName
      salePrice
      saleQuantity
      submitTime
      waitForDeliveryNumSum
      selfPickedNumSum
      waitSelfPickNumSum
    }
    totalRecords
  }
}