# 费用单操作（接入费用模板）: 详情查询
query getBill2($input: GetBill2Input!) {
  getBill2(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    billFreightResp {
      billFreightCode
      billType
      totalAmount
    }
    billMainId
    billMainCode
    billMainType
    billPaymentResp {
      billCode
      billNote
      billPaymentFeeItemRespsList {
        amount
        batch {
          batchCode
          batchId
          createTime
          totalQuantity
          unitQuantity
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          sourceBatchCode
          sourceBatchId
        }
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        costUnitPrice
        grossUnitQuantity
        index
        itemId
        priceType {
          unitId
          unitName
        }
        totalQuantity
        unitPrice
        unitQuantity
        applyTotalQuantity
        applyUnitQuantity
        markList
        pricePosition
        purchaseAmountForBuckleDamage
        deductibleAmount
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        customerBelongInfo {
          customerId
          customerName
          customerType
        }
        markDescList
      }
      supplier {
        supplierId
        supplierName
      }
      totalAmount
      manualCode
    }
    billStatus
    billStatusDesc
    billTemplateId
    businessId
    businessInfo {
      domesticCollectiveProcurementReturnsAndLoss {
        domesticCollectiveCode
        supplier {
          supplierId
          supplierName
        }
        belongOrg {
          orgId
          orgName
        }
        businessType
        businessTypeName
        commodityTypeId
        commodityTypeName
        createBy {
          phoneNum
          userId
          userName
        }
        createTime
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        note
        warehouse {
          warehouseId
          warehouseName
        }
        commodities {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          commoditySkuId
        }
      }
      internalConsignmentSaleAndPurchase {
        internalConsignmentCode
        belongOrg {
          orgId
          orgName
        }
        businessType
        businessTypeName
        commodityTypeId
        commodityTypeName
        createBy {
          phoneNum
          userId
          userName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        note
        purchaseDate
        purchaser {
          phoneNum
          userId
          userName
        }
        saleDate
        warehouse {
          warehouseId
          warehouseName
        }
        supplier {
          supplierId
          supplierName
        }
        subType
      }
      otherIn {
        commodityType
        commodityTypeName
        inOrderCode
        inOrderTypeDesc
        supplier {
          supplierId
          supplierName
        }
        wmsMarkList {
          appId
          businessType
          labelContent
          markId
          tenantId
        }
        remark
      }
      selfPurchase {
        businessCode
        commodityType
        commodityTypeName
        purchaseTime
      }
      otherOutInfo {
        supplier {
          supplierId
          supplierName
        }
        wmsMarkList {
          appId
          businessType
          labelContent
          markId
          tenantId
        }
        commodityType
        commodityTypeName
        orderCode
        orderTypeDesc
        remark
      }
      internalPurchaseAndSaleReturn {
        belongOrg {
          orgId
          orgName
        }
        createBy {
          phoneNum
          userId
          userName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        supplier {
          supplierId
          supplierName
        }
        warehouse {
          warehouseId
          warehouseName
        }
        code
        commodityType
        commodityTypeName
        createTime
        exrOrderSubTypeName
        extOrderSubType
        extOrderType
        extOrderTypeName
        note
        waitConfirmFlag
        returnWay
        returnWayDesc
      }
    }
    businessType
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    customerBelongInfo {
      customerId
      customerName
      customerType
    }
    financialRejectionReason
    note
    warehouse {
      address
      belongId
      belongType
      houseNumber
      id
      locationList
      name
      orgId
      remark
      status
      typeId
    }
    billMainTypeName
    billDetailsList {
      billCostData
      billDetailId
      billMainId
      businessItemValue
      costAmount
      costId
      costName
      dictItemId
      note
      ruleCode
      ruleId
      showField
      supplier {
        supplierId
        supplierName
      }
      paymentType
    }
    matchSourceName {
      carNo
      departureDate
      matchDate
      matchSource
      matchSourceName
      runCode
      trailerNo
    }
    billMainCode
    rejectSourceType
    submitUser {
      phoneNum
      userId
      userName
    }
    submitTime
    relationBillDetail {
      billDetailList {
        supplier {
          supplierId
          supplierName
        }
        billCostData
        billDetailId
        billMainId
        businessItemValue
        costAmount
        costId
        costName
        dictItemId
        note
        paymentType
        ruleCode
        ruleId
        showField
      }
      templateId
    }
    sourceBillMainId
    billOperationLogPayload {
      user {
        phoneNum
        userId
        userName
      }
      createTime
      endStatus
      endStatusDesc
      note
      startStatus
      startStatusDesc
    }
    relationBillStatus
    billNote
    fromBIZControl
  }
}

# 费用单操作（接入费用模板）: 列表查询
query pageBill2($input: PageBill2Input!, $page: Page!) {
  pageBill2(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      billFreightResp {
        billFreightCode
        billType
        totalAmount
      }
      billMainId
      billMainType
      billStatus
      billStatusDesc
      billTemplateId
      businessId
      businessInfo {
        domesticCollectiveProcurementReturnsAndLoss {
          domesticCollectiveCode
          supplier {
            supplierId
            supplierName
          }
          belongOrg {
            orgId
            orgName
          }
          businessType
          businessTypeName
          commodityTypeId
          commodityTypeName
          createBy {
            phoneNum
            userId
            userName
          }
          createTime
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          note
          warehouse {
            warehouseId
            warehouseName
          }
          commodities {
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
            commoditySkuId
          }
        }
        internalConsignmentSaleAndPurchase {
          internalConsignmentCode
          belongOrg {
            orgId
            orgName
          }
          businessType
          businessTypeName
          commodityTypeId
          commodityTypeName
          createBy {
            phoneNum
            userId
            userName
          }
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          note
          purchaseDate
          purchaser {
            phoneNum
            userId
            userName
          }
          saleDate
          warehouse {
            warehouseId
            warehouseName
          }
          supplier {
            supplierId
            supplierName
          }
          subType
        }
        selfPurchase {
          businessCode
          commodityType
          commodityTypeName
          purchaseTime
        }
        otherOutInfo {
          supplier {
            supplierId
            supplierName
          }
          wmsMarkList {
            appId
            businessType
            labelContent
            markId
            tenantId
          }
          commodityType
          commodityTypeName
          orderCode
          orderTypeDesc
          remark
        }
        internalPurchaseAndSaleReturn {
          belongOrg {
            orgId
            orgName
          }
          createBy {
            phoneNum
            userId
            userName
          }
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          supplier {
            supplierId
            supplierName
          }
          warehouse {
            warehouseId
            warehouseName
          }
          code
          commodityType
          commodityTypeName
          createTime
          exrOrderSubTypeName
          extOrderSubType
          extOrderType
          extOrderTypeName
          note
          waitConfirmFlag
        }
      }
      businessType
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      customerBelongInfo {
        customerId
        customerName
        customerType
      }
      financialRejectionReason
      note
      warehouse {
        address
        belongId
        belongType
        houseNumber
        id
        locationList
        name
        orgId
        remark
        status
        typeId
      }
      billMainTypeName
      matchSourceName {
        carNo
        departureDate
        matchDate
        matchSource
        matchSourceName
        runCode
        trailerNo
      }
      billMainCode
      rejectSourceType
      submitUser {
        phoneNum
        userId
        userName
      }
      billDetailsList {
        supplier {
          supplierId
          supplierName
        }
        billCostData
        billDetailId
        billMainId
        businessItemValue
        costAmount
        costId
        costName
        dictItemId
        note
        paymentType
        ruleCode
        ruleId
        showField
      }
      sourceBillMainId
      submitTime
      billPaymentResp {
        supplier {
          supplierId
          supplierName
        }
        billCode
        billNote
        billPaymentFeeItemRespsList {
          commoditySku {
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
          }
          priceType {
            unitId
            unitName
          }
          batch {
            batchCode
            batchId
            createTime
            totalQuantity
            unitQuantity
          }
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          amount
          applyTotalQuantity
          applyUnitQuantity
          costUnitPrice
          deductibleAmount
          grossUnitQuantity
          index
          itemId
          markList
          pricePosition
          purchaseAmountForBuckleDamage
          totalQuantity
          unitPrice
          unitQuantity
          customerBelongInfo {
            customerId
            customerName
            customerType
          }
        }
        manualCode
        totalAmount
      }
      relationBillStatus
    }
    totalRecords
  }
}

# 费用单操作（接入费用模板）:提交审核
mutation auditBill2($input: AuditBill2Input!) {
  auditBill2(input: $input)
}

# 费用单操作（接入费用模板）:修改运杂款
mutation updateBill2Freight($input: UpdateBill2FreightInput!) {
  updateBill2Freight(input: $input)
}

# 费用单操作（接入费用模板）:修改货款
mutation updateBill2Payment($input: UpdateBill2PaymentInput!) {
  updateBill2Payment(input: $input)
}

# 采购费用审核: 国产货采购扣损 审核、驳回
mutation changeBill2Status($input: ChangeBill2StatusInput!) {
  changeBill2Status(input: $input)
}

# 费用单操作（接入费用模板）: 状态查询
query bill2StatusGroupCount($input: Bill2StatusGroupCountInput!) {
  bill2StatusGroupCount(input: $input) {
    billMainType
    billStatus
    number
  }
}

# 费用单操作（接入费用模板）:地采采购费用单修改手工单号
mutation updatePitayaBill2SelfPurchaseManualCode($input: UpdateBill2ManualCodeInput!) {
  updatePitayaBill2SelfPurchaseManualCode(input: $input)
}

# 费用单操作（接入费用模板）:地采采购退货费用单修改扣损金额
mutation updatePitayaBill2SelfPurchaseImpairmentAmount($input: UpdateBill2PaymentInput!) {
  updatePitayaBill2SelfPurchaseImpairmentAmount(input: $input)
}

# 费用单操作（接入费用模板）:地采采购费用单修改货款金额
mutation updatePitayaBill2SelfPurchaseAmount($input: UpdateBill2PaymentInput!) {
  updatePitayaBill2SelfPurchaseAmount(input: $input)
}

# 费用单操作（接入费用模板）:地采采购退货费用单修改退货金额
mutation updatePitayaBill2SelfPurchaseReturnAmount($input: UpdateBill2PaymentInput!) {
  updatePitayaBill2SelfPurchaseReturnAmount(input: $input)
}