# 收入单: 数量角标
query countIncomeStatement($creatorPrivileges: Boolean, $incomeStatementTypeInput: IncomeStatementTypeInput) {
  countIncomeStatement(
    creatorPrivileges: $creatorPrivileges
    incomeStatementTypeInput: $incomeStatementTypeInput
  ) {
    incomeStatementType
    statusNumberList {
      number
      status
    }
  }
}

# 收入单: 详情
query detailIncomeStatement($detailIncomeStatementInput: DetailIncomeStatementInput!) {
  detailIncomeStatement(detailIncomeStatementInput: $detailIncomeStatementInput) {
    commodities {
      commoditySku {
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
      }
      fileInfoList {
        accessType
        contentType
        createTime
        fileUrl
        id
        name
        size
        tags
        updateTime
      }
      billMainId
      commodityBatchCodeList {
        batchCode
        batchId
        index
        itemId
        salesAmount
        salesQuantityAndPrice {
          priceType {
            unitId
            unitName
          }
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          price
          totalQuantity
          unitQuantity
        }
      }
      commoditySkuAmount
      commodityType
      commodityTypeDesc
      saleOrderId
      salesAllQuantityAndPrice {
        priceType {
          unitId
          unitName
        }
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        price
        totalQuantity
        unitQuantity
      }
      markDescList
      markList
    }
    incomeStatementMainInfo {
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
      }
      billMainId
      createTime
      incomeStatementOrderCode
      incomeStatementStatus
      incomeStatementStatusDesc
      incomeStatementType
      incomeStatementTypeDesc
      remark
      note
      saleOrderInfo {
        code
        deliveryType
        deliveryTypeDesc
        id
        prePayType
        prePayTypeDesc
        salesDate
        warehouseId
        note
      }
      templateId
      note
    }
    incomeStatementOperationLogPayload {
      user {
        phoneNum
        userId
        userName
      }
      createTime
      endStatus
      endStatusDesc
      note
      startStatus
      startStatusDesc
    }
  }
}

# 收入单: 分页列表
query pageIncomeStatement($page: Page!, $pageIncomeStatementInput: PageIncomeStatementInput!) {
  pageIncomeStatement(
    page: $page
    pageIncomeStatementInput: $pageIncomeStatementInput
  ) {
    pageCurrent
    pageSize
    records {
      commoditiesByGroup {
        commoditySku {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
        fileInfoList {
          accessType
          contentType
          createTime
          fileUrl
          id
          name
          size
          tags
          updateTime
        }
        billMainId
        commodityBatchCodeList {
          batchCode
          batchId
          index
          itemId
          salesAmount
          salesQuantityAndPrice {
            priceType {
              unitId
              unitName
            }
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
            price
            totalQuantity
            unitQuantity
          }
        }
        commoditySkuAmount
        commodityType
        commodityTypeDesc
        saleOrderId
        salesAllQuantityAndPrice {
          priceType {
            unitId
            unitName
          }
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          price
          totalQuantity
          unitQuantity
        }
      }
      incomeStatementMainInfo {
        belongOrg {
          orgId
          orgName
        }
        createBy {
          phoneNum
          userId
          userName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
        }
        billMainId
        createTime
        incomeStatementOrderCode
        incomeStatementStatus
        incomeStatementStatusDesc
        incomeStatementType
        incomeStatementTypeDesc
        remark
        note
        saleOrderInfo {
          code
          deliveryType
          deliveryTypeDesc
          id
          prePayType
          prePayTypeDesc
          salesDate
          warehouseId
          note
        }
        templateId
      }
    }
    totalRecords
  }
}

# 收入单: 业务审核
mutation reviewIncomeStatementBySalesman($changBill2StatusInput: ChangeBill2StatusInput!) {
  reviewIncomeStatementBySalesman(changBill2StatusInput: $changBill2StatusInput)
}

# 收入单: 提交审核
mutation submitIncomeStatement($submitBillInput: SubmitBillInput!) {
  submitIncomeStatement(submitBillInput: $submitBillInput)
}

# 收入单: 修改销售金额
mutation updateIncomeStatement($updateIncomeStatementInput: UpdateIncomeStatementInput!) {
  updateIncomeStatement(updateIncomeStatementInput: $updateIncomeStatementInput)
}