# 生产计划列表
query pageProductionPlan($page: Page, $planQueryInput: PlanQueryInput) {
  pageProductionPlan(page: $page, planQueryInput: $planQueryInput) {
    records {
      planId
      planCode
      planStatus
      planStatusName
      outOrderId
      categorySum
      customerId
      customerName
      customerDistributionId
      customerDistributionName
      planDate
      planStartTime
      planEndTime
      planDescription
      createTime
      createTypeName
      expectNumSum
      completedNumSum
      saleChangeNotice
      saleCancelCount
      taskPauses
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customerType
      org {
        orgId
        orgName
      }
      warehouse {
        warehouseId
        warehouseName
      }
      commodityType
      createType
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 新增生产计划
mutation doInsertPlan($planInfoInput: PlanInfoInput) {
  doInsertPlan(planInfoInput: $planInfoInput)
}

# 暂停或继续任务
mutation pauseOrContinueTask(
  $pauseOrContinueTaskInput: PauseOrContinueTaskInput
) {
  pauseOrContinueTask(pauseOrContinueTaskInput: $pauseOrContinueTaskInput)
}

# 重启计划
mutation restartPlan($planId: ID) {
  restartPlan(planId: $planId)
}

# 商品库存查询
query listCommodityStock($commoditySkuStockInput: CommoditySkuStockInput) {
  listCommodityStock(commoditySkuStockInput: $commoditySkuStockInput) {
    commoditySku {
      commoditySkuId
      commoditySkuName
      commodityId
      commodityName
      commoditySpecOptionId
      commoditySpecOptionName
      conversion
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
    }
    unitQuantity
    totalQuantity
  }
}

# 生产计划：生产计划详情
query getProductionPlanDetail($planId: ID) {
  getProductionPlanDetail(planId: $planId) {
    planId
    planCode
    outOrderId
    planStatus
    planStatusName
    customerType
    customerId
    customerName
    customerDistributionId
    customerDistributionName
    planDate
    planStartTime
    planEndTime
    planDescription
    planLogDescription
    createType
    createTypeName
    commodityType
    commodityTypeName
    createTime
    task {
      taskId
      leaderId
      leaderName
      taskStatus
      taskStatusName
      taskCode
      line
      numberPlan
      commodities {
        taskItemId
        commodityId
        commodityName
        commodityBomId
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        expectNum
        completedNum
        unitQuantity
        unitType
        unitTypeName
        totalType
        totalTypeName
        planChangeNotice
        saleChangePayload {
          changeId
          outOrderId
          outOrderItemId
          commoditySkuId
          planId
          taskId
          saleChangeQuantity
          planChangeQuantity
          changeType
          changeRemark
          status
          createTime
          createBy
          updateTime
          updateBy
        }
        specificationLabel
        packageRequireInfos {
          commodityId
          requestText
        }
        packageLabel
        quantityLabel
        planQuantity
        stockQuantity
        outOrderItemId
        commodityStatus
        actualPickingQuantity
      }
    }
    belongOrg {
      orgId
      orgName
    }
    createBy {
      phoneNum
      userId
      userName
    }
    warehouse {
      warehouseId
      warehouseName
    }
  }
}

# 任务增减记录
query addOrDeleteRecords($addOrDeleteRecordsInput: AddOrDeleteRecordsInput) {
  addOrDeleteRecords(addOrDeleteRecordsInput: $addOrDeleteRecordsInput) {
    taskItemChangeId
    planId
    taskId
    taskItemId
    beforeQuantity
    afterQuantity
    changeQuantity
    changeType
    changeRemark
    createTime
    createBy
    createByName
  }
}

# 忽略增减提示
mutation ignoreTaskSaleChange(
  $ignoreTaskSaleChangeInput: IgnoreTaskSaleChangeInput
) {
  ignoreTaskSaleChange(ignoreTaskSaleChangeInput: $ignoreTaskSaleChangeInput)
}

# 详情页操作日志
query getProductionPlanLogs($planId: ID) {
  productionPlanLogs(planId: $planId) {
    planLogId
    planId
    planLogType
    planLogTypeText
    planLogDescription
    createTime
    createBy
    createUserName
  }
}

# 修改计划
mutation doUpdatePlanInfo(
  $updateProductionPlanInput: UpdateProductionPlanInput
) {
  doUpdatePlanInfo(updateProductionPlanInput: $updateProductionPlanInput)
}

# 修改计划基本信息
mutation doUpdatePlanBaseInfo($planBaseInfoInput: PlanBaseInfoInput) {
  doUpdatePlanBaseInfo(planBaseInfoInput: $planBaseInfoInput)
}

# 修改计划任务信息
mutation doUpdatePlanTaskInfo($planTaskInfoInput: PlanTaskInfoInput) {
  doUpdatePlanTaskInfo(planTaskInfoInput: $planTaskInfoInput)
}

# 删除计划任务信息
mutation doDeletePlanTask($taskId: ID) {
  doDeletePlanTask(taskId: $taskId)
}

# 取消发布
mutation requestDoCancelPlanStatus($cancelPlanInput: CancelPlanInput) {
  doCancelPlanStatus(cancelPlanInput: $cancelPlanInput)
}

# 发布计划
mutation doPublishPlan($planId: ID) {
  doPublishPlan(planId: $planId)
}

# 计划数量
query productionPlanStatusOption($planDate: Long) {
  productionPlanStatusOption(planDate: $planDate) {
    pendingReviewNum
    processingNum
    completedNum
  }
}

# 新增生产计划任务
mutation doInsertPlanTask($taskInput: TaskInput) {
  doInsertPlanTask(taskInput: $taskInput)
}

query planCommodites($listPlanCommodityInput: ListPlanCommoditySkuInput) {
  planCommodites(listPlanCommodityInput: $listPlanCommodityInput) {
    commodityPayload {
      commodityId
      commodityName
      commodityTypeId
      commodityTypeName
      commodityCategoryId
      commodityCategoryName
      commodityVarietyId
      commodityVarietyName
      commodityPlaceOriginId
      commodityPlaceOriginName
    }
    commoditySkuId
    commodityId
    status
    unitQuantity
    unitType
    unitTypeName
    totalQuantity
    totalType
    totalTypeName
    property
    bomId
    createTime
    createBy
    updateTime
    updateBy
    Deleted
    commoditySpecOptionId
    skuTextDescription
  }
}

# 完成计划
mutation completePlan($planId: ID) {
  completePlan(planId: $planId)
}

# 取消计划
mutation cancelPlan($planId: ID) {
  cancelPlan(planId: $planId)
}

# 取消任务
mutation cancelTask($cancelTaskInput: CancelTaskInput) {
  cancelTask(cancelTaskInput: $cancelTaskInput) {
    result
  }
}

# 拒绝申请
mutation requestRejection($requestRejectionInput: RequestRejectionInput) {
  requestRejection(requestRejectionInput: $requestRejectionInput) {
    result
  }
}

# 取消生产
mutation confirmCancelProduction(
  $confirmCancelProductionInput: ConfirmCancelProductionInput
) {
  confirmCancelProduction(
    confirmCancelProductionInput: $confirmCancelProductionInput
  ) {
    result
  }
}
