# 联营销售: 取消联营销售订单
mutation cancelJointVentureSale(
  $cancelJointVentureSaleInput: CancelJointVentureSaleInput
) {
  cancelJointVentureSale(
    cancelJointVentureSaleInput: $cancelJointVentureSaleInput
  )
}

# 联营销售: 提交联营销售订单
mutation submitJointVentureSale(
  $submitJointVentureSaleInput: SubmitJointVentureSaleInput
) {
  submitJointVentureSale(
    submitJointVentureSaleInput: $submitJointVentureSaleInput
  )
}

# 联营销售: 修改联营销售订单
mutation updateJointVentureSale($jointVentureSaleInput: JointVentureSaleInput) {
  updateJointVentureSale(jointVentureSaleInput: $jointVentureSaleInput)
}

# 联营销售: 创建联营销售订单
mutation createJointVentureSale($jointVentureSaleInput: JointVentureSaleInput) {
  createJointVentureSale(jointVentureSaleInput: $jointVentureSaleInput)
}

# 联营销售: 查询存在库存的品类
query listHasStockCategory(
  $listHasStockCategoryInput: ListHasStockCategoryInput
) {
  listHasStockCategory(listHasStockCategoryInput: $listHasStockCategoryInput) {
    categoryId
    categoryName
  }
}

# 联营销售: 查询存在库存的spu
query listHasStockSpu($listHasStockSpuInput: ListHasStockSpuInput) {
  listHasStockSpu(listHasStockSpuInput: $listHasStockSpuInput) {
    commodityId
    commodityName
  }
}

# 联营销售: 查询存在库存的sku
query listHasStockSku($listHasStockSkuInput: ListHasStockSkuInput) {
  listHasStockSku(listHasStockSkuInput: $listHasStockSkuInput) {
    sku {
      commoditySkuId
      commoditySkuName
      commodityId
      commodityName
      commoditySpecOptionId
      commoditySpecOptionName
      conversion
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
      categoryId
      categoryName
    }
    summaryTotalQuantity
    totalType {
      unitId
      unitName
    }
    summaryUnitQuantity
    unitType {
      unitId
      unitName
    }
  }
}
