# 原件销售:列表页及查询
query pageOriginalSale(
  $page: Page
  $pageOriginalSaleInput: PageOriginalSaleInput
) {
  pageOriginalSale(page: $page, pageOriginalSaleInput: $pageOriginalSaleInput) {
    records {
      outOrderStatus
      outOrderStatusDesc
      latestDescription
      outOrderId
      outOrderCode
      outOrderType
      outOrderTypeDesc
      commodityType
      commodityTypeDesc
      warehouse {
        warehouseId
        warehouseName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      createUser {
        userId
        userName
        phoneNum
      }
      createTime
      payMethod
      payMethodDesc
      remark
      saleTotalPrice
      commodityList {
        outOrderItemId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
          categoryId
          categoryName
        }
        batchId
        batchCode
        salePrice
        salePriceType {
          unitId
          unitName
        }
        totalQuantity
        totalType {
          unitId
          unitName
        }
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleTotalPrice
        actualQuantity {
          actualSalePrice
          actualSaleTotalPrice
          actualTotalQuantity
          actualUnitQuantity
          outOrderItemId
        }
        outOrderId
        stockQuantity {
          totalQuantity
          unitQuantity
        }
      }
      belongOrg {
        orgId
        orgName
      }
      deliveryRequired
      commodityTypeId
      outOrderSaleTime
      saleIncomeOrder {
        belongOrg {
          orgId
          orgName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        user {
          phoneNum
          userId
          userName
        }
        warehouse {
          warehouseId
          warehouseName
        }
        commoditiesList {
          commoditySku {
            availableSkuQuantity {
              businessUnit {
                unitId
                unitName
              }
              unit {
                unitId
                unitName
              }
              conversion
            }
            baseUnit {
              unitId
              unitName
            }
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
          }
          batchCode
          batchId
          commodityBatchInfoList {
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
            batchCode
            batchId
            goodsTotalQuantity
            goodsUnitQuantity
            incomeItemId
            outOrderItemId
            salePrice
            totalQuantity
            totalSalePrice
            unitQuantity
          }
          commodityName
          goodsTotalQuantity
          goodsUnitQuantity
          incomeId
          incomeItemId
          outOrderItemId
          photosList
          quantity
          remark
          saleMoney
          salePrice
          totalSalePrice
          unit {
            unitId
            unitName
          }
        }
        commodityTypeName
        createTime
        functionalField {
          saleTotalCost
          saleTotalPrice
        }
        incomeCode
        incomeId
        incomeStatus
        incomeStatusName
        logs {
          user {
            phoneNum
            userId
            userName
          }
          createTime
          incomeId
          incomeLogId
          remark
          type
          typeText
        }
        originalSaleCommodityPayload {
          commoditySku {
            availableSkuQuantity {
              businessUnit {
                unitId
                unitName
              }
              unit {
                unitId
                unitName
              }
              conversion
            }
            baseUnit {
              unitId
              unitName
            }
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
          }
          salePriceType {
            unitId
            unitName
          }
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          actualQuantity {
            actualSalePrice
            actualSaleTotalPrice
            actualTotalQuantity
            actualUnitQuantity
            outOrderItemId
          }
          batchCode
          batchId
          outOrderId
          outOrderItemId
          salePrice
          saleTotalPrice
          stockQuantity {
            totalQuantity
            unitQuantity
          }
          totalQuantity
          unitQuantity
        }
        payMode
        rejectReason
        remark
        saleCostOrderId
        saleCostOrderItems {
          commodity {
            availableSkuQuantity {
              businessUnit {
                unitId
                unitName
              }
              unit {
                unitId
                unitName
              }
              conversion
            }
            baseUnit {
              unitId
              unitName
            }
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
          }
          materialFee
          outOrderItemId
          packagingFee
          saleCostOrderId
          saleCostOrderItemId
        }
        saleTime
        sourceId
        sourceType
        sourceTypeName
        totalAmount
      }
      undoingDeliveryFlag
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 原件销售:列表页状态统计
query originalSaleStatus($originalSaleStatusInput: OriginalSaleStatusInput) {
  originalSaleStatus(originalSaleStatusInput: $originalSaleStatusInput) {
    toSubmit
    toOutbound
    rejected
  }
}

# 新增原件销售
mutation createOriginalSale($originalCreateInput: OriginalCreateInput) {
  createOriginalSale(originalCreateInput: $originalCreateInput) {
    outOrderId
  }
}

# 原件销售:选择销售商品-品类list
query listOriginalSaleCommodityCategory(
  $listOriginalSaleCommodityCategoryInput: ListOriginalSaleCommodityCategoryInput
) {
  listOriginalSaleCommodityCategory(
    listOriginalSaleCommodityCategoryInput: $listOriginalSaleCommodityCategoryInput
  ) {
    categoryId
    categoryName
  }
}

# 原件销售:选择销售商品-商品名称spu list
query listOriginalSaleCommoditySPU(
  $listOriginalSaleCommoditySPUInput: ListOriginalSaleCommoditySPUInput
) {
  listOriginalSaleCommoditySPU(
    listOriginalSaleCommoditySPUInput: $listOriginalSaleCommoditySPUInput
  ) {
    commodityId
    commodityName
  }
}

# 原件销售:选择销售商品-批次list
query listOriginalSaleCommodityBatch(
  $listOriginalSaleCommodityBatchInput: ListOriginalSaleCommodityBatchInput
) {
  listOriginalSaleCommodityBatch(
    listOriginalSaleCommodityBatchInput: $listOriginalSaleCommodityBatchInput
  ) {
    commodityType
    commodityTypeDesc
    categoryId
    categoryName
    commodityId
    commodityName
    countBatch
    commoditySku {
      commoditySkuId
      commoditySkuName
      commodityId
      commodityName
      commoditySpecOptionId
      commoditySpecOptionName
      availableSkuQuantity {
        businessUnit {
          unitId
          unitName
        }
        unit {
          unitId
          unitName
        }
        conversion
      }
      baseUnit {
        unitId
        unitName
      }
      categoryId
      categoryName
    }
    batchId
    batchCode
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    inStockTime
    unit {
      unitId
      unitName
    }
    quantity
    quantityItem {
      unit {
        unitId
        unitName
      }
      quantity
    }
  }
}

# 原件销售:原件销售详情
query originalSaleOrder($originalSaleOrderInput: OriginalSaleOrderInput) {
  originalSaleOrder(originalSaleOrderInput: $originalSaleOrderInput) {
    outOrderStatus
    outOrderStatusDesc
    latestDescription
    outOrderId
    outOrderCode
    outOrderType
    outOrderTypeDesc
    commodityType
    commodityTypeId
    commodityTypeDesc
    warehouse {
      warehouseId
      warehouseName
    }
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    createUser {
      userId
      userName
      phoneNum
    }
    createTime
    payMethod
    payMethodDesc
    remark
    saleTotalPrice
    commodityList {
      outOrderItemId
      commoditySku {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
        categoryId
        categoryName
      }
      batchId
      batchCode
      salePrice
      salePriceType {
        unitId
        unitName
      }
      totalQuantity
      totalType {
        unitId
        unitName
      }
      unitQuantity
      unitType {
        unitId
        unitName
      }
      saleTotalPrice
      stockQuantity {
        unitQuantity
        totalQuantity
      }
      actualQuantity {
        actualTotalQuantity
        actualUnitQuantity
        actualSalePrice
        actualSaleTotalPrice
        outOrderItemId
      }
      outOrderId
    }
    saleIncomeOrder {
      incomeId
      incomeStatus
      incomeStatusName
      incomeCode
      sourceId
      sourceType
      sourceTypeName
      remark
      createTime
      saleCostOrderId
      totalAmount
      commodityTypeName
      payMode
      saleTime
      belongOrg {
        orgId
        orgName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      user {
        phoneNum
        userId
        userName
      }
      warehouse {
        warehouseId
        warehouseName
      }
      commoditiesList {
        commoditySku {
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
        }
        batchCode
        batchId
        commodityBatchInfoList {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          batchCode
          batchId
          goodsTotalQuantity
          goodsUnitQuantity
          incomeItemId
          outOrderItemId
          salePrice
          totalQuantity
          totalSalePrice
          unitQuantity
        }
        commodityName
        goodsTotalQuantity
        goodsUnitQuantity
        incomeId
        incomeItemId
        outOrderItemId
        photosList
        quantity
        remark
        saleMoney
        salePrice
        totalSalePrice
        unit {
          unitId
          unitName
        }
      }
      functionalField {
        saleTotalCost
        saleTotalPrice
      }
      logs {
        user {
          phoneNum
          userId
          userName
        }
        createTime
        incomeId
        incomeLogId
        remark
        type
        typeText
      }
      originalSaleCommodityPayload {
        commoditySku {
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
        }
        salePriceType {
          unitId
          unitName
        }
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        actualQuantity {
          actualSalePrice
          actualSaleTotalPrice
          actualTotalQuantity
          actualUnitQuantity
          outOrderItemId
        }
        batchCode
        batchId
        outOrderId
        outOrderItemId
        salePrice
        saleTotalPrice
        stockQuantity {
          totalQuantity
          unitQuantity
        }
        totalQuantity
        unitQuantity
      }
      rejectReason
      saleCostOrderItems {
        commodity {
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
        }
        materialFee
        outOrderItemId
        packagingFee
        saleCostOrderId
        saleCostOrderItemId
      }
    }
    belongOrg {
      orgId
      orgName
    }
    deliveryRequired
    undoingDeliveryFlag
    outOrderSaleTime
  }
}

# 原件销售:提交原件销售
mutation submitOriginalSale($originalSubmitInput: OriginalSubmitInput) {
  submitOriginalSale(originalSubmitInput: $originalSubmitInput)
}

# 原件销售:取消原件销售
mutation cancelOriginalSale($originalCancelInput: OriginalCancelInput) {
  cancelOriginalSale(originalCancelInput: $originalCancelInput)
}

# 修改原件销售
mutation updateOriginalSale($originalUpdateInput: OriginalUpdateInput) {
  updateOriginalSale(originalUpdateInput: $originalUpdateInput)
}

# 原件销售:修改金额
mutation updateOriginalSaleIncomeAmount(
  $updateSaleIncomeAmountInput: UpdateOriginalSaleAmountInput
) {
  updateOriginalSaleIncomeAmount(
    updateSaleIncomeAmountInput: $updateSaleIncomeAmountInput
  )
}

# 原件销售:选择销售商品-查询
query listSPUByCommodityName(
  $listSPUByCommodityNameInput: ListSPUByCommodityNameInput
) {
  listSPUByCommodityName(
    listSPUByCommodityNameInput: $listSPUByCommodityNameInput
  ) {
    commodityId
    commodityName
  }
}

# 原件销售:撤销配送
mutation undoDelivery($originalUndoDeliveryInput: OriginalUndoDeliveryInput) {
  undoDelivery(originalUndoDeliveryInput: $originalUndoDeliveryInput)
}

# 原件销售:修改报价信息
mutation updateOriginalSalePriceInfo(
  $updateOriginalSalePriceInfoInput: UpdateOriginalSalePriceInfoInput
) {
  updateOriginalSalePriceInfo(
    updateOriginalSalePriceInfoInput: $updateOriginalSalePriceInfoInput
  )
}
