# 销售计划:列表
query pageSalePlanOrder(
  $page: Page
  $pageSalePlanOrderInput: PageSalePlanOrderInput
) {
  pageSalePlanOrder(
    page: $page
    pageSalePlanOrderInput: $pageSalePlanOrderInput
  ) {
    pageCurrent
    pageSize
    records {
      belongType
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      org {
        orgId
        orgName
      }
      code
      createTime
      id
      remark
      salePlanOrderItems {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
        }
        warehouse {
          warehouseId
          warehouseName
        }
        itemId
        price
        salePlanOrderId
        totalPrice
        commodityTypeId
        commodityTypeName
        unit {
          unitId
          unitName
        }
        applyMark
        belongCustomerId
        belongCustomerType
        commodityId
        index
        packageRequireInfos {
          commodityId
          requestText
        }
        quantity
        quantityLabel
        specificationLabel
        summaryStockItems {
          unit {
            unitId
            unitName
          }
          quantity
        }
      }
      salePlanOrderStatus
      saleTime
      salePlanOrderStatusName
      distributionId
      distributionName
      customerId
      listBusinessCommonLogs {
        createBy {
          phoneNum
          userId
          userName
        }
        businessId
        businessType
        businessTypeName
        createTime
        id
        logType
        logTypeName
        nextStatus
        preStatus
        remark
      }
    }
    totalRecords
  }
}

# 销售计划:状态统计
query salePlanOrderBadge {
  salePlanOrderBadge {
    canceled
    published
    toBePublished
  }
}

# 销售计划:详情
query salePlanOrderDetail($salePlanOrderDetailInput: SalePlanOrderDetailInput) {
  salePlanOrderDetail(salePlanOrderDetailInput: $salePlanOrderDetailInput) {
    belongType
    belongOrg {
      orgId
      orgName
    }
    createBy {
      phoneNum
      userId
      userName
    }
    org {
      orgId
      orgName
    }
    code
    createTime
    id
    remark
    salePlanOrderItems {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      warehouse {
        warehouseId
        warehouseName
      }
      itemId
      price
      salePlanOrderId
      totalPrice
      commodityTypeId
      commodityTypeName
      index
      packageRequireInfos {
        commodityId
        requestText
      }
      quantityLabel
      specificationLabel
      belongCustomerId
      belongCustomerType
      applyMark
      commodityId
      unit {
        unitId
        unitName
      }
      quantity
      summaryStockItems {
        unit {
          unitId
          unitName
        }
        quantity
      }
    }
    salePlanOrderStatus
    saleTime
    salePlanOrderStatusName
    distributionId
    distributionName
    customerId
    listBusinessCommonLogs {
      createBy {
        phoneNum
        userId
        userName
      }
      businessId
      businessType
      businessTypeName
      createTime
      id
      logType
      logTypeName
      nextStatus
      preStatus
      remark
    }
  }
}

# 销售计划:新增
mutation createSalePlanOrder(
  $createSalePlanOrderInput: CreateSalePlanOrderInput
) {
  createSalePlanOrder(createSalePlanOrderInput: $createSalePlanOrderInput)
}

# 销售计划:修改
mutation updateSalePlanOrder(
  $updateSalePlanOrderInput: UpdateSalePlanOrderInput
) {
  updateSalePlanOrder(updateSalePlanOrderInput: $updateSalePlanOrderInput)
}

# 销售计划:平台报价修改
mutation updateSalePlanOrderPrice(
  $updateSalePlanOrderPriceInput: UpdateSalePlanOrderPriceInut
) {
  updateSalePlanOrderPrice(
    updateSalePlanOrderPriceInput: $updateSalePlanOrderPriceInput
  )
}

# 销售计划:预估销量修改
mutation updateSalePlanOrderQuantity(
  $updateSalePlanOrderQuantityInput: UpdateSalePlanOrderQuantityInput
) {
  updateSalePlanOrderQuantity(
    updateSalePlanOrderQuantityInput: $updateSalePlanOrderQuantityInput
  )
}

# 销售计划:状态变更(取消、撤回)
mutation updateSalePlanOrderStat(
  $updateSalePlanOrderStatInput: UpdateSalePlanOrderStatInput
) {
  updateSalePlanOrderStat(
    updateSalePlanOrderStatInput: $updateSalePlanOrderStatInput
  )
}

# 销售计划:库存商品汇总列表
query listSalePlanOrderSummaryStock(
  $listSalePlanOrderSummaryStockInput: ListSalePlanOrderSummaryStockInput
) {
  listSalePlanOrderSummaryStock(
    listSalePlanOrderSummaryStockInput: $listSalePlanOrderSummaryStockInput
  ) {
    commoditySku {
      categoryId
      categoryName
      commodityId
      commodityName
      commoditySkuId
      commoditySkuName
      commoditySpecOptionId
      commoditySpecOptionName
      availableSkuQuantity {
        businessUnit {
          unitId
          unitName
        }
        unit {
          unitId
          unitName
        }
        conversion
      }
      baseUnit {
        unitId
        unitName
      }
    }
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    commodityTypeId
    commodityTypeName
    warehouse {
      warehouseId
      warehouseName
    }
    index
    summaryStockItems {
      unit {
        unitId
        unitName
      }
      quantity
    }
  }
}

# 销售计划:选择销售商品-商品名称spu list（筛选有库存）
query listSalePlanCommoditySPU(
  $listSalePlanCommoditySPUInput: ListSalePlanCommoditySPUInput
) {
  listSalePlanCommoditySPU(
    listSalePlanCommoditySPUInput: $listSalePlanCommoditySPUInput
  ) {
    categoryId
    commodityName
    commodityTypeId
    commodityId
  }
}

# 销售计划:选择销售商品-品类list（筛选有库存）
query listSalePlanCommodityCategory(
  $listSalePlanCommodityCategoryInput: ListSalePlanCommodityCategoryInput
) {
  listSalePlanCommodityCategory(
    listSalePlanCommodityCategoryInput: $listSalePlanCommodityCategoryInput
  ) {
    categoryId
    categoryName
  }
}

# 销售计划: 再来一单
mutation oneMoreSalePlanOrder(
  $oneMoreSalePlanOrderInput: OneMoreSalePlanOrderInput!
) {
  oneMoreSalePlanOrder(oneMoreSalePlanOrderInput: $oneMoreSalePlanOrderInput) {
    outOfStockItems {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      commodityType {
        commodityTypeId
        commodityTypeName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      warehouse {
        warehouseId
        warehouseName
      }
      applyMark
    }
    saleOrderId
  }
}

# 销售计划:赠送数量修改
mutation updateSalePlanOrderGiveQuantity(
  $updateSalePlanOrderGiftQuantityInput: UpdateSalePlanOrderGiftQuantityInput
) {
  updateSalePlanOrderGiveQuantity(
    updateSalePlanOrderGiftQuantityInput: $updateSalePlanOrderGiftQuantityInput
  )
}
