# 销售退货: 列表页
query pitayaPageReturn($input: PitayaPageReturnInput!, $page: Page) {
  pitayaPageReturn(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongId
      belongName
      belongOrgId
      belongOrgName
      belongType
      saleReturnWay
      saleReturnWayName
      commodities {
        commodityId
        commodityName
        commoditySkuName
        commodityTypeId
        optionName
        price
        priceType
        returnId
        skuId
        totalName
        totalQuantity
        totalType
        unitName
        unitQuantity
        unitType
      }
      createBy
      createByName
      createTime
      remark
      returnStatus
      returnStatusDesc
      returnTime
      returnType
      returnTypeDesc
      saleOrderCode
      saleOrderId
      returnCode
      returnId
    }
    totalRecords
  }
}

# 销售退货: 角标
query pitayaReturnBadge {
  pitayaReturnBadge {
    toBeInbound
    toBeSubmit
  }
}

# 销售开单销售退货: 新增
mutation createSaleInvoiceReturn(
  $input: CreateOrUpdateSaleInvoiceReturnInput!
) {
  createSaleInvoiceReturn(input: $input)
}

# 销售开单销售退货: 修改
mutation updateSaleInvoiceReturn(
  $input: CreateOrUpdateSaleInvoiceReturnInput!
) {
  updateSaleInvoiceReturn(input: $input)
}
