# default

# 废旧品销售分页列表接口
query pageWasteSaleOrder(
  $pageWasteSaleOrderInput: PageWasteSaleOrderInput
  $page: Page
) {
  pageWasteSaleOrder(
    pageWasteSaleOrderInput: $pageWasteSaleOrderInput
    page: $page
  ) {
    records {
      saleOrderId
      saleOrderCode
      saleOrderStatus
      org {
        orgId
        orgName
      }
      warehouse {
        warehouseId
        warehouseName
      }
      payMode
      remark
      user {
        userId
        userName
        phoneNum
      }
      createTime
      wasteSaleOrderItemList {
        saleOrderItemId
        commodityName
        unitQuantity
        unit {
          unitId
          unitName
        }
        saleAmount
        totalSaleAmount
        photos
      }
      wasteSaleOrderLogList {
        saleOrderLogId
        saleOrderId
        type
        typeText
        remark
        user {
          userId
          userName
          phoneNum
        }
        createTime
      }
      reason
      belongOrg {
        orgId
        orgName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 废旧品销售详情接口
query wasteSaleOrder($getWasteSaleOrderInput: GetWasteSaleOrderInput) {
  wasteSaleOrder(getWasteSaleOrderInput: $getWasteSaleOrderInput) {
    saleOrderId
    saleOrderCode
    saleOrderStatus
    org {
      orgId
      orgName
    }
    warehouse {
      warehouseId
      warehouseName
    }
    payMode
    remark
    user {
      userId
      userName
      phoneNum
    }
    createTime
    wasteSaleOrderItemList {
      saleOrderItemId
      commodityName
      unitQuantity
      unit {
        unitId
        unitName
      }
      saleAmount
      totalSaleAmount
      photos
    }
    wasteSaleOrderLogList {
      saleOrderLogId
      saleOrderId
      type
      typeText
      remark
      user {
        userId
        userName
        phoneNum
      }
      createTime
    }
    reason
    saleIncome {
      incomeId
      incomeStatus
      incomeStatusName
      incomeCode
      sourceId
      sourceType
      sourceTypeName
      warehouse {
        warehouseId
        warehouseName
      }
      remark
      rejectReason
      user {
        userId
        userName
        phoneNum
      }
      customer {
        customerId
        customerName
        customerType
      }
      createTime
      commoditiesList {
        incomeItemId
        incomeId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        commodityName
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleMoney
        photosList
        outOrderItemId
        salePrice
        remark
        totalQuantity
        totalType {
          unitId
          unitName
        }
        batchId
        batchCode
        totalSalePrice
        priceType {
          unitId
          unitName
        }
      }
      saleCostOrderItems {
        saleCostOrderItemId
        saleCostOrderId
        outOrderItemId
        commodity {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        packagingFee
        materialFee
      }
      logs {
        incomeLogId
        incomeId
        type
        typeText
        remark
        createTime
        user {
          userId
          userName
          phoneNum
        }
      }
      saleCostOrderId
      functionalField {
        saleTotalPrice

        saleTotalCost
      }
      totalAmount
      commodityTypeName
      payMode
      belongOrg {
        orgId
        orgName
      }
    }
    belongOrg {
      orgId
      orgName
    }
  }
}
# 废旧品销售状态数量统计
query wasteSaleOrderStats($wasteSaleOrderStatsInput: WasteSaleOrderStatsInput) {
  wasteSaleOrderStats(wasteSaleOrderStatsInput: $wasteSaleOrderStatsInput) {
    finished
    reject
    canceled
  }
}

# 创建废旧品销售
mutation createWasteSaleOrder(
  $createWasteSaleOrderInput: CreateWasteSaleOrderInput
) {
  createWasteSaleOrder(createWasteSaleOrderInput: $createWasteSaleOrderInput)
}

# 废旧品销售修改金额
mutation updateWasteSaleOrderPrice(
  $updateWasteSaleOrderPriceInput: UpdateWasteSaleOrderPriceInput
) {
  updateWasteSaleOrderPrice(
    updateWasteSaleOrderPriceInput: $updateWasteSaleOrderPriceInput
  )
}

# 废旧品销售取消订单
mutation cancelWasteSaleOrder(
  $cancelWasteSaleOrderInput: CancelWasteSaleOrderInput
) {
  cancelWasteSaleOrder(cancelWasteSaleOrderInput: $cancelWasteSaleOrderInput)
}

# 废旧品销售提交(即完成当前废旧品销售单)
mutation submitWasteSaleOrder(
  $submitWasteSaleOrderInput: SubmitWasteSaleOrderInput
) {
  submitWasteSaleOrder(submitWasteSaleOrderInput: $submitWasteSaleOrderInput)
}

# 商品类型单位下拉列表
query listCommodityUnitOption(
  $listCommodityUnitOptionInput: ListCommodityUnitOptionInput
) {
  listCommodityUnitOption(
    listCommodityUnitOptionInput: $listCommodityUnitOptionInput
  ) {
    label
    value
  }
}
