# 平台退回: 选择商品-商品spu&sku以及搜索/门店管理-平台开单选商品-spu&sku
query listVirtualStock($input: ListVirtualStockInput!) {
  listVirtualStock(input: $input) {
    commodityId
    commodityName
    skuStockInfo {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      commodityType
      commodityTypeName
      stockQuantity {
        unit {
          unitId
          unitName
        }
        quantity
      }
      mark
      markName
      batchIds
    }
  }
}

# 平台退回: 选择商品-选种类/门店管理-平台开单选商品-选种类
query listVirtualStockCategory($input: ListVirtualStockCategoryInput!) {
  listVirtualStockCategory(input: $input) {
    categoryId
    categoryName
  }
}

# 平台退回: 平台退回列表页/门店管理-退货信息列表页/门店管理-详情页面-退货信息
query pitayaPagePlatformReturn($input: PitayaPagePlatformReturnInput!, $page: Page) {
  pitayaPagePlatformReturn(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      commodities {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
        }
        batches {
          batchInfo {
            warehouse {
              warehouseId
              warehouseName
            }
            batchCode
            batchId
            createTime
            customer {
              customerId
              customerName
              customerType
              lastLevelId
              lastLevelName
            }
            unit {
              unitId
              unitName
            }
            commodityTypeId
            commodityTypeName
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
          itemId
          batch {
            unit {
              unitId
              unitName
            }
            batchCode
            batchId
            createTime
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
            sourceBatchCode
            sourceBatchId
          }
          dynamicQuantity {
            unit {
              unitId
              unitName
            }
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
          index
        }
        commodityType
        commodityTypeName
        returnId
        returnType
        returnableQuantity
        saleData {
          # saleItemId
          salePrice
          saleTotalPrice
          quantity
          saleOrderId
        }
        stockQuantity {
          unit {
            unitId
            unitName
          }
          quantity
        }
        unit {
          unitId
          unitName
        }
        amount
        mark
        markName
        returnableAmount
      }
      createTime
      remark
      returnCode
      returnId
      returnStatus
      returnStatusName
      returnTime
      returnType
      returnTypeName
      saleOrderCode
      saleOrderId
      bill2FetchData {
        billDetailsList {
          supplier {
            supplierId
            supplierName
          }
          billCostData
          billDetailId
          billMainId
          businessItemValue
          costAmount
          costId
          costName
          dictItemId
          note
          paymentType
          ruleCode
          ruleId
          showField
        }
        billMainId
        templateId
        totalTransportFees
      }
      differenceOrderType
      saleReturnWay
      saleReturnWayName
      saleTime
      sourceBill2Data {
        billDetailsList {
          supplier {
            supplierId
            supplierName
          }
          billCostData
          billDetailId
          billMainId
          businessItemValue
          costAmount
          costId
          costName
          dictItemId
          note
          paymentType
          ruleCode
          ruleId
          showField
        }
        billMainId
        templateId
        totalTransportFees
      }
    }
    totalRecords
  }
}

# 平台退回: 角标/门店管理-退货信息列表页-角标
query pitayaPlatformReturnBadge($input: PitayaPagePlatformReturnInput) {
  pitayaPlatformReturnBadge(input: $input) {
    toBeInbound
    toBeSubmitted
  }
}

# 平台退回: 新增/门店管理-新增平台退回
mutation createPlatformReturn($input: CreateOrUpdatePlatformReturnInput!) {
  createPlatformReturn(input: $input)
}

# 平台退回: 修改/门店管理-修改平台退回
mutation updatePlatformReturn($input: CreateOrUpdatePlatformReturnInput!, $returnId: ID!) {
  updatePlatformReturn(input: $input, returnId: $returnId)
}

# 销售退货/平台退回/平台开单退货信息: 详情页
query pitayaReturnDetail($input: PitayaReturnInput!) {
  pitayaReturnDetail(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    createBy {
      phoneNum
      userId
      userName
    }
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    commodities {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      batches {
        batchInfo {
          warehouse {
            warehouseId
            warehouseName
          }
          batchCode
          batchId
          createTime
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          commodityTypeId
          commodityTypeName
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        itemId
        batch {
          batchCode
          batchId
          createTime
          sourceBatchCode
          sourceBatchId
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        dynamicQuantity {
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        index
      }
      commodityType
      commodityTypeName
      returnId
      returnType
      returnableQuantity
      saleData {
        # saleItemId
        salePrice
        saleTotalPrice
        quantity
        saleOrderId
      }
      stockQuantity {
        unit {
          unitId
          unitName
        }
        quantity
      }
      amount
      returnableAmount
      mark
      markName
      unit {
        unitId
        unitName
      }
    }
    createTime
    remark
    returnCode
    returnId
    returnStatus
    returnStatusName
    returnTime
    returnType
    returnTypeName
    saleOrderCode
    saleOrderId
    saleTime
    differenceOrderType
    saleReturnWay
    saleReturnWayName
    bill2FetchData {
      billDetailsList {
        supplier {
          supplierId
          supplierName
        }
        billCostData
        billDetailId
        billMainId
        businessItemValue
        costAmount
        costId
        costName
        dictItemId
        note
        paymentType
        ruleCode
        ruleId
        showField
      }
      billMainId
      templateId
      totalTransportFees
    }
    sourceBill2Data {
      billDetailsList {
        supplier {
          supplierId
          supplierName
        }
        billCostData
        billDetailId
        billMainId
        businessItemValue
        costAmount
        costId
        costName
        dictItemId
        note
        paymentType
        ruleCode
        ruleId
        showField
      }
      billMainId
      templateId
      totalTransportFees
    }
  }
}

# 销售退货/平台退回: 取消
mutation pitayaCancelReturn($input: PitayaReturnInput!) {
  pitayaCancelReturn(input: $input)
}

# 销售退货/平台退回: 提交
mutation pitayaSubmitReturn($input: PitayaReturnInput!) {
  pitayaSubmitReturn(input: $input)
}

# 销售退货/平台退回: 作废
mutation pitayaVoidReturn($input: PitayaReturnInput!) {
  pitayaVoidReturn(input: $input)
}

# 销售退货/平台退回: 撤销
mutation pitayaWithdrawReturn($input: PitayaReturnInput!) {
  pitayaWithdrawReturn(input: $input)
}