# 门店管理: 新增平台开单-一件填入
query listPlatformSalePlan($input: ListPlatformSalePlanInput!) {
  listPlatformSalePlan(input: $input) {
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    commodities {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      addressId
      commodityType
      commodityTypeName
      itemId
      planId
      planQuantity {
        unit {
          unitId
          unitName
        }
        quantity
        quantityItem {
          unit {
            unitId
            unitName
          }
          quantity
        }
      }
      stockQuantity {
        unit {
          unitId
          unitName
        }
        quantity
      }
      mark
      markName
    }
    planCode
    planId
    planTime
  }
}

# 门店管理: 销售退货选择销售单和商品/销售退货-选择商品
query listSaleReturnCommodity($input: ListSaleReturnCommodityInput!) {
  listSaleReturnCommodity(input: $input) {
    createBy {
      phoneNum
      userId
      userName
    }
    belongOrg {
      orgName
      orgId
    }
    commodities {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      commodityType
      commodityTypeName
      returnableQuantity
      saleOrderId
      saleOrderType
      salePrice
      saleQuantity
      saleTotalPrice
      returnableAmount
      mark
      markName
      unit {
        unitId
        unitName
      }
    }
    createTime
    saleOrderCode
    saleOrderId
    saleOrderType
    saleOrderTypeName
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    saleTime
  }
}

# 门店管理: 商超管理-列表页/门店管理-搜索客户页/门店管理-详情页面
query listStoreManagement($input: ListStoreManagementInput!) {
  listStoreManagement(input: $input) {
    customerDetail {
      addresses {
        addressId
        addressName
        belongType
        deliveryName
        isEnabled
        stockCount
      }
      customerId
      customerName
      customerType
    }
  }
}

# 门店管理: 库存信息详情页/库存搜索页面/门店管理-详情页面
query listStoreManagementStockInfo($input: ListStoreManagementStockInfoInput!) {
  listStoreManagementStockInfo(input: $input) {
    commoditySku {
      categoryId
      categoryName
      commodityId
      commodityName
      commoditySkuId
      commoditySkuName
      commoditySpecOptionId
      commoditySpecOptionName
      availableSkuQuantity {
        businessUnit {
          unitId
          unitName
        }
        unit {
          unitId
          unitName
        }
        conversion
      }
      baseUnit {
        unitId
        unitName
      }
    }
    batches {
      batchCode
      batchId
      createTime
      sourceBatchCode
      sourceBatchId
      deliveryCode
      planCode
      planSaleTime
      dynamicQuantity {
        unit {
          unitId
          unitName
        }
        quantity
      }
    }
    commodityType
    commodityTypeName
    stockQuantity {
      unit {
        unitId
        unitName
      }
      quantity
    }
    mark
    markName
  }
}

# 门店管理: 开单信息列表页/搜索商品名称/门店管理-详情页面
query pageStoreManagementSaleInfo(
  $input: PageStoreManagementSaleInfoInput!
  $page: Page
) {
  pageStoreManagementSaleInfo(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      commodities {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
        }
        batchInfo {
          itemId
          batchCode
          batchId
          batch {
            unit {
              unitId
              unitName
            }
            batchCode
            batchId
            createTime
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
            sourceBatchCode
            sourceBatchId
          }
          dynamicQuantity {
            unit {
              unitId
              unitName
            }
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
          index
        }
        commodityType
        commodityTypeName
        salePrice
        totalSalePrice
        unit {
          unitId
          unitName
        }
        mark
        markName
      }
      createTime
      platformSaleReturnOrders {
        belongOrg {
          orgId
          orgName
        }
        createBy {
          phoneNum
          userId
          userName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        commodities {
          commoditySku {
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
            availableSkuQuantity {
              businessUnit {
                unitId
                unitName
              }
              unit {
                unitId
                unitName
              }
              conversion
            }
            baseUnit {
              unitId
              unitName
            }
          }
          batches {
            batchInfo {
              warehouse {
                warehouseId
                warehouseName
              }
              batchCode
              batchId
              createTime
              customer {
                customerId
                customerName
                customerType
                lastLevelId
                lastLevelName
              }
              unit {
                unitId
                unitName
              }
              commodityTypeId
              commodityTypeName
              quantity
              quantityItem {
                unit {
                  unitId
                  unitName
                }
                quantity
              }
            }
            itemId
            batch {
              unit {
                unitId
                unitName
              }
              batchCode
              batchId
              createTime
              quantity
              quantityItem {
                unit {
                  unitId
                  unitName
                }
                quantity
              }
              sourceBatchCode
              sourceBatchId
            }
            dynamicQuantity {
              unit {
                unitId
                unitName
              }
              quantity
              quantityItem {
                unit {
                  unitId
                  unitName
                }
                quantity
              }
            }
            index
          }
          commodityType
          commodityTypeName
          returnId
          returnType
          returnableQuantity
          saleData {
            # saleItemId
            salePrice
            saleTotalPrice
            quantity
            saleOrderId
          }
          stockQuantity {
            unit {
              unitId
              unitName
            }
            quantity
          }
          unit {
            unitId
            unitName
          }
          amount
          mark
          markName
          returnableAmount
        }
        createTime
        remark
        returnCode
        returnId
        returnStatus
        returnStatusName
        returnTime
        returnType
        returnTypeName
        saleOrderCode
        saleOrderId
        bill2FetchData {
          billDetailsList {
            supplier {
              supplierId
              supplierName
            }
            billCostData
            billDetailId
            billMainId
            businessItemValue
            costAmount
            costId
            costName
            dictItemId
            note
            paymentType
            ruleCode
            ruleId
            showField
          }
          billMainId
          templateId
          totalTransportFees
        }
        differenceOrderType
        saleReturnWay
        saleReturnWayName
        saleTime
        sourceBill2Data {
          billDetailsList {
            supplier {
              supplierId
              supplierName
            }
            billCostData
            billDetailId
            billMainId
            businessItemValue
            costAmount
            costId
            costName
            dictItemId
            note
            paymentType
            ruleCode
            ruleId
            showField
          }
          billMainId
          templateId
          totalTransportFees
        }
      }
      remark
      saleAmount
      saleOrderCode
      saleOrderId
      saleOrderStatus
      saleOrderStatusName
      saleTime
      saleIncomeId
    }
    totalRecords
  }
}

# 门店管理: 平台开单详情页
query platformSaleDetail($input: PlatformSaleInput!) {
  platformSaleDetail(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    createBy {
      phoneNum
      userId
      userName
    }
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    commodities {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      batchInfo {
        itemId
        batch {
          batchCode
          batchId
          createTime
          sourceBatchCode
          sourceBatchId
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        batchCode
        batchId
        dynamicQuantity {
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        index
      }
      commodityType
      commodityTypeName
      salePrice
      totalSalePrice
      mark
      markName
      unit {
        unitId
        unitName
      }
    }
    createTime
    platformSaleReturnOrders {
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      commodities {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          availableSkuQuantity {
            businessUnit {
              unitId
              unitName
            }
            unit {
              unitId
              unitName
            }
            conversion
          }
          baseUnit {
            unitId
            unitName
          }
        }
        batches {
          batchInfo {
            warehouse {
              warehouseId
              warehouseName
            }
            batchCode
            batchId
            createTime
            customer {
              customerId
              customerName
              customerType
              lastLevelId
              lastLevelName
            }
            unit {
              unitId
              unitName
            }
            commodityTypeId
            commodityTypeName
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
          itemId
          batch {
            unit {
              unitId
              unitName
            }
            batchCode
            batchId
            createTime
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
            sourceBatchCode
            sourceBatchId
          }
          dynamicQuantity {
            unit {
              unitId
              unitName
            }
            quantity
            quantityItem {
              unit {
                unitId
                unitName
              }
              quantity
            }
          }
          index
        }
        commodityType
        commodityTypeName
        returnId
        returnType
        returnableQuantity
        saleData {
          # saleItemId
          salePrice
          saleTotalPrice
          quantity
          saleOrderId
        }
        stockQuantity {
          unit {
            unitId
            unitName
          }
          quantity
        }
        unit {
          unitId
          unitName
        }
        amount
        mark
        markName
        returnableAmount
      }
      createTime
      remark
      returnCode
      returnId
      returnStatus
      returnStatusName
      returnTime
      returnType
      returnTypeName
      saleOrderCode
      saleOrderId
      bill2FetchData {
        billDetailsList {
          supplier {
            supplierId
            supplierName
          }
          billCostData
          billDetailId
          billMainId
          businessItemValue
          costAmount
          costId
          costName
          dictItemId
          note
          paymentType
          ruleCode
          ruleId
          showField
        }
        billMainId
        templateId
        totalTransportFees
      }
      differenceOrderType
      saleReturnWay
      saleReturnWayName
      saleTime
      sourceBill2Data {
        billDetailsList {
          supplier {
            supplierId
            supplierName
          }
          billCostData
          billDetailId
          billMainId
          businessItemValue
          costAmount
          costId
          costName
          dictItemId
          note
          paymentType
          ruleCode
          ruleId
          showField
        }
        billMainId
        templateId
        totalTransportFees
      }
    }
    remark
    saleAmount
    saleOrderCode
    saleOrderId
    saleOrderStatus
    saleOrderStatusName
    saleTime
    saleIncomeId
  }
}

# 门店管理: 新增平台开单-新增
mutation createPlatformSale($input: CreatePlatformSaleInput!) {
  createPlatformSale(input: $input)
}

# 门店管理: 新增销售退货
mutation createPlatformSaleReturn(
  $input: CreateOrUpdatePlatformSaleReturnInput!
) {
  createPlatformSaleReturn(input: $input)
}

# 门店管理: 修改销售退货
mutation updatePlatformSaleReturn(
  $input: CreateOrUpdatePlatformSaleReturnInput!
  $returnId: ID!
) {
  updatePlatformSaleReturn(input: $input, returnId: $returnId)
}

# 门店管理: 平台开单详情页-作废
mutation voidPlatformSale($input: PlatformSaleInput!) {
  voidPlatformSale(input: $input)
}

# 平台开单: 售后单状态角标
query platformSaleAfterSaleBadge($input: PlatformSaleAfterSaleBadgeInput) {
  platformSaleAfterSaleBadge(input: $input) {
    toBeDealt
  }
}

# 平台开单: 再来一单
mutation oneMorePlatformSale($input: OneMorePlatformSaleInput) {
  oneMorePlatformSale(input: $input) {
    outOfStockItems {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      commodityType
    }
    saleOrderId
  }
}

# 平台开单: 获取平台开单单子上商品列表，商品列表区分有库存还是没有库存
query listPlatformSaleCommodity(
  $listPlatformSaleCommodityInput: ListPlatformSaleCommodityInput
) {
  listPlatformSaleCommodity(
    listPlatformSaleCommodityInput: $listPlatformSaleCommodityInput
  ) {
    commodityListWithStock {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      batchInfo {
        itemId
        batchCode
        batchId
        batch {
          unit {
            unitId
            unitName
          }
          batchCode
          batchId
          createTime
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
          sourceBatchCode
          sourceBatchId
        }
        dynamicQuantity {
          unit {
            unitId
            unitName
          }
          quantity
          quantityItem {
            unit {
              unitId
              unitName
            }
            quantity
          }
        }
        index
      }
      commodityType
      commodityTypeName
      salePrice
      totalSalePrice
      mark
      markName
      unit {
        unitId
        unitName
      }
    }
    outOfStockItems {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        availableSkuQuantity {
          businessUnit {
            unitId
            unitName
          }
          unit {
            unitId
            unitName
          }
          conversion
        }
        baseUnit {
          unitId
          unitName
        }
      }
      commodityType
    }
  }
}
