query pageReceiptPlan($input: ReceiptPlanPageInput) {
  pageReceiptPlan(input: $input) {
    pageCurrent
    pageSize
    records {
      cabinetBatchCode
      cabinetCode
      categoryId
      categoryName
      customerId
      customerName
      originPlanCode
      planId
      receiptTemperatureState
      receiptTime
      salesPlanCode
      shipmentTime
      state
      tagAttribute
      tagList {
        canDeleted
        createBy
        createTime
        createUserName
        enabled
        id
        meaning
        name
        planId
        remark
        styleColor
        tagBelong
        tagId
        type
      }
      tags {
        canDeleted
        createBy
        createTime
        createUserName
        enabled
        id
        meaning
        name
        planId
        remark
        styleColor
        tagBelong
        tagId
        type
      }
      taskId
      temperatureFile {
        externalInfo {
          watermarkText
        }
        fileId
        fileUploadTime
        fileUrl
        filename
      }
    }
    totalRecords
  }
}

query receiptDetail($input: ID) {
  receiptDetail(input: $input) {
    billMainId
    cabinetBatchCodeList
    cabinetCodeList
    categoryId
    categoryName
    emptyCabinetBillBusinessState
    emptyCabinetInfo {
      emptyCabinetDate
    }
    headquarterAreaOrderInfo {
      areaPurchaseOrderId
      headquarterAreaOrderRunCode
      headquarterSalesOrderId
    }
    pictureUrl
    planCode
    planId
    planList {
      planCode
      planId
      taskId
    }
    salePlanCreateTime
    sampleQuantity
    sopId
    sopIds
    sopOptionList {
      label
      value
    }
    state
    stateName
    taskId
    thermometerOrderId
    thermometerOrderInfo {
      bindThermometerState
      cabinetInfo {
        cabinetCode
        cabinetId
        deviceId
        originPlanCode
        salesPlanCode
      }
      currentAlarmLogList {
        alarmColor
        alarmDesc
        alarmState
        alarmSubType
        alarmTextColor
        alarmType
        alarmValue
        durationTime
        endAddress
        endTime
        handleContent
        handleTime
        handler
        id
        startAddress
        startTime
      }
      deviceInfo {
        currentAddress
        firstReportTime
        humidity
        lastReportTime
        lat
        lng
        temperature
        thermometerCode
      }
      orderInfo {
        alarmLogList {
          alarmColor
          alarmDesc
          alarmState
          alarmSubType
          alarmTextColor
          alarmType
          alarmValue
          durationTime
          endAddress
          endTime
          handleContent
          handleTime
          handler
          id
          startAddress
          startTime
        }
        alarmState
        firstAlarmTime
        thermometerEndTime
        thermometerStartTime
      }
      thermometerOrderId
    }
    tmpId
    totalQuantity
    transportInfo {
      backupPhone
      cabinetType
      carNo
      deliverAddress
      deliverAddressType
      departureDate
      driver
      entryPort
      entryPortId
      phone
      receiptPlace
      trailerNo
      transportCompany
    }
    billBusinessId
  }
}

query receiptPage($input: ReceiptPageInput) {
  receiptPage(input: $input) {
    pageCurrent
    pageSize
    records {
      acceptanceTime
      backupPhone
      cabinetBatchCode
      cabinetCode
      carNo
      category
      deliverAddressType
      departureDate
      driverName
      driverPhone
      entryPort
      pictureUrl
      planCode
      quantity
      receiptAddress
      receiptDate
      sampleQuantity
      sopId
      state
      stateDesc
      taskId
      thermometerOrderId
      thermometerOrderInfo {
        bindThermometerState
        cabinetInfo {
          cabinetCode
          cabinetId
          deviceId
          originPlanCode
          salesPlanCode
        }
        currentAlarmLogList {
          alarmColor
          alarmDesc
          alarmState
          alarmSubType
          alarmTextColor
          alarmType
          alarmValue
          durationTime
          endAddress
          endTime
          handleContent
          handleTime
          handler
          id
          startAddress
          startTime
        }
        deviceInfo {
          currentAddress
          firstReportTime
          humidity
          lastReportTime
          lat
          lng
          temperature
          thermometerCode
        }
        orderInfo {
          alarmLogList {
            alarmColor
            alarmDesc
            alarmState
            alarmSubType
            alarmTextColor
            alarmType
            alarmValue
            durationTime
            endAddress
            endTime
            handleContent
            handleTime
            handler
            id
            startAddress
            startTime
          }
          alarmState
          firstAlarmTime
          thermometerEndTime
          thermometerStartTime
        }
        thermometerOrderId
      }
      trailerNo
    }
    totalRecords
  }
}

query receiptQuantity($input: ReceiptQuantityInput) {
  receiptQuantity(input: $input) {
    finishedTotal
    totalTodoQuantity
    waitAcceptanceTotal
    waitEmptyCabinetTotal
  }
}

query receiptSearch($input: ReceiptSearchInput) {
  receiptSearch(input: $input) {
    pageCurrent
    pageSize
    records {
      acceptanceTime
      backupPhone
      cabinetBatchCode
      cabinetCode
      carNo
      category
      deliverAddressType
      departureDate
      driverName
      driverPhone
      entryPort
      pictureUrl
      planCode
      quantity
      receiptAddress
      receiptDate
      sampleQuantity
      sopId
      state
      stateDesc
      taskId
      thermometerOrderId
      thermometerOrderInfo {
        bindThermometerState
        cabinetInfo {
          cabinetCode
          cabinetId
          deviceId
          originPlanCode
          salesPlanCode
        }
        currentAlarmLogList {
          alarmColor
          alarmDesc
          alarmState
          alarmSubType
          alarmTextColor
          alarmType
          alarmValue
          durationTime
          endAddress
          endTime
          handleContent
          handleTime
          handler
          id
          startAddress
          startTime
        }
        deviceInfo {
          currentAddress
          firstReportTime
          humidity
          lastReportTime
          lat
          lng
          temperature
          thermometerCode
        }
        orderInfo {
          alarmLogList {
            alarmColor
            alarmDesc
            alarmState
            alarmSubType
            alarmTextColor
            alarmType
            alarmValue
            durationTime
            endAddress
            endTime
            handleContent
            handleTime
            handler
            id
            startAddress
            startTime
          }
          alarmState
          firstAlarmTime
          thermometerEndTime
          thermometerStartTime
        }
        thermometerOrderId
      }
      trailerNo
    }
    totalRecords
  }
}

mutation commitTemperatureInfo($input: ReceiptTemperatureInput) {
  commitTemperatureInfo(input: $input)
}

mutation confirmFee($input: ReceiptFeeConfirmInput) {
  confirmFee(input: $input)
}

mutation receiptBack($input: ReceiptBackInput) {
  receiptBack(input: $input)
}

mutation calculatorAmount($input: CalculatorInput) {
  calculatorAmount(input: $input)
}

query getFeeBillById($input: BillGetInput) {
  getFeeBillById(input: $input) {
    amount
    billFieldList {
      data
      decimalPlaces
      fieldId
      fieldKey
      fieldName
      fieldType
      isInteger
      note
      required
    }
    calculateRule
    calculateType
    costId
    costName
    needInvoicingSupplier
    note
    remark
    ruleId
    showField
    showFieldValue
    supplierId
    tmpId
  }
}

query getSopList($sopIds: [ID]) {
  getSopList(sopIds: $sopIds) {
    sopId
    sopName
    time
  }
}
