query getPitayaTemplateByTriggerCondition($input: GetTemplateInput) {
  getPitayaTemplateByTriggerCondition(input: $input) {
    appId
    createTime
    note
    status
    tempCode
    tempId
    tempName
    tempType
    templateDetailList {
      amount
      businessItemValue
      costRule {
        calculateRule
        calculateType
        costId
        costName
        fieldList {
          data
          dataSourceList
          dataType
          decimalPlaces
          fieldId
          fieldKey
          fieldName
          fieldType
          isInteger
          note
          required
        }
        note
        ruleCode
        ruleId
        ruleName
        showField
        status
        tenantId
        version
      }
      dictItemId
      extendTypesList
      partCostCalculate
      repeatUse
      requiredField
    }
    tenantId
    updateTime
    version
  }
}

query getPitayaTemplateByTempId($input: GetTemplateByIdInput) {
  getPitayaTemplateByTempId(input: $input) {
    appId
    createTime
    note
    status
    tempCode
    tempId
    tempName
    tempType
    templateDetailList {
      amount
      businessItemValue
      costRule {
        calculateRule
        calculateType
        costId
        costName
        fieldList {
          data
          dataSourceList
          dataType
          decimalPlaces
          fieldId
          fieldKey
          fieldName
          fieldType
          isInteger
          note
          required
        }
        note
        ruleCode
        ruleId
        ruleName
        showField
        status
        tenantId
        version
      }
      dictItemId
      extendTypesList
      partCostCalculate
      repeatUse
      requiredField
    }
    tenantId
    updateTime
    version
  }
}

query getBillDictItem($input: GetBillDictItemInput) {
  getBillDictItem(input: $input) {
    description
    dictCode
    dictItemId
    itemText
    itemValue
    sort
  }
}
