query pageDamageOutOrder(
  $pageDamageOutOrderInput: PageDamageOutOrderInput
  $page: Page
) {
  pageDamageOutOrder(
    pageDamageOutOrderInput: $pageDamageOutOrderInput
    page: $page
  ) {
    records {
      outOrderStatus
      outOrderStatusName
      outOrderId
      outOrderCode
      outOrderType
      outOrderTypeName
      commodityTypeId
      commodityTypeName
      warehouse {
        warehouseId
        warehouseName
      }
      belongOrg {
        orgId
        orgName
      }
      applyDate
      outOrderDescription
      errorDescription
      createUser {
        userId
        userName
        phoneNum
      }
      createTime
      commodities {
        outOrderItemId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
        }
        stockBatchInfo {
          batchId
          batchCode
          unitQuantity
          totalQuantity
          customerBelongInfo {
            customerId
            customerName
            customerType
          }
        }
        damageQuantity {
          unitQuantity
          totalQuantity
        }
        damageReason
      }
      photos {
        proofUploads {
          fileId
          fileName
          fileUrl
          fileUploadTime
        }
        damageOrder {
          fileId
          fileName
          fileUrl
          fileUploadTime
        }
        processProofUploads {
          fileId
          fileName
          fileUrl
          fileUploadTime
        }
      }
      auditLogs {
        createUser {
          userId
          userName
          phoneNum
        }
        completeTime
        note
        actionTypeId
        actionTypeName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

query listDamageFlowTemplate($input: ListDamageFlowTemplateInput) {
  listDamageFlowTemplate(input: $input) {
    id
    name
  }
}

query damageOutOrder($damageOutIDInput: DamageOutIDInput) {
  damageOutOrder(damageOutIDInput: $damageOutIDInput) {
    outOrderStatus
    outOrderStatusName
    outOrderId
    outOrderCode
    outOrderType
    outOrderTypeName
    commodityTypeId
    commodityTypeName
    warehouse {
      warehouseId
      warehouseName
    }
    belongOrg {
      orgId
      orgName
    }
    applyDate
    outOrderDescription
    errorDescription
    createUser {
      userId
      userName
      phoneNum
    }
    createTime
    commodities {
      outOrderItemId
      commoditySku {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        categoryId
        categoryName
      }
      stockBatchInfo {
        batchId
        batchCode
        unitQuantity
        totalQuantity
        customerBelongInfo {
          customerId
          customerName
          customerType
        }
      }
      damageQuantity {
        unitQuantity
        totalQuantity
      }
      damageReason
    }
    photos {
      proofUploads {
        fileId
        fileName
        fileUrl
        fileUploadTime
      }
      damageOrder {
        fileId
        fileName
        fileUrl
        fileUploadTime
      }
      processProofUploads {
        fileId
        fileName
        fileUrl
        fileUploadTime
      }
    }
    auditLogs {
      createUser {
        userId
        userName
        phoneNum
      }
      completeTime
      note
      actionTypeId
      actionTypeName
    }
  }
}

query damageOutStatusCount(
  $damageOutStatusCountInput: DamageOutStatusCountInput
) {
  damageOutStatusCount(damageOutStatusCountInput: $damageOutStatusCountInput) {
    toBeSubmit
    inProgress
    toBeOut
    rejected
    canceled
    completed
  }
}

mutation createDamageOutOrder(
  $createDamageOutOrderInput: CreateDamageOutOrderInput
) {
  createDamageOutOrder(createDamageOutOrderInput: $createDamageOutOrderInput)
}

mutation updateDamageOutOrder(
  $createDamageOutOrderInput: CreateDamageOutOrderInput
) {
  updateDamageOutOrder(createDamageOutOrderInput: $createDamageOutOrderInput)
}

mutation outDamageOutOrder($damageOutIDInput: DamageOutIDInput) {
  outDamageOutOrder(damageOutIDInput: $damageOutIDInput)
}

mutation submitDamageOutOrder($damageOutIDInput: DamageOutIDInput) {
  submitDamageOutOrder(damageOutIDInput: $damageOutIDInput)
}

mutation cancelDamageOutOrder($damageOutIDInput: DamageOutIDInput) {
  cancelDamageOutOrder(damageOutIDInput: $damageOutIDInput)
}
