# 入库记录列表
query pageInOrderRecord($inOrderRecordCondition: InOrderRecordFilter!, $page: Page) {
  pageInOrderRecord(inOrderRecordCondition: $inOrderRecordCondition, page: $page) {
    records {
      inStockRecordId
      inOrderTypeId
      inOrderTypeName
      inOrderCode
      commodityTypeId
      commodityTypeName
      customerTypeId
      customerTypeName
      customerId
      customerName
      warehouseId
      warehouseName
      createUserName
      createTime
      commodities {
        conversion
        commodityId
        commodityName
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        unitQuantity
        unitTypeName
        totalQuantity
        totalTypeName
        unitPrice
        unitPriceTypeName
        unitTotalPrice
        batchCode
        batchInfo {
          warehouse {
            warehouseId
            warehouseName
          }
          batchCode
          batchId
          createTime
          totalQuantity
          unitQuantity
          commodityTypeId
          commodityTypeName
        }
        grossUnitQuantity
      }
      inStockCode
      stockOrderTypeId
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 入库记录详情
query getInOrderRecordDetail($inOrderDetailInput: InOrderDetailInput) {
  getInOrderRecordDetail(inOrderDetailInput: $inOrderDetailInput) {
    inStockRecordId
    inOrderTypeId
    inOrderTypeName
    inOrderCode
    taskId
    taskCode
    commodityTypeId
    commodityTypeName
    customerTypeId
    customerTypeName
    customerId
    customerName
    inOrderStatusId
    inOrderStatus
    warehouseId
    warehouseName
    supplierId
    supplierName
    inOrderDescription
    commodities {
      conversion
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitTypeName
      grossUnitQuantity
      totalQuantity
      totalTypeName
      unitPrice
      unitPriceTypeName
      unitTotalPrice
      batchCode
      batchInfo {
        warehouse {
          warehouseId
          warehouseName
        }
        batchCode
        batchId
        commodityTypeId
        commodityTypeName
        createTime
        totalQuantity
        unitQuantity
      }
      mark
      markName
    }
    totalPrice
    submitUserName
    submitTime
    putInUserName
    putInTime
    deliveryFee
    inStockCode
    stockOrderTypeId
  }
}

# 出库记录: 出库记录列表（出库记录）
query pageOutStockRecord($page: Page, $pageOutStockRecordInput: PageOutStockRecordInput!) {
  pageOutStockRecord(
    page: $page
    pageOutStockRecordInput: $pageOutStockRecordInput
  ) {
    pageCurrent
    pageSize
    records {
      commodityTypeId
      commodityTypeName
      createBy
      createTime
      createUserName
      customerId
      customerName
      customerType
      customerTypeName
      deliveryFee
      items {
        basketCustomerId
        basketCustomerName
        basketQuantity
        belongCustomerId
        belongCustomerName
        belongWarehouseId
        belongWarehouseName
        commodityId
        commodityName
        commoditySkuId
        conversion
        outOrderCode
        outOrderId
        outOrderType
        outStockRecordId
        outStockRecordItemId
        photos
        salePrice
        salePriceType
        salePriceTypeName
        skuSpecOptionId
        skuTextDescription
        stockBatchCode
        stockTotalPrice
        stockUnitPrice
        stockUnitPriceType
        stockUnitPriceTypeName
        taskId
        totalPrice
        totalQuantity
        totalType
        totalTypeName
        unitQuantity
        unitType
        unitTypeName
        batchInfo {
          warehouse {
            warehouseId
            warehouseName
          }
          batchCode
          batchId
          createTime
          totalQuantity
          unitQuantity
          commodityTypeId
          commodityTypeName
        }
      }
      organizationId
      organizationName
      outOrderCode
      outOrderId
      outOrderItemId
      outOrderType
      outOrderTypeName
      outStockCode
      outStockRecordId
      remark
      taskCode
      totalPrice
      warehouseId
      warehouseName
      stockOrderType
    }
    totalRecords
  }
}

# 出库记录详情
query outOrderRecordDetail($outStockRecordInput: OutStockRecordInput, $getOutStockRecordLogInput: GetOutStockRecordLogInput) {
  outStockRecord(outStockRecordInput: $outStockRecordInput) {
    outStockRecordId
    outOrderId
    outOrderType
    commodityTypeId
    commodityTypeName
    totalPrice
    organizationId
    organizationName
    warehouseId
    warehouseName
    customerType
    customerTypeName
    customerId
    customerName
    taskCode
    createUserName
    createTime
    createBy
    outOrderItemId
    remark
    outStockCode
    outOrderCode
    outOrderTypeName
    deliveryFee
    items {
      commodityName
      skuTextDescription
      basketQuantity
      basketCustomerName
      salePrice
      salePriceTypeName
      totalPrice
      totalType
      totalTypeName
      unitType
      unitTypeName
      items {
        outStockRecordItemId
        outStockRecordId
        outOrderId
        stockBatchCode
        outOrderCode
        commodityId
        commodityName
        commoditySkuId
        skuSpecOptionId
        skuTextDescription
        salePrice
        salePriceType
        salePriceTypeName
        totalPrice
        unitType
        unitTypeName
        unitQuantity
        totalType
        totalTypeName
        totalQuantity
        taskId
        outOrderType
        belongCustomerId
        belongCustomerName
        belongWarehouseId
        belongWarehouseName
        basketQuantity
        basketCustomerId
        basketCustomerName
        stockUnitPrice
        stockUnitPriceType
        stockUnitPriceTypeName
        stockTotalPrice
        batchInfo {
          warehouse {
            warehouseId
            warehouseName
          }
          batchCode
          batchId
          commodityTypeId
          commodityTypeName
          createTime
          totalQuantity
          unitQuantity
        }
        conversion
        photos
        mark
        markName
      }
      outStockCode
      conversion
    }
    stockOrderType
  }
  getOutStockRecordLog(getOutStockRecordLogInput: $getOutStockRecordLogInput) {
    submitUserName
    submitTime
    putInUserName
    putInTime
  }
}

# 出库记录: 获取筛选类型
query listOutStockRecordType {
  listOutStockRecordType {
    label
    outOrderTypeId
    stockOrderTypeId
  }
}

# 入库记录: 获取筛选类型
query listInStockRecordType {
  listInStockRecordType {
    label
    inOrderTypeId
    stockOrderTypeId
  }
}