## 实时库存 分页
query pageStock($page: Page, $stockConditionInput: StockConditionInput) {
  pageStock(page: $page, stockConditionInput: $stockConditionInput) {
    records {
      commoditySkuId
      commodityTypeId
      commodityName
      batchCode
      unitQuantity
      unitTypeName
      totalQuantity
      totalTypeName
      belongType
      belongId
      belongName
      warehouseName
      specOptionList
      createTime
      inTime
      commodityStatus
      displayBelongName
    }
    pageCurrent
    pageSize
    totalRecords
  }
}
