# 其他出库申请
mutation createOtherOutOrder(
  $createOtherOutOrderInput: CreateOtherOutOrderInput
) {
  createOtherOutOrder(createOtherOutOrderInput: $createOtherOutOrderInput)
}

# 其他出库申请修改
mutation updateOtherOutOrder(
  $updateOtherOutOrderInput: UpdateOtherOutOrderInput
) {
  updateOtherOutOrder(updateOtherOutOrderInput: $updateOtherOutOrderInput)
}

# 完成出库请求当前出库状态数据
query confirmOutOrderStatistics($outOrderId: ID!) {
  confirmOutOrderStatistics(outOrderId: $outOrderId) {
    commodityCount
    outOrderFinishCount
    outOrderUnFinishCount
  }
}

# 出库申请状态数量统计
query countOutOrderStatus($countOutOrderStatusInput: CountOutOrderStatusInput) {
  countOutOrderStatus(countOutOrderStatusInput: $countOutOrderStatusInput) {
    toSubmit
    toAudit
    producing
    toOutbound
    finished
  }
}

# 出库申请列表-其他出库
query pageOtherOutOrder(
  $page: Page
  $pageOtherOutOrderInput: PageOtherOutOrderInput
) {
  pageOtherOutOrder(
    page: $page
    pageOtherOutOrderInput: $pageOtherOutOrderInput
  ) {
    records {
      outOrderId
      outOrderType
      outOrderTypeName
      outOrderCode
      commodityTypeId
      commodityTypeName
      outOrderStatus
      outOrderStatusName
      createTime
      outOrderDescription
      errorDescription
      commodityList {
        outOrderItemId
        outOrderId
        unitQuantity
        unitType {
          unitId
          unitName
        }
        totalQuantity
        totalType {
          unitId
          unitName
        }
        salePrice
        unitTotalPrice
        inBoundTotalQuantity
        inBoundUnitQuantity
        commoditySku {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
        priceType {
          unitId
          unitName
        }
        stockBatchInfo {
          customerBelongInfo {
            customerId
            customerName
            customerType
          }
          batchCode
          batchId
          createTime
          totalQuantity
          unitQuantity
        }
      }
      belongOrg {
        orgId
        orgName
      }
      createBy {
        phoneNum
        userId
        userName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      supplier {
        supplierId
        supplierName
      }
      warehouse {
        warehouseId
        warehouseName
      }
      wmsMarkList {
        appId
        businessType
        labelContent
        markId
        tenantId
      }
      billId
      outStockRecordCount
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 取消出库申请订单
mutation cancelOutOrder($cancelOutOrderInput: CancelOutOrderInput!) {
  cancelOutOrder(cancelOutOrderInput: $cancelOutOrderInput)
}

# 提交库管
mutation submitOutOrder($outOrderId: ID!) {
  submitOutOrder(outOrderId: $outOrderId)
}

# v2.8 次品销售:详情页
query outOrder($outOrderInput: OutOrderInput) {
  outOrder(outOrderInput: $outOrderInput) {
    outOrderId
    outOrderType
    outOrderTypeName
    outOrderCode
    commodityTypeId
    commodityTypeName
    customerType
    customerTypeName
    transferId
    transferType
    transferOrganizationId
    transferOrganizationName
    userId
    createUserPhone
    customerId
    customerName
    saleTime
    outOrderStatus
    outOrderStatusName
    warehouseId
    warehouseName
    createUserName
    createTime
    outOrderDescription
    errorDescription
    totalPrice
    commodityList {
      outOrderItemId
      outOrderId
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitType
      unitTypeName
      totalQuantity
      totalType
      totalTypeName
      salePrice
      salePriceType
      salePriceTypeName
      maxQuantity
      planQuantity
      basketQuantity
      basketCustomerId
      basketCustomerName
      createTime
      createBy
      updateTime
      deleted
      updateBy
      waitUnitQuantity
      waitTotalQuantity
      completeOutStock
      commodityBomId
      unitTotalPrice
      damageReason
      batchId
      batchCode
      stockUnitPrice
      stockUnitPriceType
      stockUnitPriceTypeName
      stockTotalPrice
      belongCustomerName
      photos
      realQuantity
      saleTotalPrice
      inBoundTotalQuantity
      inBoundUnitQuantity
      conversion
      outStockFinishUnitQuantity
      outStockFinishTotalQuantity
      belongCustomerId
      pickingUnitQuantity
      pickingTotalQuantity
      commodityStatus
      saleOrderInfo {
        outOrderId
        saleOrderId
        saleOrderCode
      }
      unitStockQuantity
      stockQuantity {
        unitQuantity
        totalQuantity
      }
      stockQuantityWithLock {
        unitQuantity
        totalQuantity
      }
      productPickingQuantity {
        totalQuantity
        unitQuantity
      }
    }
    taskId
    taskCode
    inOrderId
    inOrderCode
    supplierId
    supplierName
    customerDistributionId
    customerDistributionName
    deliveryFee
    organizationId
    organizationName
    payMethod
    payMethodDesc
    saleOrderInfo {
      outOrderId
      saleOrderId
      saleOrderCode
    }
    saleIncomeOrder {
      incomeId
      incomeStatus
      incomeStatusName
      incomeCode
      sourceId
      sourceType
      sourceTypeName
      warehouse {
        warehouseId
        warehouseName
      }
      remark
      rejectReason
      user {
        userId
        userName
        phoneNum
      }
      customer {
        customerId
        customerName
        customerType
      }
      createTime
      commoditiesList {
        incomeItemId
        incomeId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        commodityName
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleMoney
        photosList
        outOrderItemId
        salePrice
        remark
        totalQuantity
        totalType {
          unitId
          unitName
        }
        batchId
        batchCode
        totalSalePrice
        priceType {
          unitId
          unitName
        }
        goodsUnitQuantity
        goodsTotalQuantity
      }
      originalSaleCommodityPayload {
        outOrderItemId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        batchId
        batchCode
        salePrice
        salePriceType {
          unitId
          unitName
        }
        totalQuantity
        totalType {
          unitId
          unitName
        }
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleTotalPrice
        stockQuantity {
          unitQuantity
          totalQuantity
        }
        actualQuantity {
          actualTotalQuantity
          actualUnitQuantity
          actualSalePrice
          actualSaleTotalPrice
          outOrderItemId
        }
        outOrderId
      }
      saleCostOrderItems {
        saleCostOrderItemId
        saleCostOrderId
        outOrderItemId
        commodity {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        packagingFee
        materialFee
      }
      logs {
        incomeLogId
        incomeId
        type
        typeText
        remark
        createTime
        user {
          userId
          userName
          phoneNum
        }
      }
      saleCostOrderId
      functionalField {
        saleTotalPrice
        saleTotalCost
      }
      totalAmount
      commodityTypeName
      payMode
      belongOrg {
        orgId
        orgName
      }
      saleTime
    }
    belongOrg {
      orgId
      orgName
    }
    targetBelongOrg {
      orgId
      orgName
    }
    isExceptional
    netWeightExceptionRatio
  }
}

# 出库申请单分页接口
query pageOutOrder($page: Page, $pageOutOrderInput: PageOutOrderInput) {
  pageOutOrder(page: $page, pageOutOrderInput: $pageOutOrderInput) {
    records {
      outOrderId
      outOrderType
      outOrderTypeName
      outOrderCode
      commodityTypeId
      commodityTypeName
      customerType
      customerTypeName
      transferId
      transferType
      transferOrganizationId
      transferOrganizationName
      userId
      createUserPhone
      customerId
      customerName
      saleTime
      outOrderStatus
      outOrderStatusName
      warehouseId
      warehouseName
      createUserName
      createTime
      outOrderDescription
      errorDescription
      totalPrice
      commodityList {
        outOrderItemId
        outOrderId
        commodityId
        commodityName
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        unitQuantity
        unitType
        unitTypeName
        totalQuantity
        totalType
        totalTypeName
        salePrice
        salePriceType
        salePriceTypeName
        maxQuantity
        planQuantity
        basketQuantity
        basketCustomerId
        basketCustomerName
        createTime
        createBy
        updateTime
        deleted
        updateBy
        waitUnitQuantity
        waitTotalQuantity
        completeOutStock
        commodityBomId
        unitTotalPrice
        damageReason
        batchId
        stockUnitPrice
        stockUnitPriceType
        stockUnitPriceTypeName
        stockTotalPrice
        photos
        realQuantity
        saleTotalPrice
        inBoundTotalQuantity
        inBoundUnitQuantity
        conversion
        outStockFinishUnitQuantity
        outStockFinishTotalQuantity
        pickingUnitQuantity
        pickingTotalQuantity
        commodityStatus
        saleOrderInfo {
          outOrderId
          saleOrderId
          saleOrderCode
        }
        unitStockQuantity
        productPickingQuantity {
          totalQuantity
          unitQuantity
        }
      }
      taskId
      taskCode
      inOrderId
      inOrderCode
      supplierId
      supplierName
      customerDistributionId
      customerDistributionName
      deliveryFee
      organizationId
      organizationName
      payMethod
      payMethodDesc
      saleOrderInfo {
        outOrderId
        saleOrderId
        saleOrderCode
      }
      saleIncomeOrder {
        incomeId
        incomeStatus
        incomeStatusName
        incomeCode
        sourceId
        sourceType
        sourceTypeName
        warehouse {
          warehouseId
          warehouseName
        }
        remark
        rejectReason
        user {
          userId
          userName
          phoneNum
        }
        customer {
          customerId
          customerName
          customerType
        }
        createTime
        commoditiesList {
          incomeItemId
          incomeId
          commoditySku {
            commoditySkuId
            commoditySkuName
            commodityId
            commodityName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
          }
          commodityName
          unitQuantity
          unitType {
            unitId
            unitName
          }
          saleMoney
          photosList
          outOrderItemId
          salePrice
          remark
          totalQuantity
          totalType {
            unitId
            unitName
          }
          batchId
          batchCode
          totalSalePrice
          priceType {
            unitId
            unitName
          }
          goodsUnitQuantity
          goodsTotalQuantity
        }
        originalSaleCommodityPayload {
          outOrderItemId
          commoditySku {
            commoditySkuId
            commoditySkuName
            commodityId
            commodityName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
          }
          batchId
          batchCode
          salePrice
          salePriceType {
            unitId
            unitName
          }
          totalQuantity
          totalType {
            unitId
            unitName
          }
          unitQuantity
          unitType {
            unitId
            unitName
          }
          saleTotalPrice
          stockQuantity {
            unitQuantity
            totalQuantity
          }
          actualQuantity {
            actualTotalQuantity
            actualUnitQuantity
            actualSalePrice
            actualSaleTotalPrice
            outOrderItemId
          }
          outOrderId
        }
        saleCostOrderItems {
          saleCostOrderItemId
          saleCostOrderId
          outOrderItemId
          commodity {
            commoditySkuId
            commoditySkuName
            commodityId
            commodityName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
          }
          packagingFee
          materialFee
        }
        logs {
          incomeLogId
          incomeId
          type
          typeText
          remark
          createTime
          user {
            userId
            userName
            phoneNum
          }
        }
        saleCostOrderId
        functionalField {
          saleTotalPrice
          saleTotalCost
        }
        totalAmount
        commodityTypeName
        payMode
        belongOrg {
          orgId
          orgName
        }
        saleTime
      }
      belongOrg {
        orgId
        orgName
      }
      targetBelongOrg {
        orgId
        orgName
      }
      isExceptional
      matchingSource {
        carNo
        departureDate
        matchDate
        matchSource
        matchSourceName
        runCode
        trailerNo
      }
      supplier {
        supplierId
        supplierName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 出库详情（详情+审核记录数量）
query stockOutDetail(
  $outOrderInput: OutOrderInput!
  $countOutStockRecordInput: CountOutStockRecordInput!
) {
  # 详情页
  outOrder(outOrderInput: $outOrderInput) {
    outOrderId
    outOrderType
    outOrderTypeName
    outOrderCode
    commodityTypeId
    commodityTypeName
    customerType
    customerTypeName
    transferId
    transferType
    transferOrganizationId
    transferOrganizationName
    userId
    createUserPhone
    customerId
    customerName
    saleTime
    outOrderStatus
    outOrderStatusName
    warehouseId
    warehouseName
    createUserName
    createTime
    outOrderDescription
    errorDescription
    totalPrice
    commodityList {
      outOrderItemId
      outOrderId
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitType
      unitTypeName
      totalQuantity
      totalType
      totalTypeName
      salePrice
      salePriceType
      salePriceTypeName
      maxQuantity
      planQuantity
      basketQuantity
      basketCustomerId
      basketCustomerName
      createTime
      createBy
      updateTime
      deleted
      updateBy
      waitUnitQuantity
      waitTotalQuantity
      completeOutStock
      commodityBomId
      unitTotalPrice
      damageReason
      batchId
      batchCode
      stockUnitPrice
      stockUnitPriceType
      stockUnitPriceTypeName
      stockTotalPrice
      belongCustomerName
      photos
      realQuantity
      saleTotalPrice
      inBoundTotalQuantity
      inBoundUnitQuantity
      conversion
      outStockFinishUnitQuantity
      outStockFinishTotalQuantity
      belongCustomerId
      pickingUnitQuantity
      pickingTotalQuantity
      commodityStatus
      saleOrderInfo {
        outOrderId
        saleOrderId
        saleOrderCode
      }
      unitStockQuantity
      stockQuantity {
        unitQuantity
        totalQuantity
      }
      stockQuantityWithLock {
        unitQuantity
        totalQuantity
      }
      productPickingQuantity {
        totalQuantity
        unitQuantity
      }
    }
    matchingSource {
      carNo
      departureDate
      matchDate
      matchSource
      matchSourceName
      runCode
      trailerNo
    }
    supplier {
      supplierId
      supplierName
    }
    taskId
    taskCode
    inOrderId
    inOrderCode
    customerDistributionId
    customerDistributionName
    deliveryFee
    organizationId
    organizationName
    payMethod
    payMethodDesc
    saleOrderInfo {
      outOrderId
      saleOrderId
      saleOrderCode
    }
    saleIncomeOrder {
      incomeId
      incomeStatus
      incomeStatusName
      incomeCode
      sourceId
      sourceType
      sourceTypeName
      warehouse {
        warehouseId
        warehouseName
      }
      remark
      rejectReason
      user {
        userId
        userName
        phoneNum
      }
      customer {
        customerId
        customerName
        customerType
      }
      createTime
      commoditiesList {
        incomeItemId
        incomeId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        commodityName
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleMoney
        photosList
        outOrderItemId
        salePrice
        remark
        totalQuantity
        totalType {
          unitId
          unitName
        }
        batchId
        batchCode
        totalSalePrice
        priceType {
          unitId
          unitName
        }
        goodsUnitQuantity
        goodsTotalQuantity
      }
      originalSaleCommodityPayload {
        outOrderItemId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        batchId
        batchCode
        salePrice
        salePriceType {
          unitId
          unitName
        }
        totalQuantity
        totalType {
          unitId
          unitName
        }
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleTotalPrice
        stockQuantity {
          unitQuantity
          totalQuantity
        }
        actualQuantity {
          actualTotalQuantity
          actualUnitQuantity
          actualSalePrice
          actualSaleTotalPrice
          outOrderItemId
        }
        outOrderId
      }
      saleCostOrderItems {
        saleCostOrderItemId
        saleCostOrderId
        outOrderItemId
        commodity {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        packagingFee
        materialFee
      }
      logs {
        incomeLogId
        incomeId
        type
        typeText
        remark
        createTime
        user {
          userId
          userName
          phoneNum
        }
      }
      saleCostOrderId
      functionalField {
        saleTotalPrice
        saleTotalCost
      }
      totalAmount
      commodityTypeName
      payMode
      belongOrg {
        orgId
        orgName
      }
      saleTime
    }
    belongOrg {
      orgId
      orgName
    }
    targetBelongOrg {
      orgId
      orgName
    }
    isExceptional
    netWeightExceptionRatio
  }
  countOutStockRecord(countOutStockRecordInput: $countOutStockRecordInput)
}

# 出库记录
query stockOutRecords(
  $outOrderInput: OutOrderInput
  $outOrderItemsInput: OutOrderItemsInput
  $outStockRecordsInput: OutStockRecordsInput
) {
  outOrder(outOrderInput: $outOrderInput) {
    commodityTypeId
    outOrderType
  }
  outOrderItems(outOrderItemsInput: $outOrderItemsInput) {
    outOrderItemId
    outOrderId
    commodityId
    commodityName
    commoditySkuId
    commoditySpecOptionId
    skuTextDescription
    unitQuantity
    unitType
    unitTypeName
    totalQuantity
    totalType
    totalTypeName
    salePrice
    salePriceType
    salePriceTypeName
    maxQuantity
    planQuantity
    basketQuantity
    basketCustomerId
    basketCustomerName
    createTime
    createBy
    updateTime
    deleted
    updateBy
    waitUnitQuantity
    waitTotalQuantity
    completeOutStock
    commodityBomId
    unitTotalPrice
    damageReason
    batchId
    batchCode
    stockUnitPrice
    stockUnitPriceType
    stockUnitPriceTypeName
    stockTotalPrice
    belongCustomerName
    photos
    realQuantity
    saleTotalPrice
    inBoundTotalQuantity
    inBoundUnitQuantity
    conversion
    outStockFinishUnitQuantity
    outStockFinishTotalQuantity
    belongCustomerId
    pickingUnitQuantity
    pickingTotalQuantity
    commodityStatus
    saleOrderInfo {
      outOrderId
      saleOrderId
      saleOrderCode
    }
  }
  outStockRecords(outStockRecordsInput: $outStockRecordsInput) {
    outStockRecordId
    outOrderId
    outOrderType
    commodityTypeId
    commodityTypeName
    totalPrice
    organizationId
    organizationName
    warehouseId
    warehouseName
    customerType
    customerId
    customerName
    taskCode
    createUserName
    createTime
    createBy
    outStockCode
    outOrderItemId
    outStockCode
    remark
    deliveryFee
    items {
      commodityName
      skuTextDescription
      basketQuantity
      basketCustomerName
      salePrice
      salePriceTypeName
      totalPrice
      conversion
      unitTypeName
      totalTypeName
      items {
        outStockRecordItemId
        outStockRecordId
        outOrderId
        stockBatchCode
        outOrderCode
        commodityId
        commodityName
        commoditySkuId
        skuTextDescription
        salePrice
        salePriceType
        salePriceTypeName
        totalPrice
        unitType
        unitTypeName
        unitQuantity
        totalType
        totalTypeName
        totalQuantity
        taskId
        outOrderType
        belongCustomerId
        belongCustomerName
        belongWarehouseId
        belongWarehouseName
        basketQuantity
        basketCustomerId
        basketCustomerName
      }
    }
  }
}

# 驳回
mutation rejectOutOrderAudit($rejectOutOrderInput: RejectOutOrderInput) {
  rejectOutOrderAudit(rejectOutOrderInput: $rejectOutOrderInput)
}

# 去出库
mutation confirmOutOrder($confirmOutOrderInput: ConfirmOutOrderInput) {
  confirmOutOrder(confirmOutOrderInput: $confirmOutOrderInput)
}

# 商品批次
query stockBatches($stockBatchQueryInput: StockBatchQueryInput) {
  stockBatches(stockBatchQueryInput: $stockBatchQueryInput) {
    batchId
    batchCode
    unitQuantity
    totalQuantity
    unitTypeName
    totalTypeName
    unitType
    totalType
    createTime
    conversion
  }
}

# 完成出库
mutation finishOutOrder($finishOutOrderInput: FinishOutOrderInput) {
  finishOutOrder(finishOutOrderInput: $finishOutOrderInput)
}

# 其他出库: 详情
query otherOutOrderDetail($input: OtherOutOrderDetailInput) {
  otherOutOrderDetail(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    createBy {
      phoneNum
      userId
      userName
    }
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    supplier {
      supplierId
      supplierName
    }
    warehouse {
      warehouseId
      warehouseName
    }
    wmsMarkList {
      appId
      businessType
      labelContent
      markId
      tenantId
    }
    billId
    commodityList {
      commoditySku {
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
      }
      priceType {
        unitId
        unitName
      }
      stockBatchInfo {
        customerBelongInfo {
          customerId
          customerName
          customerType
        }
        batchCode
        batchId
        createTime
        totalQuantity
        unitQuantity
      }
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
      inBoundTotalQuantity
      inBoundUnitQuantity
      outOrderId
      outOrderItemId
      salePrice
      totalQuantity
      unitQuantity
      unitTotalPrice
    }
    commodityTypeId
    commodityTypeName
    createTime
    errorDescription
    outOrderCode
    outOrderDescription
    outOrderId
    outOrderStatus
    outOrderStatusName
    outOrderType
    outOrderTypeName
    outStockRecordCount
  }
}

# 其他出库: 取消其他出库单
mutation cancelOtherOutOrder($input: CancelOtherOutOrderInput) {
  cancelOtherOutOrder(input: $input)
}

# 其他出库: 提交其他出库单
mutation submitOtherOutOrder($input: SubmitOtherOutOrderInput) {
  submitOtherOutOrder(input: $input)
}
