# 入库审核: 查询待审核入库订单列表(入库审核)
# 查询待审核入库订单列表(入库审核)
query pageAuditInOrder($commodityType: Int!, $page: Page) {
  pageAuditInOrder(commodityType: $commodityType, page: $page) {
    records {
      inOrderId
      inOrderTypeId
      inOrderTypeName
      inOrderCode
      taskId
      taskCode
      commodityTypeId
      commodityTypeName
      customerTypeId
      customerTypeName
      customerId
      customerName
      inOrderStatus
      inOrderStatusName
      warehouseId
      warehouseName
      supplierId
      supplierName
      transferId
      transferType
      transferOrganizationId
      transferOrganizationName
      createUserName
      createTime
      createUserPhone
      inOrderDescription
      commodities {
        inOrderItemId
        commodityId
        commodityName
        commoditySkuId
        commoditySpecOptionId
        skuTextDescription
        unitQuantity
        unitTypeName
        unitType
        totalQuantity
        totalTypeName
        unitPrice
        unitPriceType
        unitPriceTypeName
        unitTotalPrice
        waitUnitQuantity
        waitTotalQuantity
        completeInStock
        conversion
        pricePosition
        grossUnitQuantity
        batchId
        inBoundTotalQuantity
        inBoundUnitQuantity
        inBoundGrossUnitQuantity
        skuDetail {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        productPickingQuantity {
          totalQuantity
          unitQuantity
        }
      }
      totalPrice
      deliveryFee
      customerDistributionName
      sourceAppId
      targetAppId
      belongOrg {
        orgId
        orgName
      }
      isExceptional
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 入库审核: 查询订单详情(入库审核)
query getAuditDetail($inOrderDetailInput: InOrderDetailInput) {
  # 查询订单详情(入库审核)
  getAuditDetail(inOrderDetailInput: $inOrderDetailInput) {
    inOrderId
    inOrderTypeId
    inOrderTypeName
    inOrderCode
    taskId
    taskCode
    commodityTypeId
    commodityTypeName
    customerTypeId
    customerTypeName
    customerId
    customerName
    inOrderStatus
    inOrderStatusName
    warehouseId
    warehouseName
    supplierId
    supplierName
    transferId
    transferType
    transferOrganizationId
    transferOrganizationName
    createUserName
    createTime
    createUserPhone
    inOrderDescription
    commodities {
      reason
      inOrderItemId
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitTypeName
      unitType
      totalQuantity
      totalTypeName
      unitPrice
      unitPriceType
      unitPriceTypeName
      unitTotalPrice
      waitUnitQuantity
      waitTotalQuantity
      completeInStock
      conversion
      pricePosition
      grossUnitQuantity
      batchId
      inBoundTotalQuantity
      inBoundUnitQuantity
      inBoundGrossUnitQuantity
      skuDetail {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      productPickingQuantity {
        totalQuantity
        unitQuantity
      }
    }
    totalPrice
    deliveryFee
    customerDistributionName
    sourceAppId
    targetAppId
    belongOrg {
      orgId
      orgName
    }
    isExceptional
    netWeightExceptionRatio
  }
}

# 入库记录数量
query countInbounded($inOrderDetailInput: InOrderDetailInput) {
  countInbounded(inOrderDetailInput: $inOrderDetailInput)
}

# 入库记录日志
query purchaseInOrderLog($inOrderId: ID!) {
  purchaseInOrderLog(inOrderId: $inOrderId) {
    inOrderLogList {
      inOrderLogId
      inOrderId
      inOrderLogType
      inOrderLogTypeText
      inOrderLogDescription
      createTime
      createBy
      createUserName
    }
  }
}

# 入库详情数据（详情+入库记录数量）
query stockInAuditDetail($inOrderDetailInput: InOrderDetailInput) {
  # 查询订单详情(入库审核)
  getAuditDetail(inOrderDetailInput: $inOrderDetailInput) {
    inOrderId
    inOrderTypeId
    inOrderTypeName
    inOrderCode
    taskId
    taskCode
    commodityTypeId
    commodityTypeName
    customerTypeId
    customerTypeName
    customerId
    customerName
    inOrderStatus
    inOrderStatusName
    warehouseId
    warehouseName
    supplierId
    supplierName
    transferId
    transferType
    transferOrganizationId
    transferOrganizationName
    createUserName
    createTime
    createUserPhone
    inOrderDescription
    commodities {
      reason
      inOrderItemId
      commodityId
      commodityName
      commoditySkuId
      commoditySpecOptionId
      skuTextDescription
      unitQuantity
      unitTypeName
      unitType
      totalQuantity
      totalTypeName
      unitPrice
      unitPriceType
      unitPriceTypeName
      unitTotalPrice
      waitUnitQuantity
      waitTotalQuantity
      completeInStock
      conversion
      pricePosition
      grossUnitQuantity
      batchId
      inBoundTotalQuantity
      inBoundUnitQuantity
      inBoundGrossUnitQuantity
      skuDetail {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      productPickingQuantity {
        totalQuantity
        unitQuantity
      }
    }
    totalPrice
    deliveryFee
    customerDistributionName
    sourceAppId
    targetAppId
    belongOrg {
      orgId
      orgName
    }
    isExceptional
    netWeightExceptionRatio
  }
  countInbounded(inOrderDetailInput: $inOrderDetailInput)
}

# 入库记录
query inboundRecord($inOrderDetailInput: InOrderDetailInput) {
  getAuditDetail(inOrderDetailInput: $inOrderDetailInput) {
    inOrderTypeId
  }
  inboundRecord(inOrderDetailInput: $inOrderDetailInput) {
    commodityTypeId
    toBeInBoundList {
      commodityName
      skuTextDescription
      unitQuantity
      unitTypeName
      grossUnitQuantity
      totalQuantity
      totalTypeName
      conversion
      waitUnitQuantity
      waitTotalQuantity
      pricePosition
    }
    inboundRecordList {
      inboundRecordItems {
        commodityName
        skuTextDescription
        unitQuantity
        unitTypeName
        grossUnitQuantity
        totalQuantity
        totalTypeName
        unitPrice
        unitPriceTypeName
        conversion
        totalPrice
        batchCode
      }
      totalPrice
      inOrderCode
      createUserName
      inboundTime
      remark
      deliveryFee
    }
  }
}

# 驳回订单
mutation rejectedInOrderAudit($rejectedInput: RejectedInput) {
  rejectedInOrderAudit(rejectedInput: $rejectedInput)
}

# 驳回订单 原料采购、辅料采购
mutation rejectPurchaseOrderAudit($rejectedInput: RejectedInput) {
  rejectPurchaseOrderAudit(rejectedInput: $rejectedInput)
}

# 入库审核: 确认入库 返回订单状态
mutation confirmInbound($confirmInput: ConfirmInput) {
  confirmInbound(confirmInput: $confirmInput)
}

# 去入库 原料采购、辅料采购
mutation confirmPurchaseInBound($purchaseConfirmInput: PurchaseConfirmInput) {
  confirmPurchaseInBound(purchaseConfirmInput: $purchaseConfirmInput)
}

# 完成入库
mutation finishInbound($inOrderId: ID!) {
  finishInbound(inOrderId: $inOrderId)
}

# 完成入库 原料采购、辅料采购
mutation finishPurchaseOrderInBound($inOrderId: ID!) {
  finishPurchaseOrderInBound(inOrderId: $inOrderId)
}

# 查询其他入库订单
query pageOtherInOrder(
  $page: Page
  $pageOtherInOrderInput: PageOtherInOrderInput
) {
  pageOtherInOrder(page: $page, pageOtherInOrderInput: $pageOtherInOrderInput) {
    records {
      inOrderId
      inOrderTypeId
      inOrderTypeName
      inOrderCode
      commodityTypeId
      commodityTypeName
      customerTypeId
      customerTypeName
      customerId
      customerName
      inOrderStatus
      inOrderStatusName
      warehouseId
      warehouseName
      supplierId
      supplierName
      createUserName
      createTime
      inOrderDescription
      errorDescription
      totalPrice
      commodities {
        unitQuantity
        unitType
        unitTypeName
        totalQuantity
        totalType
        totalTypeName
        unitPrice
        unitPriceType
        unitPriceTypeName
        totalPrice
        commoditySku {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
      }
      createBy
      belongOrg {
        orgId
        orgName
      }
      wmsMarkList {
        appId
        businessType
        labelContent
        markId
        tenantId
      }
      inStockRecordCount
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 新增其他入库
mutation createOtherInOrder($createOtherInOrderInput: CreateOtherInOrderInput) {
  createOtherInOrder(createOtherInOrderInput: $createOtherInOrderInput)
}

# 修改其他入库
mutation modifyOtherInOrder($modifyOtherInOrderInput: ModifyOtherInOrderInput) {
  modifyOtherInOrder(modifyOtherInOrderInput: $modifyOtherInOrderInput)
}

# 提交其他入库
mutation submitOtherInOrder($inOrderId: ID!) {
  submitOtherInOrder(inOrderId: $inOrderId)
}

# 取消其他入库
mutation cancelOtherInOrder($cancelOtherInOrderInput: CancelOtherInOrderInput) {
  cancelOtherInOrder(cancelOtherInOrderInput: $cancelOtherInOrderInput)
}

# 调拨入库:修改入库仓库
mutation updateTransferInOrderWarehouse(
  $updateTransferInOrderWarehouseInput: UpdateTransferInOrderWarehouseInput
) {
  updateTransferInOrderWarehouse(
    updateTransferInOrderWarehouseInput: $updateTransferInOrderWarehouseInput
  )
}

# 待入库库存: 查询列表分页
query omsPurchasePage($input: OmsPurchasePageInput, $page: Page) {
  omsPurchasePage(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      commodityItemsList {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        id
        index
        price
        priceType {
          unitId
          unitName
        }
        totalQuantity
        totalType {
          unitId
          unitName
        }
        unitQuantity
        unitType {
          unitId
          unitName
        }
      }
      commodityType
      commodityTypeDesc
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      customer {
        customerId
        customerName
        customerType
      }
      id
      runCode
      status
      statusName
      submitTime
      submitUser {
        phoneNum
        userId
        userName
      }
      transportInfo {
        cabinetBatchCode
        cabinetCode
        carNo
        trailerNo
        matchSourceName
        purchaseCode
      }
      type
      typeName
      supplierList {
        supplierId
        supplierName
      }
      code
      subType
      subTypeName
      isExceptional
    }
    totalRecords
  }
}

# 待入库库存: 查询详情
query omsPurchaseDetail($input: OmsPurchaseDetailInput) {
  omsPurchaseDetail(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    commodityItemsList {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      id
      index
      price
      priceType {
        unitId
        unitName
      }
      totalQuantity
      totalType {
        unitId
        unitName
      }
      unitQuantity
      unitType {
        unitId
        unitName
      }
      markList
      runCode
    }
    commodityType
    commodityTypeDesc
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    customer {
      customerId
      customerName
      customerType
    }
    id
    runCode
    status
    statusName
    submitTime
    submitUser {
      phoneNum
      userId
      userName
    }
    transportInfo {
      cabinetBatchCode
      cabinetCode
      carNo
      trailerNo
      matchSourceName
      purchaseCode
    }
    type
    typeName
    supplierList {
      supplierId
      supplierName
    }
    code
    subType
    subTypeName
    isExceptional
    netWeightExceptionRatio
  }
}

# 待入库库存: 查询状态统计
query omsPurchaseStatus {
  omsPurchaseStatus {
    count
    status
  }
}

# 待入库库存: 确认入库
mutation confirmOmsPurchase($input: ConfirmOmsPurchaseInput) {
  confirmOmsPurchase(input: $input)
}

query countInOrderAudit {
  countInOrderAudit {
    damageProduct
    defectiveProduct
    finishedProduct
    rawMaterial
    returnProduct
    semiFinishedProduct
    subMaterial
    turnoverBasket
  }
}

# 代卖退回入库审核: 修改仓库
mutation updateOrderTransferInOrderWarehouse(
  $input: PitayaUpdateWarehouseInput
) {
  updateOrderTransferInOrderWarehouse(input: $input)
}

# 待入库库存: 异常审核通过
mutation passOmsPurchase($input: PassOmsPurchaseInput) {
  passOmsPurchase(input: $input)
}

# 其他入库: 其他入库订单详情
query otherInOrderDetail($input: OtherInOrderDetailInput) {
  otherInOrderDetail(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    supplierId
    supplierName
    billId
    commodities {
      totalPrice
      totalQuantity
      totalType
      totalTypeName
      unitPrice
      unitPriceType
      unitPriceTypeName
      unitQuantity
      unitType
      unitTypeName
      commoditySku {
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
      }
    }
    commodityTypeId
    commodityTypeName
    createBy
    createTime
    createUserName
    customerId
    customerName
    customerTypeId
    customerTypeName
    errorDescription
    inOrderCode
    inOrderDescription
    inOrderId
    inOrderStatus
    inOrderStatusName
    inOrderTypeId
    inOrderTypeName
    totalPrice
    warehouseId
    warehouseName
    wmsMarkList {
      appId
      businessType
      labelContent
      markId
      tenantId
    }
    inStockRecordCount
  }
}

# 获取标签列表
query listWmsMark($input: ListWmsMarkInput) {
  listWmsMark(input: $input) {
    businessType
    labelContent
    markId
  }
}

# 其他入库: 入库记录查询
query otherInOrderRecord($input: OtherInOrderRecordInput) {
  otherInOrderRecord(input: $input) {
    commodityTypeId
    inApplyCode
    inboundRecordList {
      createUserName
      deliveryFee
      inOrderCode
      inboundRecordItems {
        commodityName
        commoditySkuId
        skuTextDescription
        batchCode
        batchId
        conversion
        grossUnitQuantity
        totalPrice
        totalQuantity
        totalType
        totalTypeName
        unitPrice
        unitPriceType
        unitPriceTypeName
        unitQuantity
        unitType
        unitTypeName
      }
      inboundTime
      remark
      totalPrice
      userId
    }
    toBeInBoundList {
      commodityName
      commoditySkuId
      conversion
      grossUnitQuantity
      pricePosition
      skuTextDescription
      totalQuantity
      totalType
      totalTypeName
      unitQuantity
      unitType
      unitTypeName
      waitTotalQuantity
      waitUnitQuantity
    }
  }
}
