# 配送单: 获取配送单列表详情
query commodityModificationDetail(
  $deliveryOrderDetailQueryInput: DeliveryOrderDetailQueryInput
  $saleGoodsListQueryInput: SaleGoodsListQueryInput
) {
  # 配送单: 获取配送单列表详情
  deliveryOrderDetail(
    deliveryOrderDetailQueryInput: $deliveryOrderDetailQueryInput
  ) {
    orderId
    warehouse {
      warehouseId
      warehouseName
    }
    belongInfo {
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
    }
    businessUserName
    carNum
    carType
    deliveryType
    deliveryTypeDesc
    driverContact
    driverName
    orderCode
    orderStatus
    orderStatusDesc
    org {
      orgId
      orgName
    }
    saleOrderDate
    createBy {
      userId
      userName
      phoneNum
    }
    createTime
    deliveryOrderFee {
      amount
      billId
      feeItemId
      feeType
      feeTypeDesc
      payMode
      payModeDesc
      remark
      supplier {
        supplierId
        supplierName
      }
    }
    deliveryOrderItem {
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
      itemId
      orderId
      saleOrderId
      saleOrderCode
      commodityDetail {
        itemId
        sku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        totalQuantity
        unitQuantity
        bakTotalQuantity
        bakUnitQuantity
        outTotalQuantity
        outUnitQuantity
        bakOutTotalQuantity
        bakOutUnitQuantity
        actualTotalQuantity
        actualUnitQuantity
        differenceReason
        saleOrderItemId
        deliveryOutItemId
        deliverableTotalQuantity
        deliverableUnitQuantity
        deliveredTotalQuantity
        deliveredUnitQuantity
      }
      outOrderId
      outOrderQuantity
      orderType
      commodityTypeId
      commodityTypeName
    }
    belongOrg {
      orgId
      orgName
    }
    photos
  }
  # 配送单: 选择配送货物
  querySaleGoodsList(saleGoodsListQueryInput: $saleGoodsListQueryInput) {
    customerAddressInfo {
      customerId
      customerName
      customerType
      deliveryName
    }
    saleOrderId
    saleOrderCode
    saleOrderDate
    saleGoodsItemInfo {
      commodityDetail {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      totalQuantity
      unitQuantity
      deliverableTotalQuantity
      deliverableUnitQuantity
      saleOrderItemId
      needShow
    }
    orderType
    commodityTypeId
    commodityTypeName
    outOrderId
    outOrderStatus
  }
}
