# 配送费用单: 配送费用单列表
query pageDeliveryBill(
  $page: Page
  $pageDeliveryBillInput: PageDeliveryBillInput
) {
  pageDeliveryBill(page: $page, pageDeliveryBillInput: $pageDeliveryBillInput) {
    pageCurrent
    pageSize
    records {
      belongInfo {
        customerAddressInfo {
          customerId
          customerName
          customerType
          deliveryName
        }
      }
      belongOrg {
        orgId
        orgName
      }
      billCode
      billId
      billStatus
      billStatusDesc
      businessUserName
      carNum
      carType
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      deliveryDate
      deliveryOrderType
      deliveryType
      deliveryTypeDesc
      driverContact
      driverName
      feeItems {
        amount
        billId
        feeItemId
        feeTypeDesc
        feeTypeEnum
        payModeDesc
        payModeEnum
        remark
        supplier {
          supplierId
          supplierName
        }
      }
      items {
        billId
        commodities {
          actualTotalQuantity
          actualUnitQuantity
          applyTotalQuantity
          applyUnitQuantity
          bakApplyTotalQuantity
          bakApplyUnitQuantity
          bakTotalQuantity
          bakUnitQuantity
          differenceReason
          itemId
          sku {
            categoryId
            categoryName
            commodityId
            commodityName
            commoditySkuId
            commoditySkuName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
          }
          totalQuantity
          unitQuantity
        }
        customerAddressInfo {
          customerId
          customerName
          customerType
          deliveryName
        }
        saleOrderCode
        saleOrderId
      }
      jointVentureBillItem {
        actualTotalQuantity
        actualUnitQuantity
        billId
        differenceReason
        itemId
        sku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        totalQuantity
        unitQuantity
      }
      logs {
        billId
        createBy {
          phoneNum
          userId
          userName
        }
        createTime
        logId
        logType
        logTypeDesc
        remark
      }
      manualCode
      orderCode
      orderId
      org {
        orgId
        orgName
      }
      photos
      statusNote
      warehouse {
        warehouseId
        warehouseName
      }
    }
    totalRecords
  }
}

# 配送费用单: 配送费用单详情
query getDeliveryBill($getDeliveryBillInput: GetDeliveryBillInput) {
  getDeliveryBill(getDeliveryBillInput: $getDeliveryBillInput) {
    belongInfo {
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
    }
    belongOrg {
      orgId
      orgName
    }
    billCode
    billId
    billStatus
    billStatusDesc
    businessUserName
    carNum
    carType
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    deliveryDate
    deliveryOrderType
    deliveryType
    deliveryTypeDesc
    driverContact
    driverName
    feeItems {
      amount
      billId
      feeItemId
      feeTypeDesc
      feeTypeEnum
      payModeDesc
      payModeEnum
      remark
      supplier {
        supplierId
        supplierName
      }
    }
    items {
      billId
      commodities {
        actualTotalQuantity
        actualUnitQuantity
        applyTotalQuantity
        applyUnitQuantity
        bakApplyTotalQuantity
        bakApplyUnitQuantity
        bakTotalQuantity
        bakUnitQuantity
        differenceReason
        itemId
        sku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        totalQuantity
        unitQuantity
      }
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
      saleOrderCode
      saleOrderId
    }
    jointVentureBillItem {
      actualTotalQuantity
      actualUnitQuantity
      billId
      differenceReason
      itemId
      sku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      totalQuantity
      unitQuantity
    }
    logs {
      billId
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      logId
      logType
      logTypeDesc
      remark
    }
    manualCode
    orderCode
    orderId
    org {
      orgId
      orgName
    }
    photos
    statusNote
    warehouse {
      warehouseId
      warehouseName
    }
  }
}

# 配送费用单状态查询
query deliveryBillStatusCount(
  $deliveryOrderStatusCountInput: DeliveryOrderStatusCountInput
) {
  deliveryBillStatusCount(
    deliveryOrderStatusCountInput: $deliveryOrderStatusCountInput
  ) {
    unSubmit
    unAudit
  }
}

# 配送方式下拉
query deliveryBillDeliveryMethod {
  deliveryBillDeliveryMethod {
    label
    value
  }
}

# 配送费用类型下拉
query deliveryBillType {
  deliveryBillType {
    label
    value
  }
}

# 配送费用结算方式下拉
query deliveryBillPayMode {
  deliveryBillPayMode {
    label
    value
  }
}

# 修改配送费用
mutation updateDeliveryBillFee(
  $updateDeliveryBillFeeInput: UpdateDeliveryBillFeeInput
) {
  updateDeliveryBillFee(updateDeliveryBillFeeInput: $updateDeliveryBillFeeInput)
}

# 提交配送费用
mutation submitDeliveryBillFee(
  $updateDeliveryBillStatusInput: UpdateDeliveryBillStatusInput
) {
  submitDeliveryBillFee(
    updateDeliveryBillStatusInput: $updateDeliveryBillStatusInput
  )
}

# 驳回配送费用
mutation rejectDeliveryBillFee(
  $updateDeliveryBillStatusInput: UpdateDeliveryBillStatusInput
) {
  rejectDeliveryBillFee(
    updateDeliveryBillStatusInput: $updateDeliveryBillStatusInput
  )
}

# 审核配送费用
mutation auditDeliveryBillFee(
  $updateDeliveryBillStatusInput: UpdateDeliveryBillStatusInput
) {
  auditDeliveryBillFee(
    updateDeliveryBillStatusInput: $updateDeliveryBillStatusInput
  )
}

# 配送费用单: 填写手工单号
mutation saveManualCode($saveManualCodeInput: SaveManualCodeInput) {
  saveManualCode(saveManualCodeInput: $saveManualCodeInput)
}
