# 配送单: 获取配送单列表
query pageDeliveryOrder(
  $deliveryOrderQueryInput: DeliveryOrderQueryInput
  $page: Page
) {
  pageDeliveryOrder(
    deliveryOrderQueryInput: $deliveryOrderQueryInput
    page: $page
  ) {
    records {
      orderId
      warehouse {
        warehouseId
        warehouseName
      }
      belongInfo {
        customerAddressInfo {
          customerId
          customerName
          customerType
          deliveryName
        }
      }
      businessUserName
      carNum
      carType
      deliveryType
      deliveryTypeDesc
      driverContact
      driverName
      orderCode
      orderStatus
      orderStatusDesc
      org {
        orgId
        orgName
      }
      saleOrderDate
      createBy {
        userId
        userName
        phoneNum
      }
      createTime
      deliveryOrderFee {
        amount
        billId
        feeItemId
        feeType
        feeTypeDesc
        payMode
        payModeDesc
        remark
        supplier {
          supplierId
          supplierName
        }
      }
      deliveryOrderItem {
        customerAddressInfo {
          customerId
          customerName
          customerType
          deliveryName
        }
        itemId
        orderId
        saleOrderId
        saleOrderCode
        commodityDetail {
          itemId
          sku {
            commoditySkuId
            commoditySkuName
            commodityId
            commodityName
            commoditySpecOptionId
            commoditySpecOptionName
            conversion
            totalType {
              unitId
              unitName
            }
            unitType {
              unitId
              unitName
            }
            categoryId
            categoryName
          }
          totalQuantity
          unitQuantity
          bakTotalQuantity
          bakUnitQuantity
          outTotalQuantity
          outUnitQuantity
          bakOutTotalQuantity
          bakOutUnitQuantity
          actualTotalQuantity
          actualUnitQuantity
          differenceReason
          saleOrderItemId
          deliveryOutItemId
          deliverableTotalQuantity
          deliverableUnitQuantity
          deliveredTotalQuantity
          deliveredUnitQuantity
          returnTotalQuantity
          returnUnitQuantity
        }
        outOrderId
        outOrderQuantity
        orderType
        commodityTypeId
        commodityTypeName
      }
      belongOrg {
        orgId
        orgName
      }
      photos
      deliveryOrderTypeDesc
      deliveryDate
      commodityTypeId
      commodityTypeDesc
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 配送单: 获取配送单列表详情
query deliveryOrderDetail(
  $deliveryOrderDetailQueryInput: DeliveryOrderDetailQueryInput
) {
  deliveryOrderDetail(
    deliveryOrderDetailQueryInput: $deliveryOrderDetailQueryInput
  ) {
    belongInfo {
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
    }
    belongOrg {
      orgId
      orgName
    }
    businessUserName
    carNum
    carType
    commodityTypeDesc
    commodityTypeId
    completeTime
    completeTimeUpdateSign
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    deliveryDate
    deliveryOrderFee {
      amount
      billId
      feeItemId
      feeType
      feeTypeDesc
      payMode
      payModeDesc
      remark
      supplier {
        supplierId
        supplierName
      }
    }
    deliveryOrderItem {
      commodityDetail {
        actualTotalQuantity
        actualUnitQuantity
        bakOutTotalQuantity
        bakOutUnitQuantity
        bakTotalQuantity
        bakUnitQuantity
        deliverableTotalQuantity
        deliverableUnitQuantity
        deliveredTotalQuantity
        deliveredUnitQuantity
        deliveryOutItemId
        differenceReason
        itemId
        outTotalQuantity
        outUnitQuantity
        returnTotalQuantity
        returnUnitQuantity
        saleOrderItemId
        sku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        totalQuantity
        unitQuantity
      }
      commodityTypeId
      commodityTypeName
      customerAddressInfo {
        customerId
        customerName
        customerType
        deliveryName
      }
      itemId
      orderId
      orderType
      outOrderId
      outOrderQuantity
      saleOrderCode
      saleOrderId
    }
    deliveryOrderTypeDesc
    deliveryType
    deliveryTypeDesc
    driverContact
    driverName
    jointVentureOrderItem {
      batchCode
      batchId
      deliveryOutItemId
      itemId
      orderId
      outTotalQuantity
      outUnitQuantity
      sku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      stockQuantity {
        totalQuantity
        unitQuantity
      }
      totalQuantity
      unitQuantity
    }
    orderCode
    orderId
    orderStatus
    orderStatusDesc
    org {
      orgId
      orgName
    }
    outOrderId
    outOrderQuantity
    outOrderType
    outOrderTypeDesc
    photos
    saleOrderDate
    statusNote
    warehouse {
      warehouseId
      warehouseName
    }
  }
}

# 获取配送单列表统计数据
query deliveryOrderStatusCount(
  $deliveryOrderStatusCountInput: DeliveryOrderStatusCountInput
) {
  deliveryOrderStatusCount(
    deliveryOrderStatusCountInput: $deliveryOrderStatusCountInput
  ) {
    unSubmit
    unOutStock
    unReceipt
  }
}

# 选择配送货物
query querySaleGoodsList($saleGoodsListQueryInput: SaleGoodsListQueryInput) {
  querySaleGoodsList(saleGoodsListQueryInput: $saleGoodsListQueryInput) {
    customerAddressInfo {
      customerId
      customerName
      customerType
      deliveryName
    }
    saleOrderId
    saleOrderCode
    saleOrderDate
    saleGoodsItemInfo {
      commodityDetail {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      totalQuantity
      unitQuantity
      deliverableTotalQuantity
      deliverableUnitQuantity
      saleOrderItemId
      needShow
    }
    orderType
    commodityTypeId
    commodityTypeName
    outOrderId
    outOrderStatus
  }
}

# 选择配送信息列表
query listDeliveryInfo {
  listDeliveryInfo {
    createBy {
      userId
      userName
      phoneNum
    }
    createTime
    updateBy {
      userId
      userName
      phoneNum
    }
    updateTime
    id
    driverName
    driverContact
    carType
    carNum
    deliveryType
    deliveryTypeDesc
    businessUserName
    infoName
  }
}

# 保存
mutation addDeliveryOrder($addDeliveryOrderInput: AddDeliveryOrderInput) {
  addDeliveryOrder(addDeliveryOrderInput: $addDeliveryOrderInput)
}

# 修改
mutation updateDeliveryOrder(
  $updateDeliveryOrderInput: UpdateDeliveryOrderInput
) {
  updateDeliveryOrder(updateDeliveryOrderInput: $updateDeliveryOrderInput)
}

# 提交配送单
mutation submitDeliveryOrder(
  $submitDeliveryOrderInput: SubmitDeliveryOrderInput
) {
  submitDeliveryOrder(submitDeliveryOrderInput: $submitDeliveryOrderInput)
}

# 取消
mutation cancelDeliveryOrder(
  $cancelDeliveryOrderInput: CancelDeliveryOrderInput
) {
  cancelDeliveryOrder(cancelDeliveryOrderInput: $cancelDeliveryOrderInput)
}

# 完成收货
mutation completeDeliveryOrder(
  $completeDeliveryOrderInput: CompleteDeliveryOrderInput
) {
  completeDeliveryOrder(completeDeliveryOrderInput: $completeDeliveryOrderInput)
}

# 修改配送出库货物
mutation updateDeliveryItem($updateDeliveryItemInput: UpdateDeliveryItemInput) {
  updateDeliveryItem(updateDeliveryItemInput: $updateDeliveryItemInput)
}

# 新增或修改配送信息
mutation saveOrUpdateDeliveryInfo(
  $saveOrUpdateDeliveryInfoInput: SaveOrUpdateDeliveryInfoInput
) {
  saveOrUpdateDeliveryInfo(
    saveOrUpdateDeliveryInfoInput: $saveOrUpdateDeliveryInfoInput
  )
}

# 删除配送信息
mutation removeDeliveryInfo($removeDeliveryInfoInput: RemoveDeliveryInfoInput) {
  removeDeliveryInfo(removeDeliveryInfoInput: $removeDeliveryInfoInput)
}

mutation rollbackDeliveryOrder(
  $rollbackDeliveryOrderInput: RollbackDeliveryOrderInput
) {
  rollbackDeliveryOrder(rollbackDeliveryOrderInput: $rollbackDeliveryOrderInput)
}
