query pageSaleIncomeOrder($pageSaleIncomeOrderInput: PageSaleIncomeOrderInput, $page: Page) {
  pageSaleIncomeOrder(
    pageSaleIncomeOrderInput: $pageSaleIncomeOrderInput
    page: $page
  ) {
    records {
      incomeId
      incomeStatus
      incomeStatusName
      incomeCode
      sourceId
      sourceType
      sourceTypeName
      warehouse {
        warehouseId
        warehouseName
      }
      remark
      rejectReason
      user {
        userId
        userName
        phoneNum
      }
      customer {
        customerId
        customerName
        customerType
      }
      createTime
      commoditiesList {
        incomeItemId
        incomeId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        commodityName
        unitQuantity
        unitType {
          unitId
          unitName
        }
        saleMoney
        photosList
        outOrderItemId
        salePrice
        remark
        totalQuantity
        totalType {
          unitId
          unitName
        }
        batchId
        batchCode
        totalSalePrice
        priceType {
          unitId
          unitName
        }
      }
      saleCostOrderId
      totalAmount
      commodityTypeName
      payMode
      belongOrg {
        orgId
        orgName
      }
      saleTime
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

# 销售收入单: 查询详情
query getSaleIncomeOrder($input: GetSaleIncomeInput) {
  getSaleIncomeOrder(input: $input) {
    incomeId
    incomeStatus
    incomeStatusName
    incomeCode
    sourceId
    sourceType
    sourceTypeName
    warehouse {
      warehouseId
      warehouseName
    }
    remark
    rejectReason
    user {
      userId
      userName
      phoneNum
    }
    customer {
      customerId
      customerName
      customerType
    }
    createTime
    commoditiesList {
      incomeItemId
      incomeId
      commoditySku {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      commodityName
      unitQuantity
      unitType {
        unitId
        unitName
      }
      saleMoney
      photosList
      outOrderItemId
      salePrice
      remark
      totalQuantity
      totalType {
        unitId
        unitName
      }
      batchId
      batchCode
      totalSalePrice
      priceType {
        unitId
        unitName
      }
      goodsUnitQuantity
      goodsTotalQuantity
      commodityBatchInfoList {
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        batchCode
        batchId
        goodsTotalQuantity
        goodsUnitQuantity
        incomeItemId
        outOrderItemId
        salePrice
        totalQuantity
        totalSalePrice
        unitQuantity
      }
    }
    originalSaleCommodityPayload {
      outOrderItemId
      commoditySku {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      batchId
      batchCode
      salePrice
      salePriceType {
        unitId
        unitName
      }
      totalQuantity
      totalType {
        unitId
        unitName
      }
      unitQuantity
      unitType {
        unitId
        unitName
      }
      saleTotalPrice
      stockQuantity {
        unitQuantity
        totalQuantity
      }
      actualQuantity {
        actualTotalQuantity
        actualUnitQuantity
        actualSalePrice
        actualSaleTotalPrice
        outOrderItemId
      }
      outOrderId
    }
    saleCostOrderItems {
      saleCostOrderItemId
      saleCostOrderId
      outOrderItemId
      commodity {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      packagingFee
      materialFee
    }
    logs {
      incomeLogId
      incomeId
      type
      typeText
      remark
      createTime
      user {
        userId
        userName
        phoneNum
      }
    }
    saleCostOrderId
    functionalField {
      saleTotalPrice
      saleTotalCost
    }
    totalAmount
    commodityTypeName
    payMode
    belongOrg {
      orgId
      orgName
    }
    saleTime
  }
}

query saleIncomeOrderStatistic {
  saleIncomeOrderStatistic {
    orderCount
    auditCount
  }
}

query saleIncomeOrderStatusStatistic($saleIncomeOrderStatusStatisticInput: SaleIncomeOrderStatusStatisticInput) {
  saleIncomeOrderStatusStatistic(
    saleIncomeOrderStatusStatisticInput: $saleIncomeOrderStatusStatisticInput
  ) {
    waitSubmit
    financialReject
    unBusinessAudit
    unBackOfficeAudit
    unFinancialAudit
    finished
    businessReject
  }
}

mutation submitSaleIncomeOrder($submitSaleIncomeOrderInput: SubmitSaleIncomeOrderInput) {
  submitSaleIncomeOrder(submitSaleIncomeOrderInput: $submitSaleIncomeOrderInput)
}

mutation auditSaleIncomeOrder($auditSaleIncomeOrderInput: AuditSaleIncomeOrderInput) {
  auditSaleIncomeOrder(auditSaleIncomeOrderInput: $auditSaleIncomeOrderInput)
}

mutation rejectSaleIncomeOrder($rejectSaleIncomeOrderInput: RejectSaleIncomeOrderInput) {
  rejectSaleIncomeOrder(rejectSaleIncomeOrderInput: $rejectSaleIncomeOrderInput)
}

# 销售收入单: 内勤审核接口 2.7新增
mutation submitSaleIncomeOrderWeb($incomeId: ID) {
  submitSaleIncomeOrderWeb(incomeId: $incomeId)
}