# 国产货采购:订单状态数量统计
query countDomesticPurchaseStatus($countDomesticPurchaseStatusFilter: CountDomesticPurchaseStatusFilter!) {
  countDomesticPurchaseStatus(
    countDomesticPurchaseStatusFilter: $countDomesticPurchaseStatusFilter
  ) {
    countDomesticPurchaseStatus {
      count
      status
    }
    countExpandOrderStatus {
      count
      status
    }
  }
}

# 国产货采购:采购订单详情
query detailDomesticPurchaseOrder($domesticPurchaseId: ID!) {
  detailDomesticPurchaseOrder(domesticPurchaseId: $domesticPurchaseId) {
    amount
    belongOrg {
      orgId
      orgName
    }
    code
    commodityType
    commodityTypeDesc
    createTime
    customer {
      customerId
      customerName
      customerType
    }
    expandOrderList {
      code
      commodityItems {
        actualTotalQuantity
        actualUnitQuantity
        amount
        canReturnTotalQuantity
        canReturnUnitQuantity
        commodity {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        expandOrderTypeEnum
        id
        price
        priceType {
          unitId
          unitName
        }
        totalQuantity
        unitQuantity
        index
        batchId
        sourceBatchId
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      id
      runCode
      status
      statusDesc
      type
      typeDesc
      totalAmount
    }
    id
    matchingSource {
      carNo
      departureDate
      matchDate
      matchSource
      matchSourceName
      runCode
      trailerNo
    }
    purchaseDate
    runCode
    status
    statusDesc
    subType
    subTypeDesc
    supplier {
      supplierId
      supplierName
    }
    warehouse {
      warehouseId
      warehouseName
    }
    commodityItems {
      actualTotalQuantity
      actualUnitQuantity
      amount
      batchCode
      batchId
      canApplyStock
      canReturnTotalQuantity
      canReturnUnitQuantity
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      deductTotalQuantity
      deductUnitQuantity
      expandOrderTypeEnum
      id
      index
      orderId
      orderType
      price
      priceType {
        unitId
        unitName
      }
      returnTotalQuantity
      returnUnitQuantity
      runCode
      sourceBatchId
      stockBatch {
        batchCode
        batchId
        customerBelongInfo {
          customerId
          customerName
          customerType
        }
        totalQuantity
        unitQuantity
      }
      totalQuantity
      totalType {
        unitId
        unitName
      }
      unitQuantity
      unitType {
        unitId
        unitName
      }
      warehouseId
      expandOrderTypeEnumDesc
      markList
    }
    createBy {
      phoneNum
      userId
      userName
    }
    billId
  }
}

# 国产货采购:根据采购id获取商品列表
query listCommodityByDomesticPurchaseId($domesticPurchaseId: ID!, $expandOrderId: ID) {
  listCommodityByDomesticPurchaseId(
    domesticPurchaseId: $domesticPurchaseId
    expandOrderId: $expandOrderId
  ) {
    actualTotalQuantity
    actualUnitQuantity
    amount
    batchId
    commoditySku {
      categoryId
      categoryName
      commodityId
      commodityName
      commoditySkuId
      commoditySkuName
      commoditySpecOptionId
      commoditySpecOptionName
      conversion
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
    }
    expandOrderTypeEnum
    id
    orderId
    orderType
    price
    priceType {
      unitId
      unitName
    }
    runCode
    stockBatch {
      batchCode
      batchId
      customerBelongInfo {
        customerId
        customerName
        customerType
      }
      totalQuantity
      unitQuantity
    }
    totalQuantity
    totalType {
      unitId
      unitName
    }
    unitQuantity
    unitType {
      unitId
      unitName
    }
    batchCode
    canReturnTotalQuantity
    canReturnUnitQuantity
    deductTotalQuantity
    deductUnitQuantity
    returnTotalQuantity
    returnUnitQuantity
    sourceBatchId
    warehouseId
    index
    canApplyStock
  }
}

# 国产货采购:获取国产集采货列表
query pageDomesticPurchaseOrder($page: Page!, $pageDomesticPurchaseFilter: PageDomesticPurchaseFilter!) {
  pageDomesticPurchaseOrder(
    page: $page
    pageDomesticPurchaseFilter: $pageDomesticPurchaseFilter
  ) {
    pageCurrent
    pageSize
    totalRecords
    records {
      amount
      belongOrg {
        orgId
        orgName
      }
      code
      commodityItems {
        actualTotalQuantity
        actualUnitQuantity
        amount
        batchCode
        batchId
        canApplyStock
        canReturnTotalQuantity
        canReturnUnitQuantity
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        deductTotalQuantity
        deductUnitQuantity
        expandOrderTypeEnum
        id
        index
        orderId
        orderType
        price
        priceType {
          unitId
          unitName
        }
        returnTotalQuantity
        returnUnitQuantity
        runCode
        sourceBatchId
        stockBatch {
          batchCode
          batchId
          customerBelongInfo {
            customerId
            customerName
            customerType
          }
          totalQuantity
          unitQuantity
        }
        totalQuantity
        totalType {
          unitId
          unitName
        }
        unitQuantity
        unitType {
          unitId
          unitName
        }
        warehouseId
      }
      commodityType
      commodityTypeDesc
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      customer {
        customerId
        customerName
        customerType
      }
      id
      matchingSource {
        carNo
        departureDate
        matchDate
        matchSource
        matchSourceName
        runCode
        trailerNo
      }
      purchaseDate
      runCode
      status
      statusDesc
      subType
      subTypeDesc
      supplier {
        supplierId
        supplierName
      }
      warehouse {
        warehouseId
        warehouseName
      }
    }
  }
}

# 国产货采购:申请增加库存量,待库管进行审核,返回审核状态
mutation addCommodityStock($addCommodityStockInput: AddCommodityStockInput) {
  addCommodityStock(addCommodityStockInput: $addCommodityStockInput)
}

# 国产货采购扩展单:根据扩展单id查询
query detailExpandOrder($idsInput: IdsInput!) {
  detailExpandOrder(idsInput: $idsInput) {
    belongOrg {
      orgId
      orgName
    }
    billId
    code
    commodities {
      actualTotalQuantity
      actualUnitQuantity
      amount
      canReturnTotalQuantity
      canReturnUnitQuantity
      commodity {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      expandOrderTypeEnum
      id
      price
      priceType {
        unitId
        unitName
      }
      totalQuantity
      unitQuantity
      index
      batchId
      sourceBatchId
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
    }
    customer {
      customerId
      customerName
      customerType
    }
    fileImages
    freightTotalAmount
    id
    matchingSource {
      carNo
      departureDate
      matchDate
      matchSource
      matchSourceName
      runCode
      trailerNo
    }
    purchaseCode
    remark
    status
    supplier {
      supplierId
      supplierName
    }
    type
    typeDesc
    warehouse {
      warehouseId
      warehouseName
    }
    commodityType
    extendLabelId
    commodityTypeDesc
    freightItemList {
      amount
      costId
      costName
      data
      extendId
      note
      ruleId
      supplier {
        supplierId
        supplierName
      }
      dictItemId
    }
    statusDesc
  }
}

# 国产货采购扩展单:取消扩展单
mutation cancelExpandOrder($changeStatusExpandOrderInput: ChangeStatusExpandOrderInput!) {
  cancelExpandOrder(changeStatusExpandOrderInput: $changeStatusExpandOrderInput)
}

# 国产货采购扩展单:创建扩展单,返回的是扩展单id
mutation createExpandOrder($createExpandOrderInput: CreateExpandOrderInput!) {
  createExpandOrder(createExpandOrderInput: $createExpandOrderInput)
}

# 国产货采购扩展单:修改扩展单
mutation editExpandOrder($createExpandOrderInput: CreateExpandOrderInput, $expandOrderId: ID!) {
  editExpandOrder(
    createExpandOrderInput: $createExpandOrderInput
    expandOrderId: $expandOrderId
  )
}

# 国产货采购扩展单:提交扩展单
mutation submitExpandOrder($changeStatusExpandOrderInput: ChangeStatusExpandOrderInput!) {
  submitExpandOrder(changeStatusExpandOrderInput: $changeStatusExpandOrderInput)
}

# 国产货采购:根据采购单id获取操作日志
query listDomesticPurchaseOperationLog($domesticPurchaseOperationLogInput: DomesticPurchaseOperationLogInput) {
  listDomesticPurchaseOperationLog(
    domesticPurchaseOperationLogInput: $domesticPurchaseOperationLogInput
  ) {
    createUser {
      phoneNum
      userId
      userName
    }
    beforeStatus
    beforeStatusDesc
    createTime
    note
    status
    statusDesc
  }
}

# 费用单操作（接入费用模板）:退货单修改退货金额
mutation updateBill2ReturnAmount($input: UpdateBill2PaymentInput!) {
  updateBill2ReturnAmount(input: $input)
}

# 国产货采购扩展单:列表分页
query pageExpandOrder($input: PageExpandOrderInput, $page: Page) {
  pageExpandOrder(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      createUser {
        phoneNum
        userId
        userName
      }
      applyId
      businessInfo {
        belongOrg {
          orgId
          orgName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
        }
        supplier {
          supplierId
          supplierName
        }
        warehouse {
          warehouseId
          warehouseName
        }
        applyId
        commodityType
        commodityTypeDesc
        purchaseCode
        purchaseTime
        runCode
        createUser {
          phoneNum
          userId
          userName
        }
        createTime
        matchingSource {
          carNo
          departureDate
          matchDate
          matchSource
          matchSourceName
          runCode
          trailerNo
        }
      }
      code
      commodityItems {
        commodity {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
        priceType {
          unitId
          unitName
        }
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        actualTotalQuantity
        actualUnitQuantity
        amount
        batchId
        canReturnTotalQuantity
        canReturnUnitQuantity
        expandOrderTypeEnum
        id
        index
        price
        sourceBatchId
        totalQuantity
        unitQuantity
      }
      createTime
      id
      runCode
      status
      statusDesc
      totalAmount
      type
      typeDesc
    }
    totalRecords
  }
}

# 国产货采购扩展单:角标统计
query expandOrderBadge($input: ExpandOrderBadgeInput) {
  expandOrderBadge(input: $input) {
    completed
    toBeDelivered
    toBeSubmit
  }
}