# 内部采购: 详情页
query internalPurchaseOrder($input: PitayaInternalPurchaseIDInput!) {
  internalPurchaseOrder(input: $input) {
    belongOrg {
      orgId
      orgName
    }
    billDetailsList {
      billCostData
      billDetailId
      billMainId
      businessItemValue
      costAmount
      costId
      costName
      dictItemId
      note
      ruleCode
      ruleId
      showField
      supplier {
        supplierId
        supplierName
      }
      paymentType
    }
    billMainId
    commodities {
      commoditySku {
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      purchasePrice
      purchasePriceType {
        unitId
        unitName
      }
      purchaseQuantity {
        totalQuantity
        unitQuantity
      }
      purchaseTotalPrice
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
      mark
      markName
    }
    commodityTotalSalePrice
    commodityTypeId
    commodityTypeName
    createBy {
      phoneNum
      userId
      userName
    }
    createTime
    customer {
      customerId
      customerName
      customerType
      lastLevelId
      lastLevelName
    }
    isConfirmed
    purchaseCode
    purchaseId
    purchaseStatus
    purchaseStatusName
    purchaseTime
    supplier {
      supplierId
      supplierName
    }
    templateId
    totalTransportFees
    warehouse {
      warehouseId
      warehouseName
    }
    logs {
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      logType
      logTypeText
    }
    relationBillDetail {
      billDetailList {
        supplier {
          supplierId
          supplierName
        }
        billCostData
        billDetailId
        billMainId
        businessItemValue
        costAmount
        costId
        costName
        dictItemId
        note
        paymentType
        ruleCode
        ruleId
        showField
      }
      templateId
    }
    sourceBillMainId
    purchaseSubType
    purchaseSubTypeName
    costShowFlag
    note
    isTaskReceived
    runCode
    extOrderList {
      billDetailInfoDetailPayloadList {
        billDetailAmount
        billDetailsList {
          supplier {
            supplierId
            supplierName
          }
          billCostData
          billDetailId
          billMainId
          businessItemValue
          costAmount
          costId
          costName
          dictItemId
          note
          paymentType
          ruleCode
          ruleId
          showField
        }
        billMainId
        billTemplateId
      }
      extendCommodityList {
        batchInfo {
          customer {
            customerId
            customerName
            customerType
            lastLevelId
            lastLevelName
          }
          warehouse {
            warehouseId
            warehouseName
          }
          batchCode
          batchId
          commodityTypeId
          commodityTypeName
          createTime
          totalQuantity
          unitQuantity
        }
        commoditySku {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
        canApplyStock
        canOutStockQuantity {
          totalQuantity
          unitQuantity
        }
        canReturnQuantity {
          totalQuantity
          unitQuantity
        }
        commodityId
        commodityType
        id
        inStockNetQuantity {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          totalQuantity
          unitQuantity
        }
        index
        mark
        markName
        outStockNetQuantity {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          totalQuantity
          unitQuantity
        }
        purchaseInfo {
          priceType {
            unitId
            unitName
          }
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          amount
          price
          totalQuantity
          unitQuantity
        }
        returnQuantityAndPriceInfo {
          priceType {
            unitId
            unitName
          }
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          amount
          price
          totalQuantity
          unitQuantity
        }
        sourceBatchId
      }
      extendMainInfo {
        createBy {
          phoneNum
          userId
          userName
        }
        createTime
        extendCode
        extendId
        extendStatus
        extendStatusDesc
        extendSubType
        extendSubTypeDesc
        extendType
        extendTypeDesc
        remark
      }
      purchaseMainInfo {
        belongOrg {
          orgId
          orgName
        }
        createBy {
          phoneNum
          userId
          userName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
          lastLevelName
        }
        supplier {
          supplierId
          supplierName
        }
        user {
          phoneNum
          userId
          userName
        }
        warehouse {
          warehouseId
          warehouseName
        }
        code
        createTime
        id
        manualCode
        note
        purchaseDate
        purchaseSubType
        purchaseSubTypeName
        runCode
        statusEnum
        statusEnumDesc
      }
    }
    extOrderNum
  }
}

# 内部采购: 列表页以及搜索
query pageInternalPurchase($input: PitayaPageInternalPurchaseInput!, $page: Page!) {
  pageInternalPurchase(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      belongOrg {
        orgId
        orgName
      }
      billDetailsList {
        billCostData
        billDetailId
        billMainId
        businessItemValue
        costAmount
        costId
        costName
        dictItemId
        note
        ruleCode
        ruleId
        showField
        supplier {
          supplierId
          supplierName
        }
        paymentType
      }
      billMainId
      commodities {
        commoditySku {
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        purchasePrice
        purchasePriceType {
          unitId
          unitName
        }
        purchaseQuantity {
          totalQuantity
          unitQuantity
        }
        purchaseTotalPrice
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      commodityTotalSalePrice
      commodityTypeId
      commodityTypeName
      createBy {
        phoneNum
        userId
        userName
      }
      createTime
      customer {
        customerId
        customerName
        customerType
        lastLevelId
        lastLevelName
      }
      isConfirmed
      purchaseCode
      purchaseId
      purchaseStatus
      purchaseStatusName
      purchaseTime
      supplier {
        supplierId
        supplierName
      }
      templateId
      totalTransportFees
      warehouse {
        warehouseId
        warehouseName
      }
      purchaseSubType
      purchaseSubTypeName
      isTaskReceived
      note
      runCode
      sourceBillMainId
    }
    totalRecords
  }
}

# 内部采购: 状态统计
query pitayaCountInternalPurchaseStatus {
  pitayaCountInternalPurchaseStatus {
    toBeReceived
    received
  }
}

# 内部采购: 确认
mutation confirmInternalPurchase($input: PitayaInternalPurchaseConfirmInput!) {
  confirmInternalPurchase(input: $input)
}

# 内部采购: 售后单状态为`待处理`的采购单数量
query countInternalPurchaseByExtendStatus($countInternalPurchaseByExtStatusInput: CountInternalPurchaseByExtStatusInput) {
  countInternalPurchaseByExtendStatus(
    countInternalPurchaseByExtStatusInput: $countInternalPurchaseByExtStatusInput
  )
}