query purchaseReturnCommodities($purchaseReturnCommoditiesInput: PurchaseReturnCommoditiesInput) {
  purchaseReturnCommodities(
    purchaseReturnCommoditiesInput: $purchaseReturnCommoditiesInput
  ) {
    commoditySku {
      commoditySkuId
      commoditySkuName
      commodityId
      commodityName
      commoditySpecOptionId
      commoditySpecOptionName
      conversion
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
    }
    inBoundQuantity {
      unitQuantity
      totalQuantity
    }
    stockQuantity {
      unitQuantity
      totalQuantity
    }
    unitPrice {
      unit {
        unitId
        unitName
      }
      quantity
    }
    amount
    returnableQuantity {
      unitQuantity
      totalQuantity
    }
    canApply
  }
}

query pagePurchaseReturn($pagePurchaseReturnInput: PagePurchaseReturnInput, $page: Page) {
  pagePurchaseReturn(
    pagePurchaseReturnInput: $pagePurchaseReturnInput
    page: $page
  ) {
    records {
      returnId
      returnType
      returnTypeName
      status
      statusName
      applyCode
      note
      supplier {
        supplierId
        supplierName
      }
      customer {
        customerId
        customerName
        customerType
      }
      warehouse {
        warehouseId
        warehouseName
      }
      commodityType
      commodityTypeName
      user {
        userId
        userName
        phoneNum
      }
      createTime
      returnsCommodityRespList {
        returnId
        commoditySku {
          commoditySkuId
          commoditySkuName
          commodityId
          commodityName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
        }
        unitType {
          unitId
          unitName
        }
        unitQuantity
        totalType {
          unitId
          unitName
        }
        totalQuantity
        unitPrice
        totalPrice
        unitPriceType {
          unitId
          unitName
        }
        finishedQuantity {
          unitQuantity
          totalQuantity
        }
        returnsStockQuantity {
          returnableQuantity {
            unitQuantity
            totalQuantity
          }
          inBoundQuantity {
            unitQuantity
            totalQuantity
          }
        }
      }
      returnOtherRespList {
        costId
        ruleId
        note
        amount
        data
        supplier {
          supplierId
          supplierName
        }
      }
      billId
      flowLogs {
        type
        typeName
        note
        createTime
        createBy
        createUserName
        flowId
      }
      returnCode
      applyBillId
      manualCode
      belongOrg {
        orgId
        orgName
      }
    }
    pageCurrent
    pageSize
    totalRecords
  }
}

query getPurchaseReturn($getPurchaseReturnInput: GetPurchaseReturnInput) {
  getPurchaseReturn(getPurchaseReturnInput: $getPurchaseReturnInput) {
    returnId
    returnType
    returnTypeName
    status
    statusName
    applyCode
    applyId
    note
    supplier {
      supplierId
      supplierName
    }
    customer {
      customerId
      customerName
      customerType
    }
    warehouse {
      warehouseId
      warehouseName
    }
    commodityType
    commodityTypeName
    user {
      userId
      userName
      phoneNum
    }
    createTime
    returnsCommodityRespList {
      returnId
      commoditySku {
        commoditySkuId
        commoditySkuName
        commodityId
        commodityName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
      }
      unitType {
        unitId
        unitName
      }
      unitQuantity
      totalType {
        unitId
        unitName
      }
      totalQuantity
      unitPrice
      totalPrice
      unitPriceType {
        unitId
        unitName
      }
      finishedQuantity {
        unitQuantity
        totalQuantity
      }
      returnsStockQuantity {
        returnableQuantity {
          unitQuantity
          totalQuantity
        }
        inBoundQuantity {
          unitQuantity
          totalQuantity
        }
      }
    }
    returnOtherRespList {
      costId
      ruleId
      note
      amount
      data
      supplier {
        supplierId
        supplierName
      }
    }
    billId
    flowLogs {
      type
      typeName
      note
      createTime
      createBy
      createUserName
      flowId
    }
    returnCode
    applyBillId
    manualCode
    belongOrg {
      orgId
      orgName
    }
    templateId
  }
}

query returnStatusStatistic($returnStatusStatisticInput: ReturnStatusStatisticInput) {
  returnStatusStatistic(returnStatusStatisticInput: $returnStatusStatisticInput) {
    waitSubmitCount
    waitProcessedCount
    completeCount
    cancelCount
  }
}

mutation createPurchaseReturn($purchaseReturnInsertInput: PurchaseReturnInsertInput) {
  createPurchaseReturn(purchaseReturnInsertInput: $purchaseReturnInsertInput) {
    id
  }
}

mutation updatePurchaseReturn($updatePurchaseReturnInput: UpdatePurchaseReturnInput) {
  updatePurchaseReturn(updatePurchaseReturnInput: $updatePurchaseReturnInput)
}

mutation cancelPurchaseReturnOrder($cancelPurchaseReturnOrderInput: CancelPurchaseReturnOrderInput) {
  cancelPurchaseReturnOrder(
    cancelPurchaseReturnOrderInput: $cancelPurchaseReturnOrderInput
  )
}

mutation submitPurchaseReturnOrder($submitPurchaseReturnOrderInput: SubmitPurchaseReturnOrderInput) {
  submitPurchaseReturnOrder(
    submitPurchaseReturnOrderInput: $submitPurchaseReturnOrderInput
  )
}

mutation addStockQuantity($addStockQuantityInput: AddStockQuantityInput) {
  addStockQuantity(addStockQuantityInput: $addStockQuantityInput)
}

# 采购退货: 状态统计
query individualPurchaseReturnBadge($input: IndividualPurchaseReturnBadgeInput) {
  individualPurchaseReturnBadge(input: $input) {
    completed
    toBeDelivered
    toBeSubmit
  }
}

# 采购退货: 退货单详情
query individualPurchaseReturnDetail($returnId: ID!) {
  individualPurchaseReturnDetail(returnId: $returnId) {
    billId
    businessInfo {
      belongOrg {
        orgId
        orgName
      }
      customer {
        customerId
        customerName
        customerType
        lastLevelId
      }
      supplier {
        supplierId
        supplierName
      }
      warehouse {
        warehouseId
        warehouseName
      }
      businessType
      businessTypeDesc
      commodityType
      commodityTypeDesc
      purchaseCode
      purchaseTime
      runCode
      createUser {
        phoneNum
        userId
        userName
      }
      createTime
    }
    commodities {
      batchInfo {
        warehouse {
          warehouseId
          warehouseName
        }
        batchCode
        batchId
        commodityTypeId
        commodityTypeName
        createTime
        totalQuantity
        unitQuantity
      }
      commodity {
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        categoryId
        categoryName
        commodityId
        commodityName
        commoditySkuId
        commoditySkuName
        commoditySpecOptionId
        commoditySpecOptionName
        conversion
      }
      priceType {
        unitId
        unitName
      }
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
      amount
      canApplyStock
      index
      itemId
      markList
      markListDesc
      price
      purchaseId
      returnAmount
      returnId
      returnQuantity {
        totalQuantity
        unitQuantity
      }
      returnableAmount
      returnableQuantity {
        totalQuantity
        unitQuantity
      }
      stockInQuantity {
        totalQuantity
        unitQuantity
      }
      pricePosition
    }
    freightTotalAmount
    remark
    returnCode
    returnId
    returnStatus
    returnStatusDesc
    returnType
    returnTypeDesc
    runCode
    costItem {
      supplier {
        supplierId
        supplierName
      }
      amount
      costId
      costName
      data
      dictItemId
      extendId
      note
      ruleId
    }
    purchaseId
    historyFlag
  }
}

# 采购退货: 退货商品选择
query listIndividualPurchaseReturnCommodity($input: ListIndividualPurchaseReturnCommodityInput) {
  listIndividualPurchaseReturnCommodity(input: $input) {
    batchInfo {
      warehouse {
        warehouseId
        warehouseName
      }
      batchCode
      batchId
      commodityTypeId
      commodityTypeName
      createTime
      totalQuantity
      unitQuantity
    }
    commodity {
      totalType {
        unitId
        unitName
      }
      unitType {
        unitId
        unitName
      }
      categoryId
      categoryName
      commodityId
      commodityName
      commoditySkuId
      commoditySkuName
      commoditySpecOptionId
      commoditySpecOptionName
      conversion
    }
    priceType {
      unitId
      unitName
    }
    totalType {
      unitId
      unitName
    }
    unitType {
      unitId
      unitName
    }
    amount
    canApplyStock
    index
    itemId
    markList
    markListDesc
    price
    purchaseId
    returnAmount
    returnId
    returnQuantity {
      totalQuantity
      unitQuantity
    }
    returnableAmount
    returnableQuantity {
      totalQuantity
      unitQuantity
    }
    stockInQuantity {
      totalQuantity
      unitQuantity
    }
    pricePosition
  }
}

# 采购退货: 退货单列表
query pageIndividualPurchaseReturn($input: PageIndividualPurchaseReturnInput, $page: Page) {
  pageIndividualPurchaseReturn(input: $input, page: $page) {
    pageCurrent
    pageSize
    records {
      billId
      businessInfo {
        belongOrg {
          orgId
          orgName
        }
        customer {
          customerId
          customerName
          customerType
          lastLevelId
        }
        supplier {
          supplierId
          supplierName
        }
        warehouse {
          warehouseId
          warehouseName
        }
        businessType
        businessTypeDesc
        commodityType
        commodityTypeDesc
        purchaseCode
        purchaseTime
        runCode
        createUser {
          phoneNum
          userId
          userName
        }
        createTime
      }
      commodities {
        batchInfo {
          warehouse {
            warehouseId
            warehouseName
          }
          batchCode
          batchId
          commodityTypeId
          commodityTypeName
          createTime
          totalQuantity
          unitQuantity
        }
        commodity {
          totalType {
            unitId
            unitName
          }
          unitType {
            unitId
            unitName
          }
          categoryId
          categoryName
          commodityId
          commodityName
          commoditySkuId
          commoditySkuName
          commoditySpecOptionId
          commoditySpecOptionName
          conversion
        }
        priceType {
          unitId
          unitName
        }
        totalType {
          unitId
          unitName
        }
        unitType {
          unitId
          unitName
        }
        amount
        canApplyStock
        index
        itemId
        markList
        markListDesc
        price
        purchaseId
        returnAmount
        returnId
        returnQuantity {
          totalQuantity
          unitQuantity
        }
        returnableAmount
        returnableQuantity {
          totalQuantity
          unitQuantity
        }
        stockInQuantity {
          totalQuantity
          unitQuantity
        }
      }
      freightTotalAmount
      remark
      returnCode
      returnId
      returnStatus
      returnStatusDesc
      returnType
      returnTypeDesc
      runCode
    }
    totalRecords
  }
}

# 采购退货: 申请增加数量
mutation addSalePurchaseStockQuantity($input: addSalePurchaseStockQuantityInput) {
  addSalePurchaseStockQuantity(input: $input)
}

# 采购退货: 取消订单
mutation cancelIndividualPurchaseReturn($input: CancelIndividualPurchaseReturnInput) {
  cancelIndividualPurchaseReturn(input: $input)
}

# 采购退货: 新增采购退货订单
mutation createIndividualPurchaseReturn($input: CreateOrUpdateIndividualPurchaseReturnInput) {
  createIndividualPurchaseReturn(input: $input)
}

# 采购退货: 提交订单
mutation submitIndividualPurchaseReturn($input: SubmitIndividualPurchaseReturnInput) {
  submitIndividualPurchaseReturn(input: $input)
}

# 采购退货: 修改退货单
mutation updateIndividualPurchaseReturn($input: CreateOrUpdateIndividualPurchaseReturnInput) {
  updateIndividualPurchaseReturn(input: $input)
}

# 采购退货: 作废订单
mutation voidIndividualPurchaseReturn($input: VoidIndividualPurchaseReturnInput) {
  voidIndividualPurchaseReturn(input: $input)
}

# 采购退货: 撤销订单
mutation withdrawIndividualPurchaseReturn($input: WithdrawIndividualPurchaseReturnInput) {
  withdrawIndividualPurchaseReturn(input: $input)
}