# 配送费用单-接入中台: 所有状态数量角标
query countAllStatusDeliveryFee($countBillStatusInput: CountBillStatusInput) {
  countAllStatusDeliveryFee(countBillStatusInput: $countBillStatusInput) {
    billMainType
    billStatusNumberList {
      number
      status
    }
  }
}
